-- GENERATED by `pv discharge gen-axioms` (PVL-001 EV-6a, #4139). Do not edit: regenerate.
-- Every contract-bound theorem in the root's import cone may use only the pinned axioms. It is a SUBSET pin,
-- so a proof that needs fewer stays green; `sorryAx`, or any axiom outside the set, fails elaboration.
-- 164 pinned; 85 bound outside the root's import cone (ORPHANED-ROOT, pinned once EV-5c imports them).
import ProvableContracts

open Lean Elab Command in
/-- `n` exists and every axiom it depends on is in `pinned`. -/
def pvlAxiomsSubset (n : Name) (pinned : List Name) : CommandElabM Unit := do
  unless (← getEnv).contains n do
    throwError "MISSING-ROOT {n}"
  let axs ← collectAxioms n
  let extra := axs.toList.filter (fun a => !pinned.contains a)
  unless extra.isEmpty do
    throwError "AXIOMS {n}: {extra} outside the pinned set"

open Lean in
/-- formalization.yaml `status.axioms`, plus every axiom escape-allowlist.yaml exempts. -/
def pvlPinned : List Name := [`propext, `Classical.choice, `Quot.sound, `ProvableContracts.DPO.sigmoid_bounded, `ProvableContracts.DPO.dpo_loss_zero_at_strong_preference, `ProvableContracts.DPO.dpo_gradient_formula, `ProvableContracts.CooperativeMatrix.f16_accumulation_error_bound, `ProvableContracts.NF4.nf4_lut, `ProvableContracts.NF4.nf4_lut_monotone, `ProvableContracts.NF4.nf4_lut_bounded]

run_cmd pvlAxiomsSubset `ProvableContracts.AdamW.decay_update_eq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_bias_antitone pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_bias_linear pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_bias_nonpos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_bias_self pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_causal_keeps_past pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_causal_masks_future pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_head_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_head_zero_eight pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_antitone pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_ggml pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_lt_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_real_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.alibi_slope_strict_anti pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.dist_comm pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Alibi.dist_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.attention_output_bounded pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.attention_weight_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.attention_weights_bounded pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.attention_weights_sum_to_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.causal_mask_zeroes_future pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.convex_comb_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.le_convex_comb pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.scale_factor_ne_linear pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.scale_factor_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Attention.scale_factor_sq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.attention_entropy_le_log_card pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.attention_entropy_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.dot_sq_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.mean_smul pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.scaledScores_apply pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.scaled_score_abs_le_sqrt pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.softmax_le_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.softmax_max_subtraction_invariant pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.variance_scaled_by_inv_sqrt_normalizes pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.AttentionScaling.variance_smul pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv1d_valid_length pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv1d_valid_length_eq_outLen pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_abs_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_add pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_linear pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_shift pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_shift_eq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_smul pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.conv_zero_eq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Conv1D.outLen_valid pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Elementwise.relu_idempotent pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Elementwise.relu_monotone pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Elementwise.relu_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Elementwise.relu_of_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Elementwise.relu_of_nonpos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.embed_dim pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_deterministic pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_finite pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_hits_table pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_inbounds pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_length pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_length_seq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_preserves pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_row pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.«gather_row?» pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_scatter_id pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.gather_self_eq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.mean_pool_smul pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.onehot_select pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.sum_pool_add pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.sum_pool_smul pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.temp_identity pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.tied_apply pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.tied_row_eq pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.token_lt_vocab pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.token_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.unembed_apply pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Embedding.unembed_shape pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.clampMag_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.clampMag_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.decode_abs_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.gridRound_mono pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.range_e4m3 pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.range_e5m2 pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.roundtrip_e4m3 pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.roundtrip_e5m2 pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.roundtrip_ulp pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.sign_preservation_neg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.sign_preservation_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.FP8.zero_roundtrip pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_le_self_of_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_nonneg_of_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_nonneg_of_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_nonpos_of_neg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_right_factor_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_strictMono_of_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.gelu_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gelu.tanh_strictMono pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.attn_weights_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.attn_weights_sum_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.convex_combination_bounds pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.gqa_output_convex pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.kvHead_eq_mul_div pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.kvHead_group pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.kvHead_group_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Gqa.kvHead_surjective pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LU.identity_is_unit_lower_triangular pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LU.identity_is_upper_triangular pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LU.identity_lu pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.centered_shift pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.layernorm_id_of_normalized pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.layernorm_idempotent pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.ln_denom_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.mean_layernorm_centering pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.mean_shift pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.sum_sub_mean_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.variance_layernorm_ratio pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.variance_layernorm_standardized pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.variance_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.LayerNorm.variance_shift pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.MatMul.matmul_assoc pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.MatMul.matmul_identity_left pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.MatMul.matmul_identity_right pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Quantization.roundtrip_bound pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.QuantizedDotProduct.bsum_decomposition_total pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.QuantizedDotProduct.bsum_precompute_eq_inline pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.RMSNorm.mean_sq_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.RMSNorm.mean_sq_scale pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.RMSNorm.rms_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.RMSNorm.rms_scale_zero_eps pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.penalty_one_identity pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.penalty_reduces_negative pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.penalty_reduces_positive pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.tempScale_mono_le pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.tempScale_monotone pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.tempScale_preserves_argmax pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.topk_one_is_argmax pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.topk_separates pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.topk_zero_keeps_all pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sampling.valid_temperature_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.mul_exp_ge_neg_inv_e pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_bounded pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_lt_exp pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_lt_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_mono pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_strictMono pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.sigmoid_symmetry pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.silu_gt_neg_inv_e pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.silu_gt_neg_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.silu_mono_nonneg pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.silu_strictMono_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.silu_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.swiglu_gate_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.swiglu_gating_identity pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.swiglu_value_zero pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Sigmoid.swiglu_zero_preservation pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.monotone pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.partition_of_unity pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.shift_invariance pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.softmax_bounded pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.softmax_lt_one pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.softmax_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Softmax.sum_exp_pos pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Transpose.transpose_element pvlPinned
run_cmd pvlAxiomsSubset `ProvableContracts.Transpose.transpose_involution pvlPinned
