-- Root module: imports all definitions and theorems
-- Linear algebra definitions
-- Linear algebra theorems
-- Elementwise operations
-- Quantization
-- AdamW optimizer
-- Discrete Fourier Transform
import ProvableContracts.Basic
import ProvableContracts.Defs.AbsolutePosition
import ProvableContracts.Defs.AdamW
import ProvableContracts.Defs.Alibi
import ProvableContracts.Defs.BLAS
import ProvableContracts.Defs.BatchNorm
import ProvableContracts.Defs.CMAES
import ProvableContracts.Defs.Cholesky
import ProvableContracts.Defs.Conv1D
import ProvableContracts.Defs.CrossEntropy
import ProvableContracts.Defs.Elementwise
import ProvableContracts.Defs.Embedding
import ProvableContracts.Defs.FFT
import ProvableContracts.Defs.GEMV
import ProvableContracts.Defs.Gelu
import ProvableContracts.Defs.LU
import ProvableContracts.Defs.LayerNorm
import ProvableContracts.Defs.MatMul
import ProvableContracts.Defs.QR
import ProvableContracts.Defs.Quantization
import ProvableContracts.Defs.RMSNorm
import ProvableContracts.Defs.SVD
import ProvableContracts.Defs.Sampling
import ProvableContracts.Defs.Sigmoid
import ProvableContracts.Defs.Softmax
import ProvableContracts.Defs.Sparse
import ProvableContracts.Defs.Transpose
import ProvableContracts.Theorems.AbsolutePosition.Core
import ProvableContracts.Theorems.AdamW.WeightDecay
import ProvableContracts.Theorems.Alibi.Basic
import ProvableContracts.Theorems.Alibi.Slopes
import ProvableContracts.Theorems.Attention.ScaledDotProduct
import ProvableContracts.Theorems.Attention.Scaling
import ProvableContracts.Theorems.BLAS.SyrkSymmetric
import ProvableContracts.Theorems.BatchNorm.Centering
import ProvableContracts.Theorems.BatchNorm.DenominatorPositive
import ProvableContracts.Theorems.BatchNorm.EvalUsesRunning
import ProvableContracts.Theorems.BatchNorm.RunningVariance
import ProvableContracts.Theorems.CMAES.StepSizePositive
import ProvableContracts.Theorems.CMAES.WeightsNormalized
import ProvableContracts.Theorems.CMAES.CovarianceSymmetry
import ProvableContracts.Theorems.CMAES.CovariancePositiveDefinite
import ProvableContracts.Theorems.Cholesky.SPD
import ProvableContracts.Theorems.Conv1D.Bound
import ProvableContracts.Theorems.Conv1D.Linearity
import ProvableContracts.Theorems.Conv1D.OutputLength
import ProvableContracts.Theorems.Conv1D.ShiftEquivariance
import ProvableContracts.Theorems.Conv1D.ZeroInput
import ProvableContracts.Theorems.CrossEntropy.LogSoftmaxBound
import ProvableContracts.Theorems.CrossEntropy.NonNegativity
import ProvableContracts.Theorems.CrossEntropy.SoftmaxBackward
import ProvableContracts.Theorems.Elementwise.AddCommutative
import ProvableContracts.Theorems.Elementwise.LeakyReLU
import ProvableContracts.Theorems.Elementwise.MulScalarAssoc
import ProvableContracts.Theorems.Elementwise.ReLUNonNeg
import ProvableContracts.Theorems.Embedding.Bounds
import ProvableContracts.Theorems.Embedding.Determinism
import ProvableContracts.Theorems.Embedding.Finite
import ProvableContracts.Theorems.Embedding.Rows
import ProvableContracts.Theorems.Embedding.Shape
import ProvableContracts.Theorems.Embedding.Algebra
import ProvableContracts.Theorems.FFT.Parseval
import ProvableContracts.Theorems.FP8.Interchange
import ProvableContracts.Theorems.GEMV.Correctness
import ProvableContracts.Theorems.Gelu.GeluMono
import ProvableContracts.Theorems.Gelu.GeluSign
import ProvableContracts.Theorems.Gelu.GeluBounds
import ProvableContracts.Theorems.Gelu.GeluZero
import ProvableContracts.Theorems.Gqa.ConvexBound
import ProvableContracts.Theorems.Gqa.Distribution
import ProvableContracts.Theorems.Gqa.HeadMapping
import ProvableContracts.Theorems.LU.Existence
import ProvableContracts.Theorems.LayerNorm.Centering
import ProvableContracts.Theorems.LayerNorm.DenominatorPositive
import ProvableContracts.Theorems.LayerNorm.Idempotency
import ProvableContracts.Theorems.LayerNorm.ShiftInvariance
import ProvableContracts.Theorems.LayerNorm.Standardization
import ProvableContracts.Theorems.MatMul.Associativity
import ProvableContracts.Theorems.MatMul.Identity
import ProvableContracts.Theorems.QR.Orthogonality
import ProvableContracts.Theorems.Quantization.RoundtripBound
import ProvableContracts.Theorems.QuantizedDotProduct.BsumDecomposition
import ProvableContracts.Theorems.QuantizedDotProduct.ErrorBound
import ProvableContracts.Theorems.RMSNorm.DenominatorPositive
import ProvableContracts.Theorems.RMSNorm.ScaleInvariance
import ProvableContracts.Theorems.SVD.NonNegative
import ProvableContracts.Theorems.Sampling.RepeatPenalty
import ProvableContracts.Theorems.Sampling.TemperatureScaling
import ProvableContracts.Theorems.Sampling.TopK
import ProvableContracts.Theorems.Sigmoid.SigmoidBounded
import ProvableContracts.Theorems.Sigmoid.SigmoidSymmetry
import ProvableContracts.Theorems.Sigmoid.SiluZero
import ProvableContracts.Theorems.Sigmoid.SwigluZero
import ProvableContracts.Theorems.Sigmoid.SiluLowerBound
import ProvableContracts.Theorems.Sigmoid.SiluMonotone
import ProvableContracts.Theorems.Sigmoid.SwigluGating
import ProvableContracts.Theorems.Softmax.Bounded
import ProvableContracts.Theorems.Softmax.Monotonicity
import ProvableContracts.Theorems.Softmax.NonNegativity
import ProvableContracts.Theorems.Softmax.PartitionOfUnity
import ProvableContracts.Theorems.Softmax.ShiftInvariance
import ProvableContracts.Theorems.Sparse.SpMVLinear
import ProvableContracts.Theorems.Transpose.Involution

-- Modules nothing imported, so `lake build` never compiled them and leanchecker never
-- re-checked their theorems (#4244). scripts/check_lean_modules_reachable.sh keeps every
-- module under ProvableContracts/ reachable from here.
import ProvableContracts.Defs.GPU
import ProvableContracts.Defs.Image
import ProvableContracts.Defs.Rand
import ProvableContracts.Defs.Tensor
import ProvableContracts.Theorems.AdamW.Adam_Moments
import ProvableContracts.Theorems.AdamW.Adam_Variance
import ProvableContracts.Theorems.AdamW.Analytic
import ProvableContracts.Theorems.AdamW.Bias_Correction
import ProvableContracts.Theorems.AdamW.Weight_Update
import ProvableContracts.Theorems.AprCode.HarnessIrRoundtrip
import ProvableContracts.Theorems.BLAS.Trmm
import ProvableContracts.Theorems.BLAS.Trsm
import ProvableContracts.Theorems.CrossEntropy.CoreSoftmaxInvariants
import ProvableContracts.Theorems.DPO
import ProvableContracts.Theorems.F16.Conversion
import ProvableContracts.Theorems.FFT.Bluestein
import ProvableContracts.Theorems.FFT.Fft2d
import ProvableContracts.Theorems.FFT.Fft3d
import ProvableContracts.Theorems.FFT.FftBatched
import ProvableContracts.Theorems.Fusion.Correctness
import ProvableContracts.Theorems.GPU.DimensionIndependence
import ProvableContracts.Theorems.GatedDeltaNet.Recurrence
import ProvableContracts.Theorems.GgufExportSymmetry.Roundtrip
import ProvableContracts.Theorems.Image.Canny
import ProvableContracts.Theorems.Image.ConnectedComponents
import ProvableContracts.Theorems.Image.Conv2d
import ProvableContracts.Theorems.Image.Histogram
import ProvableContracts.Theorems.Image.HsvRoundtrip
import ProvableContracts.Theorems.Image.Morphology
import ProvableContracts.Theorems.Image.Resize
import ProvableContracts.Theorems.Image.RgbToGray
import ProvableContracts.Theorems.Image.Sobel
import ProvableContracts.Theorems.LoRA.Dare_Unbiased
import ProvableContracts.Theorems.LoRA.Lora_Shape
import ProvableContracts.Theorems.LoRA.Shape_Preservation
import ProvableContracts.Theorems.LoRA.Task_Vector
import ProvableContracts.Theorems.Lora.MergeForwardEquiv
import ProvableContracts.Theorems.MatMul.CooperativeTiling
import ProvableContracts.Theorems.MatMul.Distributivity
import ProvableContracts.Theorems.MatMul.MatVecLinearity
import ProvableContracts.Theorems.MatMul.Shape
import ProvableContracts.Theorems.MatMul.TransposeMul
import ProvableContracts.Theorems.Metrics.Regression
import ProvableContracts.Theorems.Metrics.RegressionAnalytic
import ProvableContracts.Theorems.Quantization.NF4Dequant
import ProvableContracts.Theorems.RMSNorm.NormalizedRMS
import ProvableContracts.Theorems.Rand.Philox
import ProvableContracts.Theorems.Rand.Threefry
import ProvableContracts.Theorems.Rope.Rope
import ProvableContracts.Theorems.Sigmoid.SiluAsymptotic
import ProvableContracts.Theorems.Sigmoid.SiluSign
import ProvableContracts.Theorems.Sparse.BsrSpmv
import ProvableContracts.Theorems.Sparse.SellSpmv
import ProvableContracts.Theorems.Sparse.Spgemm
import ProvableContracts.Theorems.Sparse.Spmm
import ProvableContracts.Theorems.Tensor.Einsum
import ProvableContracts.Theorems.TensorLayout.IndexAlgebra
import ProvableContracts.Theorems.TensorTranspose.Roundtrip
import ProvableContracts.Theorems.Tokenizer
