//! Full-model parity of the Rust Laya port against spike 025's fixture (plan 08-09; D-17, D-12).
//!
//! ENV-GATED, never `#[ignore]`: without `LAYA_MODEL_DIR` it prints
//! `SKIP: LAYA_MODEL_DIR not set` and returns, so CI compiles it and runs nothing (the real
//! 0.84 GB English root is not in CI; plan 08-12 decides whether it ever is).
//!
//! ```text
//! LAYA_MODEL_DIR=~/.cache/huggingface/hub/models--convaiinnovations--laya/snapshots/55cf4c4e… \
//!   cargo test -p aprender-decide --release --test laya_parity -- --nocapture
//! ```
//!
//! Optional: `LAYA_PARITY_FIXTURE` (default: the tracked spike-025 fixture, whose sha256 must be
//! the one laya-parity-v1 records) and `LAYA_LADDER_BIN` (the oracle's gitignored ladder dump,
//! regenerated by spike-025 `tools/oracle.py`; without it the ladder rung prints SKIP).
//!
//! The weights go through the SAME F16 path the packer and the verifier use
//! (`pack::load_checkpoint_for_scoring`: every tensor's raw bytes into an in-memory `.apr`,
//! widened by core's loader). Every bar is read from `contracts/laya-parity-v1.yaml`.

use aprender_decide::laya::temperature::{softmax_t, temperature_for};
use aprender_decide::laya::QType;
use aprender_decide::pack::load_checkpoint_for_scoring;
use aprender_decide::Task;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

const ENV_MODEL: &str = "LAYA_MODEL_DIR";
const ENV_FIXTURE: &str = "LAYA_PARITY_FIXTURE";
const ENV_LADDER: &str = "LAYA_LADDER_BIN";
const FIXTURE_REL: &str =
    ".planning/spikes/025-laya-rust-forward-parity/fixtures/laya-en_fixture.json";

#[derive(Deserialize)]
struct Fixture {
    ladder: Ladder,
    records: Vec<Record>,
}

#[derive(Deserialize)]
struct Ladder {
    n_tokens: usize,
    d: usize,
    blocks: Vec<String>,
}

#[derive(Deserialize)]
struct Record {
    state: String,
    rows: Vec<Row>,
    questions: serde_json::Value,
}

#[derive(Deserialize)]
struct Row {
    qid: String,
    t: String,
    ins: String,
    options: Vec<String>,
    ids: Vec<u32>,
    markers: Vec<usize>,
    qtype: usize,
    temperature: f32,
    logits: Vec<f32>,
    probs: Vec<f64>,
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn contract() -> serde_yaml::Value {
    let path = workspace_root().join("contracts/laya-parity-v1.yaml");
    let text = std::fs::read_to_string(&path).expect("read laya-parity-v1.yaml");
    serde_yaml::from_str(&text).expect("parse laya-parity-v1.yaml")
}

fn bar(c: &serde_yaml::Value, equation: &str) -> f64 {
    c["equations"][equation]["float_tolerance"]
        .as_f64()
        .unwrap_or_else(|| panic!("laya-parity-v1 equations.{equation}.float_tolerance"))
}

/// NaN-visible running maximum: once either side is NaN the result stays NaN. `f64::max`
/// returns the non-NaN operand, so a plain `m.max(d)` fold drops a NaN seen earlier (A2-6).
fn nan_max(m: f64, d: f64) -> f64 {
    if m.is_nan() || d.is_nan() {
        f64::NAN
    } else {
        m.max(d)
    }
}

/// NaN-visible `delta <= bound` (the crate's `within` idiom).
fn within(delta: f64, bound: f64) -> bool {
    !delta.is_nan() && !bound.is_nan() && delta <= bound
}

fn max_abs(a: &[f32], b: &[f32]) -> f64 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    a.iter().zip(b).fold(0.0f64, |m, (&x, &y)| {
        nan_max(m, (f64::from(x) - f64::from(y)).abs())
    })
}

fn rms(a: &[f32]) -> f64 {
    (a.iter().map(|&x| f64::from(x) * f64::from(x)).sum::<f64>() / a.len() as f64).sqrt()
}

fn rel_rms(a: &[f32], reference: &[f32]) -> f64 {
    let diff: Vec<f32> = a.iter().zip(reference).map(|(x, y)| x - y).collect();
    rms(&diff) / rms(reference)
}

fn argmax<T: PartialOrd + Copy>(a: &[T]) -> usize {
    (0..a.len()).fold(0, |m, i| if a[i] > a[m] { i } else { m })
}

/// The ladder rung: emb / 28 layers / final / 2 head layers on the 158-token row.
fn ladder_rung(
    model: &aprender_decide::laya::Laya,
    fx: &Fixture,
    c: &serde_yaml::Value,
    ladder_bin: &Path,
) {
    let (l, d) = (fx.ladder.n_tokens, fx.ladder.d);
    let bytes = std::fs::read(ladder_bin).expect("read LAYA_LADDER_BIN");
    assert_eq!(
        bytes.len(),
        fx.ladder.blocks.len() * l * d * 4,
        "ladder bin is not blocks x n_tokens x d f32"
    );
    let ladder: Vec<f32> = bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect();
    let row = &fx.records[0].rows[0];
    assert_eq!(row.ids.len(), l, "the ladder row is record 0 row 0");
    let (emb_bar, layer_bar, final_bar) = (
        bar(c, "embeddings_abs"),
        bar(c, "per_layer_rel_rms"),
        bar(c, "final_norm_abs"),
    );
    let mut seen = Vec::new();
    let qtype = QType::from_index(row.qtype).expect("qtype");
    model
        .forward_row(&row.ids, &row.markers, qtype, |name, x| {
            if let Some(bi) = fx.ladder.blocks.iter().position(|b| b == name) {
                let r = &ladder[bi * l * d..(bi + 1) * l * d];
                seen.push((name.to_string(), max_abs(x, r), rel_rms(x, r)));
            }
        })
        .expect("ladder forward");
    assert_eq!(
        seen.len(),
        fx.ladder.blocks.len(),
        "every ladder block was tapped"
    );
    for (name, abs, rel) in &seen {
        println!("ladder {name}: max_abs {abs:.3e} rel_rms {rel:.3e}");
        let ok = match name.as_str() {
            "emb" => within(*abs, emb_bar),
            "final" => within(*abs, final_bar),
            _ => within(*rel, layer_bar),
        };
        assert!(ok, "ladder block {name} over its bar: abs {abs} rel {rel}");
    }
    // Positive evidence for `just _laya-leg-verdict laya_parity` (plan 08-22): printed only
    // after every tapped block passed its bar, so its absence means the rung did not run.
    println!("MEASURED ladder {} blocks within bars", seen.len());
}

/// FALSIFY-LAYA-PARITY-001 / -003 on the real English root: the spike-025 14-row fixture.
#[test]
fn full_model_reproduces_spike_025_fixture() {
    let Some(model_dir) = std::env::var_os(ENV_MODEL).map(PathBuf::from) else {
        println!("SKIP: {ENV_MODEL} not set");
        return;
    };
    let c = contract();
    let fixture_path = std::env::var_os(ENV_FIXTURE)
        .map_or_else(|| workspace_root().join(FIXTURE_REL), PathBuf::from);
    let fixture_bytes = std::fs::read(&fixture_path).unwrap_or_else(|e| {
        panic!(
            "{ENV_MODEL} is set but the parity fixture {} is unreadable: {e}",
            fixture_path.display()
        )
    });
    let fixture_sha = format!("{:x}", Sha256::digest(&fixture_bytes));
    let recorded = c["metadata"]["description"].as_str().expect("description");
    assert!(
        recorded.contains(&fixture_sha),
        "fixture sha256 {fixture_sha} is not the one laya-parity-v1 records"
    );
    let fx: Fixture = serde_json::from_slice(&fixture_bytes).expect("parse fixture");
    let n_rows: usize = fx.records.iter().map(|r| r.rows.len()).sum();
    let want_rows = c["constants"]["spike025_fixture_rows"]
        .as_u64()
        .expect("spike025_fixture_rows") as usize;
    assert_eq!(n_rows, want_rows, "fixture row count");

    // Any choice task binds the model; parity runs on the fixture rows' own questions.
    let bind: Task = Task::from_slice(
        &serde_json::to_vec(&fx.records[0].questions["department"]).expect("task json"),
    )
    .expect("record 0 `department` is a choice task");
    let t0 = std::time::Instant::now();
    let model = load_checkpoint_for_scoring(&model_dir, bind).expect("load the English root");
    println!(
        "load: {:.2} s through the F16 .apr path",
        t0.elapsed().as_secs_f64()
    );

    let (probs_bar, logits_bar) = (bar(&c, "probs_abs"), bar(&c, "logits_abs"));
    let max_len = c["constants"]["row_max_tokens"]
        .as_u64()
        .expect("row_max_tokens") as usize;
    let (mut ids_ok, mut argmax_ok, mut worst_p, mut worst_z) = (0usize, 0usize, 0f64, 0f64);
    let mut truncated_rows = 0usize;
    for (ri, rec) in fx.records.iter().enumerate() {
        for row in &rec.rows {
            let built = model
                .builder()
                .build(&rec.state, &row.t, &row.ins, &row.options)
                .expect("build row");
            assert_eq!(built.ids, row.ids, "rec {ri} {}: ids", row.qid);
            assert_eq!(built.markers, row.markers, "rec {ri} {}: markers", row.qid);
            ids_ok += 1;
            if row.ids.len() == max_len {
                assert!(
                    built.truncated,
                    "rec {ri} {}: the {max_len}-token row must report truncated (D-12)",
                    row.qid
                );
                truncated_rows += 1;
            }
            let qtype = QType::from_index(row.qtype).expect("qtype");
            let t = temperature_for(model.agent_config(), qtype, row.markers.len());
            assert_eq!(
                t.to_bits(),
                row.temperature.to_bits(),
                "rec {ri} {}: temperature {t} vs {}",
                row.qid,
                row.temperature
            );
            let z = model
                .forward_row(&built.ids, &built.markers, qtype, |_, _| {})
                .expect("forward");
            let p = softmax_t(&z, t);
            let dz = max_abs(&z, &row.logits);
            assert_eq!(
                p.len(),
                row.probs.len(),
                "rec {ri} {}: probability row length",
                row.qid
            );
            let dp = p
                .iter()
                .zip(&row.probs)
                .fold(0.0f64, |m, (a, b)| nan_max(m, (f64::from(*a) - b).abs()));
            let same = argmax(&p) == argmax(&row.probs);
            println!(
                "rec {ri} {} ({}, {} tokens): |dz| {dz:.3e} |dp| {dp:.3e} argmax {}",
                row.qid,
                row.t,
                row.ids.len(),
                if same { "same" } else { "FLIP" }
            );
            assert!(within(dz, logits_bar), "rec {ri} {}: |dz| {dz}", row.qid);
            assert!(within(dp, probs_bar), "rec {ri} {}: |dp| {dp}", row.qid);
            assert!(same, "rec {ri} {}: argmax", row.qid);
            argmax_ok += 1;
            worst_z = nan_max(worst_z, dz);
            worst_p = nan_max(worst_p, dp);
        }
    }
    assert_eq!(truncated_rows, 1, "exactly one 512-token truncation row");
    println!(
        "ids {ids_ok}/{n_rows}; argmax {argmax_ok}/{n_rows}; max |dp| {worst_p:.3e} (bar {probs_bar:e}); \
         max |dlogit| {worst_z:.3e} (bar {logits_bar:e}); truncated rows {truncated_rows}; ARCH {}",
        std::env::consts::ARCH
    );
    // Positive evidence for `just _laya-leg-verdict laya_parity` (plan 08-22): printed only
    // after every row passed, so a leg that measured nothing cannot produce them.
    println!(
        "MEASURED ids {ids_ok}/{n_rows} argmax {argmax_ok}/{n_rows} truncated {truncated_rows}"
    );
    println!(
        "MEASURED probs max_abs {worst_p:.3e} bar {probs_bar:e} logits max_abs {worst_z:.3e} bar {logits_bar:e} ARCH {}",
        std::env::consts::ARCH
    );

    match std::env::var_os(ENV_LADDER) {
        Some(p) => ladder_rung(&model, &fx, &c, Path::new(&p)),
        None => println!("SKIP ladder rung: {ENV_LADDER} not set"),
    }
}

/// A2-6 (plan 08-22): the probability rung's running maximum must keep a NaN seen EARLIER in the
/// row. `f64::max` returns the non-NaN operand, so the old `m.max(d)` fold turned `[NaN, 0.1]`
/// into 0.1 and a NaN row could pass the bar. Not env-gated: it needs no weights.
#[test]
fn nan_max_keeps_an_earlier_nan() {
    let folded = [f64::NAN, 0.1, 0.0]
        .iter()
        .fold(0.0f64, |m, &d| nan_max(m, d));
    assert!(folded.is_nan(), "an earlier NaN was dropped: {folded}");
    let later = [0.1, f64::NAN].iter().fold(0.0f64, |m, &d| nan_max(m, d));
    assert!(later.is_nan(), "a later NaN was dropped: {later}");
    assert_eq!(
        [0.1, 0.3, 0.2].iter().fold(0.0f64, |m, &d| nan_max(m, d)),
        0.3
    );
    assert!(
        !within(nan_max(0.0, f64::NAN), 1.0),
        "a NaN maximum must fail the bar"
    );
}
