[package]
name = "aprender-present-test"
description = "Testing harness for Presentar applications"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["tui", "terminal", "ui", "ratatui", "aprender"]
categories = ["command-line-interface"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "presentar_test"

[dependencies]
presentar-core = { workspace = true }
presentar-test-macros = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
