// ============================================================================
// Byte-equality oracle: apr's rendering of a model's own template == HF's (#3755)
// ============================================================================
//
// Fixtures: crates/aprender-serve/tests/fixtures/chat_templates/, regenerated by
// scripts/render_chat_template_reference.py from every GGUF in the host inventory.
// Each `<sha12>.jinja` is a model's `tokenizer.chat_template` as shipped, and
// reference.json holds transformers' rendering of it for three conversations x
// thinking {on, off, unset}. apr must reproduce every rendering byte for byte.

#[cfg(test)]
mod chat_template_embedded_oracle {
    use super::*;

    fn fixture_dir() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/chat_templates")
    }

    fn reference() -> serde_json::Value {
        let path = fixture_dir().join("reference.json");
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("oracle fixture {} unreadable: {e}", path.display()));
        serde_json::from_str(&text).expect("reference.json parses")
    }

    fn template(sha: &str) -> EmbeddedChatTemplate {
        let path = fixture_dir().join(format!("{sha}.jinja"));
        let source = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("oracle fixture {} unreadable: {e}", path.display()));
        EmbeddedChatTemplate::new(source)
            .unwrap_or_else(|e| panic!("template {sha} does not load: {e}"))
    }

    fn messages(reference: &serde_json::Value, set: &str) -> Vec<ChatMessage> {
        reference["message_sets"][set]
            .as_array()
            .unwrap_or_else(|| panic!("reference.json has no message set {set:?}"))
            .iter()
            .map(|m| {
                ChatMessage::new(
                    m["role"].as_str().expect("role"),
                    m["content"].as_str().expect("content"),
                )
            })
            .collect()
    }

    /// Every reference rendering, reproduced byte for byte.
    #[test]
    fn embedded_rendering_is_byte_equal_to_hf() {
        let reference = reference();
        let cases = reference["cases"].as_object().expect("cases");
        // Vacuity: an empty or shrunken fixture set must not pass.
        assert!(cases.len() >= 81, "only {} reference renderings", cases.len());
        let mut failures = Vec::new();
        for (key, expected) in cases {
            let mut parts = key.split('/');
            let (sha, set, mode) = (
                parts.next().expect("sha"),
                parts.next().expect("set"),
                parts.next().expect("mode"),
            );
            let thinking = match mode {
                "on" => Some(true),
                "off" => Some(false),
                "unset" => None,
                other => panic!("unknown mode {other:?} in {key}"),
            };
            let expected = expected.as_str().expect("rendering is a string");
            let got = template(sha)
                .render(&messages(&reference, set), true, thinking)
                .unwrap_or_else(|e| format!("<render error: {e}>"));
            if got != expected {
                let at = got
                    .bytes()
                    .zip(expected.bytes())
                    .position(|(a, b)| a != b)
                    .unwrap_or(got.len().min(expected.len()));
                failures.push(format!(
                    "{key}: first difference at byte {at}\n  apr: {:?}\n  hf:  {:?}",
                    &got[at.saturating_sub(20)..got.len().min(at + 40)],
                    &expected[at.saturating_sub(20)..expected.len().min(at + 40)]
                ));
            }
        }
        assert!(
            failures.is_empty(),
            "{} of {} renderings differ from {}:\n{}",
            failures.len(),
            cases.len(),
            reference["renderer"],
            failures.join("\n")
        );
    }

    /// Thinking capability, derived by rendering, for every template in the inventory.
    /// Qwen3-30B-A3B-Instruct-2507 (40c21f34cf67) carries `<think>` and has no thinking
    /// mode: a marker search would call it capable (aprender-62, #3723).
    #[test]
    fn thinking_modes_are_derived_by_rendering() {
        let expected = [
            ("57f1fd00f001", ThinkingModes::Both),    // Qwen3-8B
            ("5da44855ab7e", ThinkingModes::Both),    // Qwen3-0.6B
            ("8428c815ac94", ThinkingModes::Both),    // Qwen3-1.7B
            ("7f0e529032c2", ThinkingModes::Both),    // Qwen3.5-0.8B/2B/4B/9B
            ("e60df41481b6", ThinkingModes::Both),    // Qwen3.5-27B, -35B-A3B
            ("40c21f34cf67", ThinkingModes::OffOnly), // Qwen3-30B-A3B-Instruct-2507
            ("87710339d25b", ThinkingModes::OffOnly), // Qwen3-Coder-30B-A3B
            ("cd8e9439f057", ThinkingModes::OffOnly), // Qwen2.5 (0.5B, coder-0.5B)
            ("d5495a1e5db0", ThinkingModes::OffOnly), // Qwen2.5 (1.5B, coder-1.5B/7B)
        ];
        let index: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(fixture_dir().join("index.json")).expect("index.json"),
        )
        .expect("index.json parses");
        let fixtures = index.as_object().expect("index").len();
        assert_eq!(fixtures, expected.len(), "every inventory template needs an expectation");
        for (sha, modes) in expected {
            assert_eq!(template(sha).thinking_modes(), modes, "{sha} {}", index[sha]);
        }
    }

    /// A template whose generation prompt always opens `<think>` is ON only, and the
    /// three modes resolve and refuse as #3723 requires.
    #[test]
    fn on_only_template_and_resolution() {
        let on_only = EmbeddedChatTemplate::new(
            "{% for m in messages %}<|im_start|>{{ m.role }}\n{{ m.content }}<|im_end|>\n{% endfor %}\
             {% if add_generation_prompt %}<|im_start|>assistant\n<think>\n{% endif %}",
        )
        .expect("loads");
        assert_eq!(on_only.thinking_modes(), ThinkingModes::OnOnly);
        assert!(matches!(ThinkingModes::OnOnly.resolve(None), Ok(true)));
        assert!(matches!(ThinkingModes::Both.resolve(None), Ok(false)));
        assert!(matches!(ThinkingModes::OffOnly.resolve(None), Ok(false)));
        assert!(matches!(ThinkingModes::Both.resolve(Some(true)), Ok(true)));
        let refused = ThinkingModes::OffOnly.resolve(Some(true)).expect_err("refused");
        assert_eq!(
            refused.to_string(),
            "thinking on refused: this model's chat template supports thinking off only"
        );
        assert!(ThinkingModes::OnOnly.resolve(Some(false)).is_err());
    }

    /// HF's `tojson` is Python's `json.dumps`: spaced separators, insertion order.
    #[test]
    fn tojson_writes_what_python_writes() {
        let t = EmbeddedChatTemplate::new(
            "{{ {'name': 'f', 'b': [1, 2.0, true, none], 'é': 'x\"y'} | tojson }}|\
             {{ [1] | tojson(indent=2) }}",
        )
        .expect("loads");
        assert_eq!(
            t.render(&[], false, None).expect("renders"),
            "{\"name\": \"f\", \"b\": [1, 2.0, true, null], \"é\": \"x\\\"y\"}|[\n  1\n]"
        );
    }
}
