//! Rejection sampling filter for teacher completions.
//!
//! Filters raw teacher-generated code completions by quality criteria:
//! - AST validity (Python syntax check)
//! - Minimum length
//! - Repetition detection (n-gram overlap)
//! - Non-trivial content (not only comments/whitespace)
//!
//! Contract: `contracts/aprender/sft-distillation-pipeline-v1.yaml`
//! Equation: `rejection_sampling`
//! Gate: F-SFT-DISTILL-001

use std::collections::HashSet;

/// A single teacher completion to be filtered.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TeacherCompletion {
    /// The prompt that was given to the teacher.
    pub prompt: String,
    /// The completion generated by the teacher.
    pub completion: String,
    /// Optional metadata (source model, temperature, etc.)
    #[cfg_attr(feature = "serde", serde(default))]
    pub source: Option<String>,
}

/// Reason a completion was rejected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RejectionReason {
    /// Completion is too short (< min_length chars).
    TooShort,
    /// Completion has high n-gram repetition ratio.
    Degenerate,
    /// Completion contains only comments or whitespace (no actual code).
    NoCode,
    /// Completion fails Python AST parse (syntax error).
    SyntaxError,
}

/// Configuration for the rejection sampling filter.
#[derive(Debug, Clone)]
pub struct RejectionConfig {
    /// Minimum completion length in characters.
    pub min_length: usize,
    /// N-gram size for repetition detection.
    pub ngram_size: usize,
    /// Maximum allowed repetition ratio (0.0 to 1.0).
    pub max_repetition_ratio: f64,
    /// Minimum yield rate (fraction of completions that must pass).
    /// If yield drops below this, the filter is too aggressive.
    pub min_yield_rate: f64,
}

impl Default for RejectionConfig {
    fn default() -> Self {
        Self {
            min_length: 20,
            ngram_size: 5,
            max_repetition_ratio: 0.3,
            min_yield_rate: 0.20,
        }
    }
}

/// Result of filtering a batch of completions.
#[derive(Debug)]
pub struct FilterResult {
    /// Completions that passed all filters.
    pub accepted: Vec<TeacherCompletion>,
    /// Count of rejections by reason.
    pub rejections: RejectionCounts,
    /// Total completions processed.
    pub total: usize,
    /// Yield rate (accepted / total).
    pub yield_rate: f64,
}

/// Counts of rejections by reason.
#[derive(Debug, Default)]
pub struct RejectionCounts {
    pub too_short: usize,
    pub degenerate: usize,
    pub no_code: usize,
    pub syntax_error: usize,
}

impl RejectionCounts {
    fn total(&self) -> usize {
        self.too_short + self.degenerate + self.no_code + self.syntax_error
    }
}

/// Filter a batch of teacher completions using rejection sampling.
///
/// Contract: FALSIFY-SFT-002 requires yield_rate >= config.min_yield_rate.
pub fn filter_completions(
    completions: &[TeacherCompletion],
    config: &RejectionConfig,
) -> FilterResult {
    let total = completions.len();
    let mut accepted = Vec::with_capacity(total / 2);
    let mut rejections = RejectionCounts::default();

    for completion in completions {
        match check_completion(&completion.completion, config) {
            Ok(()) => accepted.push(completion.clone()),
            Err(RejectionReason::TooShort) => rejections.too_short += 1,
            Err(RejectionReason::Degenerate) => rejections.degenerate += 1,
            Err(RejectionReason::NoCode) => rejections.no_code += 1,
            Err(RejectionReason::SyntaxError) => rejections.syntax_error += 1,
        }
    }

    let yield_rate = if total > 0 {
        accepted.len() as f64 / total as f64
    } else {
        0.0
    };

    FilterResult {
        accepted,
        rejections,
        total,
        yield_rate,
    }
}

/// Check a single completion against all quality criteria.
fn check_completion(code: &str, config: &RejectionConfig) -> Result<(), RejectionReason> {
    // 1. Length check
    if code.len() < config.min_length {
        return Err(RejectionReason::TooShort);
    }

    // 2. Non-trivial content check (not only comments/whitespace)
    if is_only_comments_or_whitespace(code) {
        return Err(RejectionReason::NoCode);
    }

    // 3. Repetition check (n-gram overlap ratio)
    if ngram_repetition_ratio(code, config.ngram_size) > config.max_repetition_ratio {
        return Err(RejectionReason::Degenerate);
    }

    // 4. Python AST validity check
    if !is_valid_python_syntax(code) {
        return Err(RejectionReason::SyntaxError);
    }

    Ok(())
}

/// Check if text contains only Python comments and whitespace.
fn is_only_comments_or_whitespace(code: &str) -> bool {
    for line in code.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        // Line has actual code content
        return false;
    }
    true
}

/// Compute n-gram repetition ratio.
///
/// Returns the fraction of n-grams that are duplicates.
/// A ratio > 0.3 indicates degenerate repetitive output.
fn ngram_repetition_ratio(text: &str, n: usize) -> f64 {
    let words: Vec<&str> = text.split_whitespace().collect();
    if words.len() < n {
        return 0.0;
    }

    let total_ngrams = words.len() - n + 1;
    let mut seen = HashSet::new();
    let mut duplicates = 0usize;

    for window in words.windows(n) {
        let ngram: Vec<&str> = window.to_vec();
        if !seen.insert(ngram) {
            duplicates += 1;
        }
    }

    duplicates as f64 / total_ngrams as f64
}

/// Check if code is valid Python syntax.
///
/// Uses a lightweight heuristic: checks for balanced brackets, valid
/// indentation structure, and presence of Python keywords. For production,
/// this should call `python3 -c "import ast; ast.parse(...)"` but we avoid
/// the Python dependency for the Rust-only pipeline.
fn is_valid_python_syntax(code: &str) -> bool {
    // Quick structural checks that catch most garbage output

    // 1. Balanced brackets/parens
    let mut paren_depth: i32 = 0;
    let mut bracket_depth: i32 = 0;
    let mut brace_depth: i32 = 0;

    for ch in code.chars() {
        match ch {
            '(' => paren_depth += 1,
            ')' => paren_depth -= 1,
            '[' => bracket_depth += 1,
            ']' => bracket_depth -= 1,
            '{' => brace_depth += 1,
            '}' => brace_depth -= 1,
            _ => {}
        }
        // Negative depth means unbalanced closing bracket
        if paren_depth < 0 || bracket_depth < 0 || brace_depth < 0 {
            return false;
        }
    }

    if paren_depth != 0 || bracket_depth != 0 || brace_depth != 0 {
        return false;
    }

    // 2. Must contain at least one Python keyword
    const PYTHON_KEYWORDS: &[&str] = &[
        "def", "return", "if", "else", "elif", "for", "while", "class", "import", "from", "try",
        "except", "with", "as", "yield", "lambda", "pass", "break", "continue", "raise", "in",
        "not", "and", "or", "is", "None", "True", "False", "print", "len", "range", "self",
    ];

    let has_keyword = PYTHON_KEYWORDS
        .iter()
        .any(|kw| code.split_whitespace().any(|word| word.trim_matches(|c: char| !c.is_alphanumeric()) == *kw));

    has_keyword
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_completion(prompt: &str, completion: &str) -> TeacherCompletion {
        TeacherCompletion {
            prompt: prompt.to_string(),
            completion: completion.to_string(),
            source: None,
        }
    }

    // FALSIFY-SFT-001: Teacher completions are syntactically valid Python
    #[test]
    fn falsify_sft_001_valid_python_accepted() {
        let good_code = "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)";
        assert!(is_valid_python_syntax(good_code));
    }

    #[test]
    fn falsify_sft_001_garbage_rejected() {
        let garbage = "UVincremental PRNGnumexprmplifyelect buffers besselk";
        // Garbage has no Python keywords
        assert!(!is_valid_python_syntax(garbage));
    }

    #[test]
    fn falsify_sft_001_unbalanced_brackets_rejected() {
        let bad_code = "def foo(x:\n    return x + 1";
        assert!(!is_valid_python_syntax(bad_code));
    }

    // FALSIFY-SFT-002: Rejection sampling yield >= 20%
    #[test]
    fn falsify_sft_002_yield_above_threshold() {
        let completions: Vec<TeacherCompletion> = (0..100)
            .map(|i| {
                if i < 30 {
                    // 30% are good
                    make_completion(
                        "def foo():",
                        "def foo():\n    return 42\n",
                    )
                } else if i < 60 {
                    // 30% are garbage
                    make_completion(
                        "def foo():",
                        "asdf jkl qwerty",
                    )
                } else {
                    // 40% are too short
                    make_completion("def foo():", "x")
                }
            })
            .collect();

        let config = RejectionConfig::default();
        let result = filter_completions(&completions, &config);

        assert!(
            result.yield_rate >= config.min_yield_rate,
            "yield_rate {} < min {}",
            result.yield_rate,
            config.min_yield_rate
        );
        assert_eq!(result.total, 100);
        assert_eq!(result.rejections.total() + result.accepted.len(), 100);
    }

    // Repetition detection
    #[test]
    fn test_ngram_repetition_detects_degenerate() {
        let degenerate = "foo bar baz foo bar baz foo bar baz foo bar baz";
        let ratio = ngram_repetition_ratio(degenerate, 5);
        assert!(ratio > 0.3, "ratio was {ratio}");
    }

    #[test]
    fn test_ngram_repetition_accepts_normal_code() {
        let normal = "def fibonacci(n):\n    if n <= 1:\n        return n\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a";
        let ratio = ngram_repetition_ratio(normal, 5);
        assert!(ratio <= 0.3, "ratio was {ratio}");
    }

    // Comments-only detection
    #[test]
    fn test_only_comments_rejected() {
        let comments = "# This is a comment\n# Another comment\n\n# More comments";
        assert!(is_only_comments_or_whitespace(comments));
    }

    #[test]
    fn test_code_with_comments_accepted() {
        let code = "# Compute sum\ndef add(a, b):\n    return a + b";
        assert!(!is_only_comments_or_whitespace(code));
    }

    // KANI-SFT-001: Rejection sampling bounds
    #[test]
    fn kani_sft_001_filter_bounds() {
        let completions = vec![
            make_completion("p1", "def foo():\n    return 42\n"),
            make_completion("p2", "x"),
            make_completion("p3", "def bar():\n    pass\n"),
        ];

        let config = RejectionConfig::default();
        let result = filter_completions(&completions, &config);

        // Invariant: accepted + rejected == total
        assert_eq!(result.accepted.len() + result.rejections.total(), result.total);
        // Invariant: yield_rate in [0.0, 1.0]
        assert!((0.0..=1.0).contains(&result.yield_rate));
    }

    // Empty input
    #[test]
    fn test_empty_input() {
        let result = filter_completions(&[], &RejectionConfig::default());
        assert_eq!(result.total, 0);
        assert_eq!(result.accepted.len(), 0);
        assert_eq!(result.yield_rate, 0.0);
    }
}
