impl Executor {
    /// Resolve the model path for a specific format.
    ///
    /// Supports multiple modes:
    /// - **File mode**: `model_path` points to a single file (e.g. `<hash>.safetensors`).
    ///   Returns `Some` if the file extension matches the scenario format, `None` otherwise.
    /// - **APR cache**: `{base}/{format}/model.{ext}` layout.
    /// - **HuggingFace cache**: `{base}/model.{ext}` (flat structure in snapshot directory).
    fn resolve_model_path(&self, scenario: &QaScenario) -> Option<String> {
        let model_path = self.config.model_path.as_deref().unwrap_or(".");
        let path = Path::new(model_path);

        if model_path.ends_with(".safetensors.index.json") {
            return Self::resolve_sharded_index(path, model_path, scenario);
        }

        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if ext == "gguf" || ext == "safetensors" || ext == "apr" {
            return Self::resolve_file_model(path, model_path, ext, scenario);
        }

        Self::resolve_directory_model(path, scenario)
    }

    /// Resolve model path for sharded SafeTensors index files
    fn resolve_sharded_index(
        path: &Path,
        model_path: &str,
        scenario: &QaScenario,
    ) -> Option<String> {
        if scenario.format == Format::SafeTensors {
            return Some(model_path.to_string());
        }
        let parent = path.parent()?;
        let target_ext = match scenario.format {
            Format::Gguf => "gguf",
            Format::SafeTensors => unreachable!(),
            Format::Apr => "apr",
        };
        Self::find_clean_model_file(parent, target_ext)
    }

    /// Resolve model path when path has a model file extension
    fn resolve_file_model(
        path: &Path,
        model_path: &str,
        ext: &str,
        scenario: &QaScenario,
    ) -> Option<String> {
        let matches = match scenario.format {
            Format::Gguf => ext == "gguf",
            Format::SafeTensors => ext == "safetensors",
            Format::Apr => ext == "apr",
        };
        if matches {
            return Some(model_path.to_string());
        }

        // Fix 202: Try sibling file with target extension
        let target_ext = match scenario.format {
            Format::Gguf => "gguf",
            Format::SafeTensors => "safetensors",
            Format::Apr => "apr",
        };
        let parent = path.parent()?;
        let stem = path.file_stem().and_then(|s| s.to_str())?;

        let sibling = parent.join(format!("{stem}.{target_ext}"));
        if sibling.exists() {
            return Some(sibling.to_string_lossy().to_string());
        }

        let prefix = Self::extract_model_family_prefix(stem);
        Self::find_model_by_prefix(parent, &prefix, target_ext)
    }

    /// Resolve model path when path is a directory
    fn resolve_directory_model(path: &Path, scenario: &QaScenario) -> Option<String> {
        let (subdir, extension) = match scenario.format {
            Format::Gguf => ("gguf", "gguf"),
            Format::Apr => ("apr", "apr"),
            Format::SafeTensors => ("safetensors", "safetensors"),
        };

        // Try APR cache structure: {base}/{format}/model.{ext}
        let resolved = path.join(subdir).join(format!("model.{extension}"));
        if resolved.exists() {
            return Some(resolved.to_string_lossy().to_string());
        }

        // Try sharded SafeTensors: {base}/{format}/model.safetensors.index.json
        if extension == "safetensors" {
            let sharded_index = path.join(subdir).join("model.safetensors.index.json");
            if sharded_index.exists() {
                return Some(sharded_index.to_string_lossy().to_string());
            }
        }

        // Try HuggingFace cache structure: {base}/model.{ext} (flat)
        let flat_resolved = path.join(format!("model.{extension}"));
        if flat_resolved.exists() {
            return Some(flat_resolved.to_string_lossy().to_string());
        }

        // Fall back to finding clean model file in format subdir
        let format_dir = path.join(subdir);
        if let Some(found) = Self::find_clean_model_file(&format_dir, extension) {
            return Some(found);
        }

        // Fall back to finding clean model file in base dir (HF cache)
        Self::find_clean_model_file(path, extension)
    }

    /// Find a clean model file in a directory, filtering out test artifacts.
    ///
    /// Test artifacts are identified by patterns like "converted", "idem", "com_"
    /// which are generated by conversion tests and should not be used for inference.
    fn find_clean_model_file(dir: &Path, extension: &str) -> Option<String> {
        let entries = std::fs::read_dir(dir).ok()?;

        for entry in entries.flatten() {
            let ep = entry.path();

            // Must have the right extension
            if ep.extension().is_none_or(|e| e != extension) {
                continue;
            }

            // Get filename for artifact detection
            let filename = ep.file_name()?.to_str()?;

            // Skip test artifacts (conversion test outputs)
            if Self::is_conversion_artifact(filename) {
                continue;
            }

            return Some(ep.to_string_lossy().to_string());
        }

        None
    }

    /// Extract model family prefix from a filename stem.
    ///
    /// Strips quantization suffixes (q4k, q4_k_m, q6_k, etc.) and trailing
    /// hyphens to get the base model family. Examples:
    /// - "qwen2.5-coder-7b-instruct-q4k" → "qwen2.5-coder-7b"
    /// - "qwen2.5-coder-1.5b" → "qwen2.5-coder-1.5b"
    /// - "TinyLlama-1.1B-Chat-v1.0-Q4_K_M" → "TinyLlama-1.1B-Chat-v1.0"
    fn extract_model_family_prefix(stem: &str) -> String {
        let lower = stem.to_lowercase();
        // Strip known quantization suffixes
        let suffixes = [
            "-q4k", "-q4_k_m", "-q4_k_s", "-q6_k", "-q8_0", "-q5_k_m", "-q2_k", "-q3_k_m",
            "-q3_k_s", "-f16", "-f32",
        ];
        let mut result = stem.to_string();
        for suffix in &suffixes {
            if lower.ends_with(suffix) {
                result.truncate(result.len() - suffix.len());
                break;
            }
        }
        // Strip "instruct" suffix to match both instruct and base variants
        let lower_result = result.to_lowercase();
        if lower_result.ends_with("-instruct") {
            result.truncate(result.len() - "-instruct".len());
        }
        result
    }

    /// Find a model file in a directory matching a model family prefix.
    ///
    /// Only returns files whose stem starts with the given prefix and
    /// has the requested extension, filtering out test artifacts.
    fn find_model_by_prefix(dir: &Path, prefix: &str, extension: &str) -> Option<String> {
        let entries = std::fs::read_dir(dir).ok()?;
        let lower_prefix = prefix.to_lowercase();

        for entry in entries.flatten() {
            let ep = entry.path();

            if ep.extension().is_none_or(|e| e != extension) {
                continue;
            }

            let filename = ep.file_name()?.to_str()?;

            // Skip test artifacts
            if Self::is_conversion_artifact(filename) {
                continue;
            }

            // Check prefix match (case-insensitive)
            let stem = ep.file_stem()?.to_str()?;
            if stem.to_lowercase().starts_with(&lower_prefix) {
                return Some(ep.to_string_lossy().to_string());
            }
        }

        None
    }

    /// Strip ANSI escape codes from a string.
    fn strip_ansi(s: &str) -> String {
        let mut result = String::with_capacity(s.len());
        let mut chars = s.chars();
        while let Some(c) = chars.next() {
            if c == '\x1b' {
                // Skip until end of escape sequence ([...m)
                if chars.next() == Some('[') {
                    for esc_c in chars.by_ref() {
                        if esc_c.is_ascii_alphabetic() {
                            break;
                        }
                    }
                }
            } else {
                result.push(c);
            }
        }
        result
    }

    /// Parse tokens per second from apr output
    fn parse_tps_from_output(output: &str) -> Option<f64> {
        // Try to find "tok/s: X.X" pattern
        output.find("tok/s:").and_then(|pos| {
            let rest = &output[pos + 6..];
            let tps_str: String = rest
                .chars()
                .skip_while(|c| c.is_whitespace())
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            tps_str.parse().ok()
        })
    }

    /// Truncate output for diagnostic messages (first 200 chars, UTF-8 safe).
    fn truncate_output(s: &str) -> String {
        if s.len() <= 200 {
            s.to_string()
        } else {
            let mut end = 200;
            while end > 0 && !s.is_char_boundary(end) {
                end -= 1;
            }
            format!("{}...", &s[..end])
        }
    }

    /// Extract generated text from apr output
    fn extract_generated_text(output: &str) -> String {
        // apr run with --json outputs JSON, otherwise plain text
        // For now, return the whole output (apr outputs generated text first)
        output
            .lines()
            .filter(|line| !line.starts_with("===") && !line.contains("tok/s"))
            .collect::<Vec<_>>()
            .join("\n")
            .trim()
            .to_string()
    }

    /// Create a scenario for G0-FORMAT evidence
    fn format_scenario(model_id: &ModelId, format: Format) -> QaScenario {
        QaScenario::new(
            model_id.clone(),
            Modality::Run,
            Backend::Cpu,
            format,
            format!("G0 Format: prepare {format:?} workspace"),
            0,
        )
    }

    /// Find sibling files that share the same hash prefix in a pacha cache directory.
    ///
    /// Given `/cache/abc123.safetensors`, scans the parent dir for files like
    /// `abc123.config.json`, `abc123.tokenizer.json`, etc. Returns pairs of
    /// `(source_path, canonical_name)` — e.g., `("abc123.config.json", "config.json")`.
    fn find_sibling_model_files(model_file: &Path) -> Vec<(PathBuf, String)> {
        let Some(parent) = model_file.parent() else {
            return Vec::new();
        };
        let Some(stem) = model_file.file_name().and_then(|n| n.to_str()) else {
            return Vec::new();
        };
        let Some(hash_prefix) = stem.strip_suffix(".safetensors") else {
            return Vec::new();
        };

        let Ok(entries) = std::fs::read_dir(parent) else {
            return Vec::new();
        };

        // Known config files to look for in flat HF directories
        let known_configs: &[&str] = &[
            "config.json",
            "tokenizer.json",
            "tokenizer_config.json",
            "generation_config.json",
            "special_tokens_map.json",
            "vocab.json",
            "merges.txt",
        ];

        let prefix_dot = format!("{hash_prefix}.");
        let is_flat = hash_prefix == "model"; // flat HF dir: model.safetensors

        entries
            .flatten()
            .filter_map(|entry| {
                let path = entry.path();
                let name = path.file_name()?.to_str()?.to_string();
                // Skip the safetensors file itself
                if name == stem {
                    return None;
                }
                // Try hash-prefix matching (pacha cache: hash.config.json)
                if let Some(canonical) = name.strip_prefix(&prefix_dot) {
                    return Some((path, canonical.to_string()));
                }
                // For flat directories, match known config files directly
                if is_flat && known_configs.contains(&name.as_str()) {
                    return Some((path, name));
                }
                None
            })
            .collect()
    }

    /// Prepare a workspace directory with the APR cache structure.
    ///
    /// When G0-PULL resolves `model_path` to a single `.safetensors` file,
    /// downstream code expects a directory with `safetensors/`, `apr/`, `gguf/`
    /// subdirectories. This method creates that structure using symlinks for the
    /// source file and config files, then converts to each requested format.
    ///
    /// # Returns
    ///
    /// `(workspace_path, passed_count, failed_count)` — evidence is added to collector
    #[allow(clippy::too_many_lines)]
    fn prepare_model_workspace(
        &mut self,
        source_file: &Path,
        model_id: &ModelId,
        requested_formats: &[Format],
    ) -> (String, usize, usize) {
        let output_dir = self.config.output_dir.as_deref().unwrap_or("output");
        let workspace = PathBuf::from(output_dir)
            .join("workspace")
            .join(&model_id.org)
            .join(&model_id.name);

        Self::clean_stale_artifacts(&workspace);

        let st_dir = workspace.join("safetensors");
        if let Err(e) = std::fs::create_dir_all(&st_dir) {
            let ev = Evidence::falsified(
                "G0-FORMAT-WORKSPACE-001",
                Self::format_scenario(model_id, Format::SafeTensors),
                format!("Failed to create workspace directory: {e}"),
                "N/A",
                0,
            );
            self.collector.add(ev);
            return (workspace.to_string_lossy().to_string(), 0, 1);
        }

        let is_sharded = source_file
            .file_name()
            .is_some_and(|n| n.to_string_lossy().ends_with(".safetensors.index.json"));

        if let Some(err) = Self::setup_source_links(source_file, &st_dir, is_sharded) {
            let ev = Evidence::falsified(
                "G0-FORMAT-WORKSPACE-001",
                Self::format_scenario(model_id, Format::SafeTensors),
                err,
                "N/A",
                0,
            );
            self.collector.add(ev);
            return (workspace.to_string_lossy().to_string(), 0, 1);
        }

        let (passed, failed) = self.convert_requested_formats(
            &workspace,
            &st_dir,
            source_file,
            model_id,
            requested_formats,
            is_sharded,
        );

        (workspace.to_string_lossy().to_string(), passed, failed)
    }

    /// Clean stale conversion artifacts from previous runs
    fn clean_stale_artifacts(workspace: &Path) {
        if !workspace.exists() {
            return;
        }
        for subdir in &["safetensors", "apr", "gguf"] {
            let dir = workspace.join(subdir);
            let Ok(entries) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let name = entry.file_name();
                let name_str = name.to_string_lossy();
                if Self::is_conversion_artifact(&name_str) {
                    let _ = std::fs::remove_file(entry.path());
                }
            }
        }
    }

    /// Check if a filename is a conversion test artifact.
    ///
    /// Patterns: converted, byte_rt, rt_ (roundtrip), idem (idempotency), com_ (composition)
    fn is_conversion_artifact(name: &str) -> bool {
        name.contains("converted")
            || name.contains("byte_rt")
            || name.contains(".rt_")
            || name.contains("idem")
            || name.contains("com_")
    }

    /// Set up source file symlinks in the workspace. Returns Some(error) on failure.
    fn setup_source_links(source_file: &Path, st_dir: &Path, is_sharded: bool) -> Option<String> {
        if is_sharded {
            Self::setup_sharded_links(source_file, st_dir)
        } else {
            Self::setup_single_file_link(source_file, st_dir)
        }
    }

    /// Symlink all files from a sharded model directory
    fn setup_sharded_links(source_file: &Path, st_dir: &Path) -> Option<String> {
        let source_dir = source_file.parent()?;
        let Ok(entries) = std::fs::read_dir(source_dir) else {
            return None;
        };
        for entry in entries.flatten() {
            let src_path = entry.path();
            let Some(filename) = src_path.file_name() else {
                continue;
            };
            if Self::is_conversion_artifact(&filename.to_string_lossy()) {
                continue;
            }
            let link_path = st_dir.join(filename);
            let _ = std::fs::remove_file(&link_path);
            #[cfg(unix)]
            let link_res = std::os::unix::fs::symlink(&src_path, &link_path);
            #[cfg(not(unix))]
            let link_res = std::fs::copy(&src_path, &link_path).map(|_| ());

            if let Err(e) = link_res {
                let fname = filename.to_string_lossy();
                eprintln!("[WARN] Failed to link shard {fname}: {e}");
            }
        }
        None
    }
}

include!("executor_resolution_b.rs");
