/// Error type for oracle operations
#[derive(Debug)]
pub enum OracleError {
    /// Failed to execute batuta
    ExecutionFailed(String),
    /// Oracle query returned error
    QueryFailed(String),
    /// Timeout waiting for oracle
    Timeout,
}

impl std::fmt::Display for OracleError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ExecutionFailed(e) => write!(f, "Failed to execute batuta: {e}"),
            Self::QueryFailed(e) => write!(f, "Oracle query failed: {e}"),
            Self::Timeout => write!(f, "Oracle query timed out"),
        }
    }
}

impl std::error::Error for OracleError {}

/// Write the hypotheses section of the checklist markdown
fn write_hypotheses_section(md: &mut String, hypotheses: &[RankedHypothesis]) {
    use std::fmt::Write;

    if hypotheses.is_empty() {
        return;
    }
    md.push_str("## Root Cause Hypotheses\n\n");
    for h in hypotheses {
        let _ = writeln!(md, "### {}: {} ({})\n", h.id, h.description, h.confidence);
        write_evidence_list(md, "**Evidence For:**\n", &h.evidence_for);
        write_evidence_list(md, "**Evidence Against:**\n", &h.evidence_against);
    }
}

/// Write an evidence list (for or against) if non-empty
fn write_evidence_list(md: &mut String, header: &str, items: &[String]) {
    use std::fmt::Write;

    if items.is_empty() {
        return;
    }
    md.push_str(header);
    for e in items {
        let _ = writeln!(md, "- {e}");
    }
    md.push('\n');
}

/// Write the investigation commands section
fn write_commands_section(md: &mut String, commands: &[String]) {
    use std::fmt::Write;

    if commands.is_empty() {
        return;
    }
    md.push_str("## Investigation Commands\n\n");
    md.push_str("```bash\n");
    for cmd in commands {
        let _ = writeln!(md, "{cmd}");
    }
    md.push_str("```\n\n");
}

/// Write the cross-references section
fn write_cross_references_section(md: &mut String, refs: &[CrossReference]) {
    use std::fmt::Write;

    if refs.is_empty() {
        return;
    }
    md.push_str("## Cross-References\n\n");
    for r in refs {
        let _ = writeln!(
            md,
            "- `{}` § {} (relevance: {:.2})",
            r.source, r.section, r.relevance
        );
    }
    md.push('\n');
}

/// Generate a checklist markdown file from oracle context
#[must_use]
pub fn generate_checklist_markdown(
    model_id: &str,
    mqs_score: u32,
    grade: &str,
    total_scenarios: usize,
    failed_scenarios: usize,
    context: &OracleContext,
) -> String {
    use std::fmt::Write;

    let mut md = String::new();

    let _ = writeln!(md, "# Falsification Checklist: {model_id}\n");
    let _ = writeln!(md, "**Generated:** {}", chrono::Utc::now().to_rfc3339());
    let _ = writeln!(md, "**MQS Score:** {mqs_score}/1000 (Grade {grade})");
    let _ = writeln!(
        md,
        "**Failures:** {failed_scenarios}/{total_scenarios} scenarios\n"
    );
    md.push_str("---\n\n");

    // Checklist items
    md.push_str("## Checklist Items\n\n");
    for item in &context.checklist {
        let _ = writeln!(md, "- [ ] **{}**: {}", item.gate_id, item.hypothesis);
        let _ = writeln!(md, "  - *Test:* {}", item.test_procedure);
        let _ = writeln!(md, "  - *Falsified if:* {}", item.falsified_if);
        let _ = writeln!(md, "  - *Status:* {}", item.status);
        let _ = writeln!(md, "  - *Confidence:* {}\n", item.confidence);
    }

    write_hypotheses_section(&mut md, &context.hypotheses);
    write_commands_section(&mut md, &context.investigation_commands);
    write_cross_references_section(&mut md, &context.cross_references);

    md.push_str("---\n\n");
    md.push_str("*Generated by apr-qa with --oracle-enhance*\n");

    md
}


#[cfg(test)]
#[path = "oracle_tests.rs"]
mod oracle_tests;
