import ProvableContracts.Theorems.AdamW.Adam_Moments
import ProvableContracts.Theorems.AdamW.Adam_Variance
import ProvableContracts.Theorems.AdamW.Bias_Correction
import ProvableContracts.Theorems.AdamW.Weight_Update

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `adamw-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.AdamW.BiasCorrection
theorem _root_.PvlChallenge.ProvableContracts.AdamW.BiasCorrection.bias_correction (beta : ℝ) (t : ℕ) (hpos : 0 < beta) (hlt : beta < 1) (ht : 1 ≤ t) : 1 < 1 / (1 - beta ^ t) := sorry
end ProvableContracts.AdamW.BiasCorrection
end

section
namespace ProvableContracts.AdamW.Moments
theorem _root_.PvlChallenge.ProvableContracts.AdamW.Moments.adam_moment_bounded (beta1 m_prev g B : ℝ) (h0 : 0 ≤ beta1) (h1 : beta1 ≤ 1) (hm : |m_prev| ≤ B) (hg : |g| ≤ B) : |adam_moment beta1 m_prev g| ≤ B := sorry
end ProvableContracts.AdamW.Moments
end

section
namespace ProvableContracts.AdamW.Moments
theorem _root_.PvlChallenge.ProvableContracts.AdamW.Moments.adam_moments (beta1 m_prev g : ℝ) : adam_moment beta1 m_prev g = beta1 * m_prev + (1 - beta1) * g := sorry
end ProvableContracts.AdamW.Moments
end

section
namespace ProvableContracts.AdamW.Variance
theorem _root_.PvlChallenge.ProvableContracts.AdamW.Variance.adam_variance (beta2 v_prev g : ℝ) (hv : 0 ≤ v_prev) (h0 : 0 ≤ beta2) (h1 : beta2 ≤ 1) : 0 ≤ adam_variance_update beta2 v_prev g := sorry
end ProvableContracts.AdamW.Variance
end

section
namespace ProvableContracts.AdamW.WeightUpdate
theorem _root_.PvlChallenge.ProvableContracts.AdamW.WeightUpdate.weight_update (theta adam_step lr wd : ℝ) : adamw_update theta adam_step lr wd = (theta - lr * adam_step) - lr * wd * theta := sorry
end ProvableContracts.AdamW.WeightUpdate
end
