import ProvableContracts.Theorems.Alibi.Basic
import ProvableContracts.Theorems.Alibi.Slopes

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `alibi-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_bias_antitone {m : ℝ} (hm : 0 ≤ m) {i₁ j₁ i₂ j₂ : ℤ} (h : dist i₁ j₁ ≤ dist i₂ j₂) : alibiBias m i₂ j₂ ≤ alibiBias m i₁ j₁ := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_bias_linear (m : ℝ) (i j : ℤ) : alibiBias m i j = -m * (dist i j : ℝ) := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_bias_nonpos {m : ℝ} (hm : 0 ≤ m) (i j : ℤ) : alibiBias m i j ≤ 0 := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_bias_self (m : ℝ) (i : ℤ) : alibiBias m i i = 0 := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_causal_keeps_past (m : ℝ) {i j : ℤ} (h : ¬ j > i) : causalBias m i j = ((alibiBias m i j : ℝ) : EReal) := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_causal_masks_future (m : ℝ) {i j : ℤ} (h : j > i) : causalBias m i j = ⊥ := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_head_zero (n : ℝ) : alibiSlope n 0 = alibiM0 n := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_head_zero_eight : alibiSlope 8 0 = 1 / 2 := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_antitone {H h₁ h₂ : ℕ} (hH : 0 < H) (h : h₁ < h₂) : slope H h₂ < slope H h₁ := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_ggml (n h : ℝ) : alibiSlope n h = (alibiM0 n) ^ (h + 1) := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_lt_one {n h : ℝ} (hn : 0 < n) (hh : 0 ≤ h) : alibiSlope n h < 1 := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_pos (H h : ℕ) : 0 < slope H h := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_real_pos (n h : ℝ) : 0 < alibiSlope n h := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.alibi_slope_strict_anti {n h₁ h₂ : ℝ} (hn : 0 < n) (h : h₁ < h₂) : alibiSlope n h₂ < alibiSlope n h₁ := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.dist_comm (i j : ℤ) : dist i j = dist j i := sorry
end ProvableContracts.Alibi
end

section
namespace ProvableContracts.Alibi
open Real
theorem _root_.PvlChallenge.ProvableContracts.Alibi.dist_nonneg (i j : ℤ) : 0 ≤ dist i j := sorry
end ProvableContracts.Alibi
end
