import ProvableContracts.Theorems.Attention.ScaledDotProduct
import ProvableContracts.Theorems.Attention.Scaling
import ProvableContracts.Theorems.RMSNorm.DenominatorPositive
import ProvableContracts.Theorems.RMSNorm.NormalizedRMS
import ProvableContracts.Theorems.RMSNorm.ScaleInvariance

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `attention-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.attention_output_bounded {m : ℕ} (scores : RVec (m + 1)) (V : RVec (m + 1)) (lo hi : ℝ) (hlo : ∀ j, lo ≤ V j) (hhi : ∀ j, V j ≤ hi) : lo ≤ ∑ j, softmax scores j * V j ∧ ∑ j, softmax scores j * V j ≤ hi := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.attention_weight_pos {m : ℕ} (scores : RVec (m + 1)) (j : Fin (m + 1)) : 0 < softmax scores j := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.attention_weights_bounded {m : ℕ} (scores : RVec (m + 2)) (j : Fin (m + 2)) : 0 < softmax scores j ∧ softmax scores j < 1 := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.attention_weights_sum_to_one {m : ℕ} (scores : RVec (m + 1)) : ∑ j : Fin (m + 1), softmax scores j = 1 := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.causal_mask_zeroes_future {n : ℕ} (w V : Fin n → ℝ) (S : Finset (Fin n)) (hmask : ∀ j ∈ (Finset.univ : Finset (Fin n)), j ∉ S → w j = 0) : ∑ j, w j * V j = ∑ j ∈ S, w j * V j := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.convex_comb_le {n : ℕ} (w V : Fin n → ℝ) (c : ℝ) (hw : ∀ j, 0 ≤ w j) (hsum : ∑ j, w j = 1) (hV : ∀ j, V j ≤ c) : ∑ j, w j * V j ≤ c := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.le_convex_comb {n : ℕ} (w V : Fin n → ℝ) (c : ℝ) (hw : ∀ j, 0 ≤ w j) (hsum : ∑ j, w j = 1) (hV : ∀ j, c ≤ V j) : c ≤ ∑ j, w j * V j := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.scale_factor_ne_linear {d : ℝ} (hd : 1 < d) : 1 / d < 1 / Real.sqrt d := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.scale_factor_pos {d : ℝ} (hd : 0 < d) : 0 < 1 / Real.sqrt d := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.Attention
open Real Finset
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.Attention.scale_factor_sq {d : ℝ} (hd : 0 < d) : (1 / Real.sqrt d) ^ 2 = 1 / d := sorry
end ProvableContracts.Attention
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.attention_entropy_le_log_card {n : ℕ} (scores : RVec (n + 1)) : entropy (fun j => softmax scores j) ≤ Real.log ((n : ℝ) + 1) := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.attention_entropy_nonneg {n : ℕ} (scores : RVec (n + 1)) : 0 ≤ entropy (fun j => softmax scores j) := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.dot_sq_le {d : ℕ} (q k : RVec d) : (dot q k) ^ 2 ≤ sqNorm q * sqNorm k := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.mean_smul {n : ℕ} (c : ℝ) (x : RVec n) : mean (fun i => c * x i) = c * mean x := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.scaledScores_apply {n m d : ℕ} (Q : Matrix (Fin n) (Fin d) ℝ) (K : Matrix (Fin m) (Fin d) ℝ) (scale : ℝ) (i : Fin n) (j : Fin m) : scaledScores Q K scale i j = scale * ∑ l : Fin d, Q i l * K j l := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.scaled_score_abs_le_sqrt {d : ℕ} (q k : RVec d) (D : ℝ) (hD : 1 ≤ D) (hq : sqNorm q ≤ 1) (hk : sqNorm k ≤ 1) : |dot q k / Real.sqrt D| ≤ Real.sqrt D := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.softmax_le_one {n : ℕ} (x : RVec (n + 1)) (i : Fin (n + 1)) : softmax x i ≤ 1 := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.softmax_max_subtraction_invariant {n : ℕ} (x : RVec (n + 1)) (M : ℝ) (i : Fin (n + 1)) : softmax (fun j => x j - M) i = softmax x i := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.variance_scaled_by_inv_sqrt_normalizes {n : ℕ} (s : RVec n) (d : ℝ) (hd : 0 < d) (hvar : variance s = d) : variance (fun i => (1 / Real.sqrt d) * s i) = 1 := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.variance_smul {n : ℕ} (c : ℝ) (x : RVec n) : variance (fun i => c * x i) = c ^ 2 * variance x := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.mean_sq_nonneg {n : ℕ} (x : RVec (n + 1)) : mean_sq x ≥ 0 := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.mean_sq_scale {n : ℕ} (x : RVec (n + 1)) (α : ℝ) : mean_sq (fun i => α * x i) = α ^ 2 * mean_sq x := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.normalized_mean_sq_one {n : ℕ} (x : RVec (n + 1)) (hx : mean_sq x > 0) : mean_sq (rmsnorm x (fun _ => 1) 0) = 1 := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.normalized_rms_one {n : ℕ} (x : RVec (n + 1)) (hx : mean_sq x > 0) : rms (rmsnorm x (fun _ => 1) 0) 0 = 1 := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.rms_pos {n : ℕ} (x : RVec (n + 1)) (eps : ℝ) (heps : eps > 0) : rms x eps > 0 := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.rms_scale_zero_eps {n : ℕ} (x : RVec (n + 1)) (α : ℝ) : rms (fun i => α * x i) 0 = |α| * rms x 0 := sorry
end ProvableContracts.RMSNorm
end

section
namespace ProvableContracts.RMSNorm
open Finset
theorem _root_.PvlChallenge.ProvableContracts.RMSNorm.rms_sq_zero_eps {n : ℕ} (x : RVec (n + 1)) : (rms x 0) ^ 2 = mean_sq x := sorry
end ProvableContracts.RMSNorm
end
