import ProvableContracts.Theorems.FP8.Interchange

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `bpe-tokenization-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.decode_abs_le (maxv : ℝ) (neg : Bool) (mag : ℝ) (h : 0 ≤ maxv) : |fp8Decode maxv neg mag| ≤ maxv := sorry
end ProvableContracts.FP8
end
