import ProvableContracts.Theorems.Conv1D.Bound
import ProvableContracts.Theorems.Conv1D.Linearity
import ProvableContracts.Theorems.Conv1D.OutputLength
import ProvableContracts.Theorems.Conv1D.ShiftEquivariance
import ProvableContracts.Theorems.Conv1D.ZeroInput

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `conv1d-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv1d_valid_length (w x : List ℝ) : (conv1d_valid w x).length = x.length - w.length + 1 := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv1d_valid_length_eq_outLen (w x : List ℝ) : (conv1d_valid w x).length = outLen x.length w.length 0 1 := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_abs_le (w : List ℝ) (x : Signal) (n : ℕ) (Wmax Xmax : ℝ) (hW : ∀ k, |w.getD k 0| ≤ Wmax) (hX : ∀ m, |x m| ≤ Xmax) : |conv w x n| ≤ w.length * Wmax * Xmax := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_add (w : List ℝ) (x z : Signal) (n : ℕ) : conv w (fun i => x i + z i) n = conv w x n + conv w z n := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_linear (w : List ℝ) (a b : ℝ) (x z : Signal) (n : ℕ) : conv w (lin a b x z) n = a * conv w x n + b * conv w z n := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_shift (w : List ℝ) (x : Signal) (s n : ℕ) : conv w (shift x s) n = conv w x (n + s) := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_shift_eq (w : List ℝ) (x : Signal) (s : ℕ) : conv w (shift x s) = shift (conv w x) s := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_smul (w : List ℝ) (a : ℝ) (x : Signal) (n : ℕ) : conv w (fun i => a * x i) n = a * conv w x n := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_zero (w : List ℝ) (n : ℕ) : conv w zeroSignal n = 0 := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.conv_zero_eq (w : List ℝ) : conv w zeroSignal = zeroSignal := sorry
end ProvableContracts.Conv1D
end

section
namespace ProvableContracts.Conv1D
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Conv1D.outLen_valid (L K : ℕ) : outLen L K 0 1 = L - K + 1 := sorry
end ProvableContracts.Conv1D
end
