import ProvableContracts.Theorems.Embedding.Algebra
import ProvableContracts.Theorems.Embedding.Bounds
import ProvableContracts.Theorems.Embedding.Determinism
import ProvableContracts.Theorems.Embedding.Finite
import ProvableContracts.Theorems.Embedding.Rows
import ProvableContracts.Theorems.Embedding.Shape

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `embedding-lookup-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.embed_dim {V d : ℕ} (_W : EmbTable V d) (_t : Fin V) : Fintype.card (Fin d) = d := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_deterministic {α : Type _} (t₁ t₂ : List α) (i₁ i₂ : List ℕ) (d₁ d₂ : α) (ht : t₁ = t₂) (hi : i₁ = i₂) (hd : d₁ = d₂) : gather t₁ i₁ d₁ = gather t₂ i₂ d₂ := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_finite {α : Type _} (isFinite : α → Prop) (table : List α) (ids : List ℕ) (dflt : α) (hdflt : isFinite dflt) (htab : ∀ x ∈ table, isFinite x) : ∀ y ∈ gather table ids dflt, isFinite y := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_hits_table {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) (hb : ∀ i ∈ ids, i < table.length) (j : ℕ) (hj : j < ids.length) : (gather table ids dflt)[j]? = some (table[ids[j]]'(hb _ (List.getElem_mem hj))) := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_inbounds {α : Type _} (table : List α) (ids : List ℕ) (hb : ∀ i ∈ ids, i < table.length) (j : ℕ) (hj : j < ids.length) : (table[ids[j]]?).isSome = true := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_length {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) : (gather table ids dflt).length = ids.length := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_length_seq {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) (seq_len : ℕ) (h : ids.length = seq_len) : (gather table ids dflt).length = seq_len := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_preserves {α : Type _} (P : α → Prop) (table : List α) (ids : List ℕ) (dflt : α) (hdflt : P dflt) (htab : ∀ x ∈ table, P x) : ∀ y ∈ gather table ids dflt, P y := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_row {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) (j : ℕ) (hj : j < ids.length) : (gather table ids dflt)[j]? = some (gatherAt table (ids[j]) dflt) := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_row? {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) (j : ℕ) : (gather table ids dflt)[j]? = (ids[j]?).map (fun i => table.getD i dflt) := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_scatter_id {α : Type _} (table : List α) (dflt : α) : gather table (List.range table.length) dflt = table := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_self_eq {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) : gather table ids dflt = gather table ids dflt := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.mean_pool_smul {m d : ℕ} (a : ℝ) (A : Fin m → RVec d) (j : Fin d) : mean_pool (fun i => fun c => a * A i c) j = a * mean_pool A j := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.onehot_select {V d : ℕ} (W : EmbTable V d) (t : Fin V) (j : Fin d) : (∑ k : Fin V, onehot t k * W k j) = embed W t j := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.sum_pool_add {m d : ℕ} (A B : Fin m → RVec d) (j : Fin d) : sum_pool (fun i => fun c => A i c + B i c) j = sum_pool A j + sum_pool B j := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.sum_pool_smul {m d : ℕ} (a : ℝ) (A : Fin m → RVec d) (j : Fin d) : sum_pool (fun i => fun c => a * A i c) j = a * sum_pool A j := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.temp_identity {n : ℕ} (z : RVec n) : temp_scale 1 z = z := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.tied_apply {V d : ℕ} (We Wu : EmbTable V d) (hty : Wu = We) (i : Fin V) (j : Fin d) : Wu i j = We i j := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.tied_row_eq {V d : ℕ} (We Wu : EmbTable V d) (hty : Wu = We) (t : Fin V) : embed Wu t = embed We t := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.token_lt_vocab {V : ℕ} (t : Fin V) : (t : ℕ) < V := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.token_nonneg {V : ℕ} (t : Fin V) : 0 ≤ (t : ℕ) := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.unembed_apply {seq d V : ℕ} (h : Matrix (Fin seq) (Fin d) ℝ) (Wu : EmbTable V d) (s : Fin seq) (v : Fin V) : (h * Wuᵀ) s v = ∑ k : Fin d, h s k * Wu v k := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
open Matrix Finset
theorem _root_.PvlChallenge.ProvableContracts.Embedding.unembed_shape (seq _d V : ℕ) : Fintype.card (Fin seq) = seq ∧ Fintype.card (Fin V) = V := sorry
end ProvableContracts.Embedding
end
