import ProvableContracts.Theorems.FP8.Interchange
import ProvableContracts.Theorems.Quantization.RoundtripBound

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `encoder-roundtrip-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e4m3 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e5m2 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_ulp (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.Quantization.roundtrip_bound (x : ℝ) (scale : ℝ) (hs : scale > 0) : |dequantize (quantize x scale) scale - x| ≤ scale / 2 := sorry
end ProvableContracts.Quantization
end
