import ProvableContracts.Theorems.FP8.Interchange

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `fp8-interchange-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.clampMag_le (maxv x : ℝ) (h : 0 ≤ maxv) : clampMag maxv x ≤ maxv := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.clampMag_nonneg (maxv x : ℝ) : 0 ≤ clampMag maxv x := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.decode_abs_le (maxv : ℝ) (neg : Bool) (mag : ℝ) (h : 0 ≤ maxv) : |fp8Decode maxv neg mag| ≤ maxv := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.gridRound_mono (ulp : ℝ) (h : ulp > 0) {x₁ x₂ : ℝ} (hle : x₁ ≤ x₂) : gridRound ulp x₁ ≤ gridRound ulp x₂ := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.range_e4m3 (neg : Bool) (mag : ℝ) : |fp8Decode E4M3_MAX neg mag| ≤ E4M3_MAX := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.range_e5m2 (neg : Bool) (mag : ℝ) : |fp8Decode E5M2_MAX neg mag| ≤ E5M2_MAX := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e4m3 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e5m2 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_ulp (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.sign_preservation_neg (ulp maxv x : ℝ) (hx : x < 0) (hmag : 0 < clampMag maxv (gridRound ulp |x|)) : fp8 ulp maxv x < 0 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.sign_preservation_pos (ulp maxv x : ℝ) (hx : 0 < x) (hmag : 0 < clampMag maxv (gridRound ulp |x|)) : 0 < fp8 ulp maxv x := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.zero_roundtrip (ulp : ℝ) : gridRound ulp 0 = 0 := sorry
end ProvableContracts.FP8
end
