import ProvableContracts.Theorems.AdamW.WeightDecay
import ProvableContracts.Theorems.GatedDeltaNet.Recurrence

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `gated-delta-net-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.AdamW
theorem _root_.PvlChallenge.ProvableContracts.AdamW.decay_update_eq (theta lr wd : ℝ) : decay_update theta lr wd = (1 - lr * wd) * theta := sorry
end ProvableContracts.AdamW
end

section
namespace ProvableContracts.GatedDeltaNet
open Real
open scoped BigOperators
theorem _root_.PvlChallenge.ProvableContracts.GatedDeltaNet.decay_lt_one (aLog dt dtBias : ℝ) : decay aLog dt dtBias < 1 := sorry
end ProvableContracts.GatedDeltaNet
end

section
namespace ProvableContracts.GatedDeltaNet
open Real
open scoped BigOperators
theorem _root_.PvlChallenge.ProvableContracts.GatedDeltaNet.decay_mem_unit_interval (aLog dt dtBias : ℝ) : 0 < decay aLog dt dtBias ∧ decay aLog dt dtBias < 1 := sorry
end ProvableContracts.GatedDeltaNet
end

section
namespace ProvableContracts.GatedDeltaNet
open Real
open scoped BigOperators
theorem _root_.PvlChallenge.ProvableContracts.GatedDeltaNet.decay_pos (aLog dt dtBias : ℝ) : 0 < decay aLog dt dtBias := sorry
end ProvableContracts.GatedDeltaNet
end

section
namespace ProvableContracts.GatedDeltaNet
open Real
open scoped BigOperators
theorem _root_.PvlChallenge.ProvableContracts.GatedDeltaNet.write_iterate_preserves_shape (kDim vDim : ℕ) : ∀ n : ℕ, (writeShape kDim vDim)^[n] ⟨kDim, vDim⟩ = ⟨kDim, vDim⟩ := sorry
end ProvableContracts.GatedDeltaNet
end

section
namespace ProvableContracts.GatedDeltaNet
open Real
open scoped BigOperators
theorem _root_.PvlChallenge.ProvableContracts.GatedDeltaNet.write_preserves_shape (kDim vDim : ℕ) : writeShape kDim vDim ⟨kDim, vDim⟩ = ⟨kDim, vDim⟩ := sorry
end ProvableContracts.GatedDeltaNet
end
