import ProvableContracts.Theorems.AdamW.WeightDecay

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `gated-delta-net-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.AdamW
theorem _root_.PvlChallenge.ProvableContracts.AdamW.decay_update_eq (theta lr wd : ℝ) : decay_update theta lr wd = (1 - lr * wd) * theta := sorry
end ProvableContracts.AdamW
end
