import ProvableContracts.Theorems.Gelu.GeluBounds
import ProvableContracts.Theorems.Gelu.GeluMono
import ProvableContracts.Theorems.Gelu.GeluSign
import ProvableContracts.Theorems.Gelu.GeluZero

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `gelu-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_le_self_of_nonneg (x : ℝ) (hx : 0 ≤ x) : gelu x ≤ x := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_nonneg_of_nonneg (x : ℝ) (hx : 0 ≤ x) : 0 ≤ gelu x := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_nonneg_of_pos {x : ℝ} (hx : 0 < x) : 0 ≤ gelu x := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_nonpos_of_neg {x : ℝ} (hx : x < 0) : gelu x ≤ 0 := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_right_factor_pos (x : ℝ) : 0 < 1 + Real.tanh (Real.sqrt (2 / Real.pi) * (x + 0.044715 * x ^ 3)) := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_strictMono_of_pos {x y : ℝ} (hy : 0 < y) (hyx : y < x) : gelu y < gelu x := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
theorem _root_.PvlChallenge.ProvableContracts.Gelu.gelu_zero : gelu 0 = 0 := sorry
end ProvableContracts.Gelu
end

section
namespace ProvableContracts.Gelu
open Real
theorem _root_.PvlChallenge.ProvableContracts.Gelu.tanh_strictMono : StrictMono Real.tanh := sorry
end ProvableContracts.Gelu
end
