import ProvableContracts.Theorems.Gqa.ConvexBound
import ProvableContracts.Theorems.Gqa.Distribution
import ProvableContracts.Theorems.Gqa.HeadMapping

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `gqa-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Gqa
open ProvableContracts Finset
theorem _root_.PvlChallenge.ProvableContracts.Gqa.attn_weights_pos {s : ℕ} (scores : RVec (s + 1)) (j : Fin (s + 1)) : 0 < Softmax.softmax scores j := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts Finset
theorem _root_.PvlChallenge.ProvableContracts.Gqa.attn_weights_sum_one {s : ℕ} (scores : RVec (s + 1)) : ∑ j : Fin (s + 1), Softmax.softmax scores j = 1 := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts Finset
theorem _root_.PvlChallenge.ProvableContracts.Gqa.convex_combination_bounds {s : ℕ} (w v : RVec s) (hw_nonneg : ∀ j, 0 ≤ w j) (hw_sum : ∑ j, w j = 1) (lo hi : ℝ) (hlo : ∀ j, lo ≤ v j) (hhi : ∀ j, v j ≤ hi) : lo ≤ ∑ j, w j * v j ∧ ∑ j, w j * v j ≤ hi := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts Finset
theorem _root_.PvlChallenge.ProvableContracts.Gqa.gqa_output_convex {s : ℕ} (scores v : RVec (s + 1)) (lo hi : ℝ) (hlo : ∀ j, lo ≤ v j) (hhi : ∀ j, v j ≤ hi) : lo ≤ ∑ j, Softmax.softmax scores j * v j ∧ ∑ j, Softmax.softmax scores j * v j ≤ hi := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts
theorem _root_.PvlChallenge.ProvableContracts.Gqa.kvHead_eq_mul_div (r kvHeads q : ℕ) (hk : 0 < kvHeads) : kvHead r q = q * kvHeads / (kvHeads * r) := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts
theorem _root_.PvlChallenge.ProvableContracts.Gqa.kvHead_group (r g i : ℕ) (hr : 0 < r) (hi : i < r) : kvHead r (g * r + i) = g := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts
theorem _root_.PvlChallenge.ProvableContracts.Gqa.kvHead_group_one (q : ℕ) : kvHead 1 q = q := sorry
end ProvableContracts.Gqa
end

section
namespace ProvableContracts.Gqa
open ProvableContracts
theorem _root_.PvlChallenge.ProvableContracts.Gqa.kvHead_surjective (r kvHeads h : ℕ) (hr : 0 < r) (hh : h < kvHeads) : ∃ q, q < kvHeads * r ∧ kvHead r q = h := sorry
end ProvableContracts.Gqa
end
