import ProvableContracts.Theorems.LoRA.Dare_Unbiased
import ProvableContracts.Theorems.LoRA.Lora_Shape
import ProvableContracts.Theorems.LoRA.Shape_Preservation
import ProvableContracts.Theorems.LoRA.Task_Vector

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `lora-algebra-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.LoRA.Dare
theorem _root_.PvlChallenge.ProvableContracts.LoRA.Dare.dare_unbiased (delta p : ℝ) (hp : p ≠ 1) : dare_expectation delta p = delta := sorry
end ProvableContracts.LoRA.Dare
end

section
namespace ProvableContracts.LoRA.Shape
theorem _root_.PvlChallenge.ProvableContracts.LoRA.Shape.lora_shape (m r n : Nat) : matmul_shape (m, r) (r, n) = (m, n) := sorry
end ProvableContracts.LoRA.Shape
end

section
namespace ProvableContracts.LoRA.Shape
theorem _root_.PvlChallenge.ProvableContracts.LoRA.Shape.lora_shape_matches_base (m r n : Nat) : matmul_shape (m, r) (r, n) = (m, n) := sorry
end ProvableContracts.LoRA.Shape
end

section
namespace ProvableContracts.LoRA.ShapePreservation
theorem _root_.PvlChallenge.ProvableContracts.LoRA.ShapePreservation.shape_preservation (base delta : Shape) (h : delta = base) : merge_shape base delta h = base ∧ merge_shape base delta h = delta := sorry
end ProvableContracts.LoRA.ShapePreservation
end

section
namespace ProvableContracts.LoRA.TaskVector
theorem _root_.PvlChallenge.ProvableContracts.LoRA.TaskVector.task_vector_roundtrip (w_fine w_base : ℝ) : w_base + task_vector w_fine w_base = w_fine := sorry
end ProvableContracts.LoRA.TaskVector
end
