import ProvableContracts.Theorems.LoRA.Lora_Shape
import ProvableContracts.Theorems.Lora.MergeForwardEquiv

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `lora-merge-forward-equivalence-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.LoRA.Shape
theorem _root_.PvlChallenge.ProvableContracts.LoRA.Shape.lora_shape (m r n : Nat) : matmul_shape (m, r) (r, n) = (m, n) := sorry
end ProvableContracts.LoRA.Shape
end

section
namespace ProvableContracts.LoRA.Shape
theorem _root_.PvlChallenge.ProvableContracts.LoRA.Shape.lora_shape_matches_base (m r n : Nat) : matmul_shape (m, r) (r, n) = (m, n) := sorry
end ProvableContracts.LoRA.Shape
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.composed_affine (W dW : List (List Int)) (x b : List Int) : vadd (matvec (madd W dW) x) b = vadd (vadd (matvec W x) (matvec dW x)) b := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.composed_affine_scaled (W dW : List (List Int)) (s : Int) (x b : List Int) : vadd (matvec (madd W (msmul s dW)) x) b = vadd (vadd (matvec W x) (smul s (matvec dW x))) b := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.dot_smul_left : ∀ (s : Int) (u x : List Int), dot (smul s u) x = s * dot u x := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.dot_vadd_left : ∀ (u v x : List Int), dot (vadd u v) x = dot u x + dot v x := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.dot_vecmat : ∀ (b : List Int) (A : List (List Int)) (x : List Int), dot (vecmat b A) x = dot b (matvec A x) := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.lora_merge_forward_equiv (W B A : List (List Int)) (s : Int) (x : List Int) : matvec (madd W (msmul s (matmul B A))) x = vadd (matvec W x) (smul s (matvec B (matvec A x))) := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.matvec_madd : ∀ (W M : List (List Int)) (x : List Int), matvec (madd W M) x = vadd (matvec W x) (matvec M x) := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.matvec_matmul_assoc : ∀ (B A : List (List Int)) (x : List Int), matvec (matmul B A) x = matvec B (matvec A x) := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.matvec_msmul : ∀ (s : Int) (M : List (List Int)) (x : List Int), matvec (msmul s M) x = smul s (matvec M x) := sorry
end ProvableContracts.Lora
end

section
namespace ProvableContracts.Lora
theorem _root_.PvlChallenge.ProvableContracts.Lora.merge_distributes (W M : List (List Int)) (s : Int) (x : List Int) : matvec (madd W (msmul s M)) x = vadd (matvec W x) (smul s (matvec M x)) := sorry
end ProvableContracts.Lora
end
