import ProvableContracts.Theorems.MatMul.Associativity
import ProvableContracts.Theorems.MatMul.CooperativeTiling
import ProvableContracts.Theorems.MatMul.Distributivity
import ProvableContracts.Theorems.MatMul.Identity
import ProvableContracts.Theorems.MatMul.Shape
import ProvableContracts.Theorems.MatMul.TransposeMul

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `matmul-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.CooperativeMatrix
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.CooperativeMatrix.matmul_block_sum {m k n : ℕ} (A : Matrix (Fin m) (Fin k) ℝ) (B : Matrix (Fin k) (Fin n) ℝ) : A * B = A * B := sorry
end ProvableContracts.CooperativeMatrix
end

section
namespace ProvableContracts.MatMul.Shape
theorem _root_.PvlChallenge.ProvableContracts.MatMul.Shape.matmul_output_len (m k n : Nat) : buffer_len (matmul_shape (m, k) (k, n)) = m * n := sorry
end ProvableContracts.MatMul.Shape
end

section
namespace ProvableContracts.MatMul.Shape
theorem _root_.PvlChallenge.ProvableContracts.MatMul.Shape.matmul_output_shape (m k n : Nat) : matmul_shape (m, k) (k, n) = (m, n) := sorry
end ProvableContracts.MatMul.Shape
end

section
namespace ProvableContracts.MatMul.Shape
theorem _root_.PvlChallenge.ProvableContracts.MatMul.Shape.matmul_shape_inner_cancels (m k k' n : Nat) : matmul_shape (m, k) (k, n) = matmul_shape (m, k') (k', n) := sorry
end ProvableContracts.MatMul.Shape
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_assoc {m n p q : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (B : Matrix (Fin n) (Fin p) ℝ) (C : Matrix (Fin p) (Fin q) ℝ) : (A * B) * C = A * (B * C) := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_identity_left {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : (1 : Matrix (Fin m) (Fin m) ℝ) * A = A := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_identity_right {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : A * (1 : Matrix (Fin n) (Fin n) ℝ) = A := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_left_distrib {m n p : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (B C : Matrix (Fin n) (Fin p) ℝ) : A * (B + C) = A * B + A * C := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_right_distrib {m n p : ℕ} (A B : Matrix (Fin m) (Fin n) ℝ) (C : Matrix (Fin n) (Fin p) ℝ) : (A + B) * C = A * C + B * C := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_transpose {m n p : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (B : Matrix (Fin n) (Fin p) ℝ) : (A * B)ᵀ = Bᵀ * Aᵀ := sorry
end ProvableContracts.MatMul
end
