import ProvableContracts.Theorems.MatMul.Associativity

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `matmul-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_assoc {m n p q : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (B : Matrix (Fin n) (Fin p) ℝ) (C : Matrix (Fin p) (Fin q) ℝ) : (A * B) * C = A * (B * C) := sorry
end ProvableContracts.MatMul
end
