import ProvableContracts.Theorems.Metrics.Regression
import ProvableContracts.Theorems.Metrics.RegressionAnalytic

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `metrics-regression-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.mae_nonneg (y yh : List Int) : 0 ≤ sae y yh := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.mae_self_zero (y : List Int) : sae y y = 0 := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.mse_nonneg (y yh : List Int) : 0 ≤ sse y yh := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.mse_self_zero (y : List Int) : sse y y = 0 := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.mse_symm (y yh : List Int) : sse y yh = sse yh y := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.rmse_nonneg {s x : Int} (h : IsSqrt s x) : 0 ≤ s := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.Regression
theorem _root_.PvlChallenge.ProvableContracts.Metrics.Regression.rmse_self_zero (y : List Int) : IsSqrt 0 (sse y y) := sorry
end ProvableContracts.Metrics.Regression
end

section
namespace ProvableContracts.Metrics.RegressionAnalytic
open Finset
theorem _root_.PvlChallenge.ProvableContracts.Metrics.RegressionAnalytic.mae_le_rmse {ι : Type*} (s : Finset ι) (e : ι → ℝ) (hpos : 0 < (s.card : ℝ)) : (∑ i ∈ s, |e i|) / (s.card : ℝ) ≤ Real.sqrt ((∑ i ∈ s, (e i) ^ 2) / (s.card : ℝ)) := sorry
end ProvableContracts.Metrics.RegressionAnalytic
end
