import ProvableContracts.Theorems.Embedding.Bounds

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `model-config-algebra-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_hits_table {α : Type _} (table : List α) (ids : List ℕ) (dflt : α) (hb : ∀ i ∈ ids, i < table.length) (j : ℕ) (hj : j < ids.length) : (gather table ids dflt)[j]? = some (table[ids[j]]'(hb _ (List.getElem_mem hj))) := sorry
end ProvableContracts.Embedding
end

section
namespace ProvableContracts.Embedding
theorem _root_.PvlChallenge.ProvableContracts.Embedding.gather_inbounds {α : Type _} (table : List α) (ids : List ℕ) (hb : ∀ i ∈ ids, i < table.length) (j : ℕ) (hj : j < ids.length) : (table[ids[j]]?).isSome = true := sorry
end ProvableContracts.Embedding
end
