import ProvableContracts.Theorems.QuantizedDotProduct.BsumDecomposition

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `q4k-q6k-superblock-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.QuantizedDotProduct
theorem _root_.PvlChallenge.ProvableContracts.QuantizedDotProduct.bsum_decomposition_total (chunks : List (List ℤ)) : (chunks.map List.sum).sum = chunks.flatten.sum := sorry
end ProvableContracts.QuantizedDotProduct
end

section
namespace ProvableContracts.QuantizedDotProduct
theorem _root_.PvlChallenge.ProvableContracts.QuantizedDotProduct.bsum_precompute_eq_inline (chunks : List (List ℤ)) (j : ℕ) (hj : j < chunks.length) : (chunks.map List.sum)[j]'(by simpa using hj) = (chunks[j]).sum := sorry
end ProvableContracts.QuantizedDotProduct
end
