import ProvableContracts.Theorems.LU.Existence
import ProvableContracts.Theorems.MatMul.Identity
import ProvableContracts.Theorems.QuantizedDotProduct.BsumDecomposition

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `quantized-dot-product-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.LU
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.LU.identity_is_unit_lower_triangular {n : ℕ} : IsUnitLowerTriangular (1 : Matrix (Fin n) (Fin n) ℝ) := sorry
end ProvableContracts.LU
end

section
namespace ProvableContracts.LU
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.LU.identity_is_upper_triangular {n : ℕ} : IsUpperTriangular (1 : Matrix (Fin n) (Fin n) ℝ) := sorry
end ProvableContracts.LU
end

section
namespace ProvableContracts.LU
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.LU.identity_lu {n : ℕ} : IsLUOf (1 : Matrix (Fin n) (Fin n) ℝ) (1 : Matrix (Fin n) (Fin n) ℝ) (1 : Matrix (Fin n) (Fin n) ℝ) := sorry
end ProvableContracts.LU
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_identity_left {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : (1 : Matrix (Fin m) (Fin m) ℝ) * A = A := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.MatMul
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.MatMul.matmul_identity_right {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : A * (1 : Matrix (Fin n) (Fin n) ℝ) = A := sorry
end ProvableContracts.MatMul
end

section
namespace ProvableContracts.QuantizedDotProduct
theorem _root_.PvlChallenge.ProvableContracts.QuantizedDotProduct.bsum_decomposition_total (chunks : List (List ℤ)) : (chunks.map List.sum).sum = chunks.flatten.sum := sorry
end ProvableContracts.QuantizedDotProduct
end

section
namespace ProvableContracts.QuantizedDotProduct
theorem _root_.PvlChallenge.ProvableContracts.QuantizedDotProduct.bsum_precompute_eq_inline (chunks : List (List ℤ)) (j : ℕ) (hj : j < chunks.length) : (chunks.map List.sum)[j]'(by simpa using hj) = (chunks[j]).sum := sorry
end ProvableContracts.QuantizedDotProduct
end
