import ProvableContracts.Theorems.Rope.Rope

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `rope-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.ropeList_length (xs : List (ℝ × ℝ)) (θ : ℝ) : (ropeList xs θ).length = xs.length := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.ropePairs_normSq {n : ℕ} (x : Fin n → ℝ × ℝ) (θ : Fin n → ℝ) : normSq (ropePairs x θ) = normSq x := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.ropePairs_norm_le {n : ℕ} (x : Fin n → ℝ × ℝ) (θ : Fin n → ℝ) : Real.sqrt (normSq (ropePairs x θ)) ≤ Real.sqrt (normSq x) := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.rope_angle_add (x0 x1 a b : ℝ) : rot0 (rot0 x0 x1 a) (rot1 x0 x1 a) b = rot0 x0 x1 (a + b) ∧ rot1 (rot0 x0 x1 a) (rot1 x0 x1 a) b = rot1 x0 x1 (a + b) := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.rope_identity (x0 x1 : ℝ) : rot0 x0 x1 0 = x0 ∧ rot1 x0 x1 0 = x1 := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.rope_norm_sq (x0 x1 θ : ℝ) : (rot0 x0 x1 θ) ^ 2 + (rot1 x0 x1 θ) ^ 2 = x0 ^ 2 + x1 ^ 2 := sorry
end ProvableContracts.Rope
end

section
namespace ProvableContracts.Rope
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Rope.rope_relative (q0 q1 k0 k1 a b : ℝ) : dot2 (rot0 q0 q1 a) (rot1 q0 q1 a) (rot0 k0 k1 b) (rot1 k0 k1 b) = dot2 q0 q1 (rot0 k0 k1 (b - a)) (rot1 k0 k1 (b - a)) := sorry
end ProvableContracts.Rope
end
