import ProvableContracts.Theorems.Attention.Scaling
import ProvableContracts.Theorems.CrossEntropy.CoreSoftmaxInvariants
import ProvableContracts.Theorems.Softmax.Bounded
import ProvableContracts.Theorems.Softmax.Monotonicity
import ProvableContracts.Theorems.Softmax.NonNegativity
import ProvableContracts.Theorems.Softmax.PartitionOfUnity
import ProvableContracts.Theorems.Softmax.ShiftInvariance

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `softmax-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.softmax_le_one {n : ℕ} (x : RVec (n + 1)) (i : Fin (n + 1)) : softmax x i ≤ 1 := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.AttentionScaling
open Real Finset Matrix
open ProvableContracts
open ProvableContracts.Softmax
theorem _root_.PvlChallenge.ProvableContracts.AttentionScaling.softmax_max_subtraction_invariant {n : ℕ} (x : RVec (n + 1)) (M : ℝ) (i : Fin (n + 1)) : softmax (fun j => x j - M) i = softmax x i := sorry
end ProvableContracts.AttentionScaling
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.monotone {n : ℕ} (x : RVec (n + 1)) (i j : Fin (n + 1)) (h : x i > x j) : softmax x i > softmax x j := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.partition_of_unity {n : ℕ} (x : RVec (n + 1)) : ∑ i : Fin (n + 1), softmax x i = 1 := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.shift_invariance {n : ℕ} (x : RVec (n + 1)) (c : ℝ) (i : Fin (n + 1)) : softmax (shift x c) i = softmax x i := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.softmax_bounded {n : ℕ} (x : RVec (n + 2)) (i : Fin (n + 2)) : 0 < softmax x i ∧ softmax x i < 1 := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.softmax_lt_one {n : ℕ} (x : RVec (n + 2)) (i : Fin (n + 2)) : softmax x i < 1 := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.softmax_pos {n : ℕ} (x : RVec (n + 1)) (i : Fin (n + 1)) : softmax x i > 0 := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.Softmax
open Real Finset
theorem _root_.PvlChallenge.ProvableContracts.Softmax.sum_exp_pos {n : ℕ} (x : RVec (n + 1)) : 0 < ∑ j : Fin (n + 1), Real.exp (x j) := sorry
end ProvableContracts.Softmax
end

section
namespace ProvableContracts.SoftmaxCore
theorem _root_.PvlChallenge.ProvableContracts.SoftmaxCore.softmax_denom_pos (a : Int) (t : List Int) (ha : 0 < a) (ht : ∀ y ∈ t, 0 ≤ y) : 0 < lsum (a :: t) := sorry
end ProvableContracts.SoftmaxCore
end

section
namespace ProvableContracts.SoftmaxCore
theorem _root_.PvlChallenge.ProvableContracts.SoftmaxCore.softmax_num_le_denom (l : List Int) (i : Int) (hi : i ∈ l) (h : ∀ y ∈ l, 0 ≤ y) : i ≤ lsum l := sorry
end ProvableContracts.SoftmaxCore
end

section
namespace ProvableContracts.SoftmaxCore
theorem _root_.PvlChallenge.ProvableContracts.SoftmaxCore.softmax_num_lt_denom (i : Int) (rest : List Int) (_hi : 0 ≤ i) (hrest : 0 < lsum rest) : i < lsum (i :: rest) := sorry
end ProvableContracts.SoftmaxCore
end

section
namespace ProvableContracts.SoftmaxCore
theorem _root_.PvlChallenge.ProvableContracts.SoftmaxCore.softmax_partition (w : List Int) : lsum w = lsum w := sorry
end ProvableContracts.SoftmaxCore
end
