import ProvableContracts.Theorems.F16.Conversion
import ProvableContracts.Theorems.FP8.Interchange
import ProvableContracts.Theorems.GgufExportSymmetry.Roundtrip
import ProvableContracts.Theorems.Quantization.RoundtripBound
import ProvableContracts.Theorems.TensorTranspose.Roundtrip

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `tokenizer-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
set_option maxRecDepth 4000
namespace ProvableContracts.F16
theorem _root_.PvlChallenge.ProvableContracts.F16.roundtrip_identity (h : F16Normal) : (signBit (toF32Bits h), expField (toF32Bits h) - 112, mantF16 (toF32Bits h)) = (h.s, h.e, h.m) := sorry
end ProvableContracts.F16
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e4m3 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_e5m2 (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.FP8
open ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.FP8.roundtrip_ulp (x ulp : ℝ) (h : ulp > 0) : |gridRound ulp x - x| ≤ ulp / 2 := sorry
end ProvableContracts.FP8
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.dtype_roundtrip (d : AprDType) (g : GgmlType) (h : exportDtype d = some g) : importDtype g = some d := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.dtype_roundtrip_section (g : GgmlType) (d : AprDType) (h : importDtype g = some d) : exportDtype d = some g := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.export_import_roundtrip (t : AprTensor) (gt : GgufTensor) (h : exportTensor t = some gt) : importTensor gt = some t := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.export_preserves_shape (t : AprTensor) (gt : GgufTensor) (h : exportTensor t = some gt) : gt.shape = t.shape := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.export_rejects_aprq4 : exportDtype .AprQ4 = none := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.export_rejects_aprq8 : exportDtype .AprQ8 = none := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.GgufExportSymmetry
theorem _root_.PvlChallenge.ProvableContracts.GgufExportSymmetry.import_rejects_q8_0 : importDtype .Q8_0 = none := sorry
end ProvableContracts.GgufExportSymmetry
end

section
namespace ProvableContracts.Quantization
theorem _root_.PvlChallenge.ProvableContracts.Quantization.roundtrip_bound (x : ℝ) (scale : ℝ) (hs : scale > 0) : |dequantize (quantize x scale) scale - x| ≤ scale / 2 := sorry
end ProvableContracts.Quantization
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.roundtrip_preserves_element {α : Type u} (t : Tensor2D α) (i j : Nat) : t.transpose.transpose.get i j = t.get i j := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.shape_transpose_involution (s : Shape) : s.transpose.transpose = s := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.shape_transpose_involution_vec (n : Nat) : (Shape.mk 1 n).transpose.transpose = Shape.mk 1 n := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.swapIdx_injective (a b : Nat × Nat) (h : swapIdx a = swapIdx b) : a = b := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.swapIdx_involutive (p : Nat × Nat) : swapIdx (swapIdx p) = p := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.swapIdx_surjective (p : Nat × Nat) : ∃ q, swapIdx q = p := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_element {α : Type u} (t : Tensor2D α) (i j : Nat) : t.transpose.get j i = t.get i j := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_involution {α : Type u} (t : Tensor2D α) : t.transpose.transpose = t := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_shape {α : Type u} (t : Tensor2D α) : t.transpose.rows = t.cols ∧ t.transpose.cols = t.rows := sorry
end ProvableContracts.TensorTranspose
end
