import ProvableContracts.Theorems.TensorLayout.IndexAlgebra
import ProvableContracts.Theorems.TensorTranspose.Roundtrip
import ProvableContracts.Theorems.Transpose.Involution

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `transpose-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_reindex (rows cols r c : Nat) : idx cols r c = r * cols + c ∧ idx rows c r = c * rows + r := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_reindex_bijective {rows cols r c : Nat} (hr : r < rows) (hc : c < cols) : (unrow cols (idx cols r c), uncol cols (idx cols r c)) = (r, c) ∧ (unrow rows (idx rows c r), uncol rows (idx rows c r)) = (c, r) := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_shape_1d_identity (n : Nat) : transpose1d n = n := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_shape_involution (s : Shape2) : s.transpose.transpose = s := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_shape_swap (s : Shape2) : s.transpose.d0 = s.d1 ∧ s.transpose.d1 = s.d0 := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorLayout
theorem _root_.PvlChallenge.ProvableContracts.TensorLayout.transpose_size_preserved (s : Shape2) : s.transpose.d0 * s.transpose.d1 = s.d0 * s.d1 := sorry
end ProvableContracts.TensorLayout
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_element {α : Type u} (t : Tensor2D α) (i j : Nat) : t.transpose.get j i = t.get i j := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_involution {α : Type u} (t : Tensor2D α) : t.transpose.transpose = t := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.TensorTranspose
universe u
theorem _root_.PvlChallenge.ProvableContracts.TensorTranspose.transpose_shape {α : Type u} (t : Tensor2D α) : t.transpose.rows = t.cols ∧ t.transpose.cols = t.rows := sorry
end ProvableContracts.TensorTranspose
end

section
namespace ProvableContracts.Transpose
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.Transpose.transpose_element {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (i : Fin m) (j : Fin n) : Aᵀ j i = A i j := sorry
end ProvableContracts.Transpose
end

section
namespace ProvableContracts.Transpose
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.Transpose.transpose_involution {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : (Aᵀ)ᵀ = A := sorry
end ProvableContracts.Transpose
end
