import ProvableContracts.Theorems.Transpose.Involution

-- GENERATED by `pv challenge gen` (PVL-001 EV-7a) for contract `transpose-kernel-v1`. Do not edit: `pv challenge check` regenerates it and fails on any difference.
-- Each `PvlChallenge.X` restates the contract-bound theorem `X` with its proof replaced by `sorry`.

section
namespace ProvableContracts.Transpose
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.Transpose.transpose_element {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) (i : Fin m) (j : Fin n) : Aᵀ j i = A i j := sorry
end ProvableContracts.Transpose
end

section
namespace ProvableContracts.Transpose
open Matrix
theorem _root_.PvlChallenge.ProvableContracts.Transpose.transpose_involution {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : (Aᵀ)ᵀ = A := sorry
end ProvableContracts.Transpose
end
