#!/usr/bin/env bash
# Case table for scripts/install_complexity_delta_gate.sh (#2766).
#
# The live pre-commit hook is generated by `pmat hooks install` and lives inside
# .git/, so it is not tracked and cannot be committed. What IS tracked is a byte
# copy of it (scripts/tests/fixtures/pmat_generated_pre_commit.fixture) plus the
# installer that splices the delta gate into it. This table drives the installer
# against that fixture, ends with a REAL `git commit` through the spliced hook,
# and — separately — checks the live generated hook still matches the anchors so
# a pmat upgrade that changes its shape is caught rather than silently skipped.

set -uo pipefail

HERE=$(cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(cd -- "$HERE/../.." && pwd)
INSTALL="$ROOT/scripts/install_complexity_delta_gate.sh"
GATE="$ROOT/scripts/complexity_delta_gate.sh"
FIXTURE="$HERE/fixtures/pmat_generated_pre_commit.fixture"

command -v pmat >/dev/null 2>&1 || { echo "SKIP: pmat not installed" >&2; exit 0; }
for f in "$INSTALL" "$GATE" "$FIXTURE"; do
    [ -e "$f" ] || { echo "FAIL: missing $f" >&2; exit 1; }
done

T=$(mktemp -d)
trap 'rm -rf -- "$T"' EXIT INT TERM HUP
pass=0
fail=0
ok() { pass=$((pass + 1)); printf '  ok   %s\n' "$1"; }
bad() { fail=$((fail + 1)); printf '  FAIL %s\n' "$1"; }

# fresh_repo <name> [hook-source] -> path, with the gate scripts in place so the
# spliced hook can actually find them at runtime.
fresh_repo() {
    local r="$T/$1"
    rm -rf -- "$r"
    mkdir -p "$r/scripts/lib" "$r/src"
    git init -q -b main "$r"
    git -C "$r" config user.email t@example.com
    git -C "$r" config user.name Test
    git -C "$r" config commit.gpgsign false
    git -C "$r" config core.hooksPath .git/hooks
    cp "$GATE" "$r/scripts/"
    cp "$ROOT/scripts/lib/complexity_delta_violations.jq" "$r/scripts/lib/"
    cp "${2:-$FIXTURE}" "$r/.git/hooks/pre-commit"
    chmod +x "$r/.git/hooks/pre-commit"
    printf '%s' "$r"
}

echo "== I1: splice into a byte copy of the generated hook =="
R=$(fresh_repo i1)
(cd "$R" && "$INSTALL") >"$T/i1.log" 2>&1
rc=$?
[ "$rc" -eq 0 ] && ok "installer exits 0" || { bad "installer rc=$rc"; sed 's/^/       | /' "$T/i1.log"; }
grep -F -q 'BEGIN complexity delta gate (#2766)' "$R/.git/hooks/pre-commit" \
    && ok "marker spliced in" || bad "marker missing"
grep -F -q 'pmat analyze complexity --file' "$R/.git/hooks/pre-commit" \
    && bad "the absolute per-file scan SURVIVED the splice" || ok "absolute per-file scan removed"
bash -n "$R/.git/hooks/pre-commit" 2>/dev/null && ok "spliced hook parses" || bad "spliced hook does not parse"
[ -f "$R/.git/hooks/pre-commit.pmat-original" ] && ok "original backed up" || bad "no backup written"
# the untouched tail of the generated hook must survive
grep -F -q 'SATD check' "$R/.git/hooks/pre-commit" && ok "the rest of the generated hook is intact" \
    || bad "the splice ate unrelated checks"

echo "== I2: idempotent =="
before=$(md5sum <"$R/.git/hooks/pre-commit")
(cd "$R" && "$INSTALL") >"$T/i2.log" 2>&1
rc=$?
after=$(md5sum <"$R/.git/hooks/pre-commit")
[ "$rc" -eq 0 ] && [ "$before" = "$after" ] && ok "second run is a no-op" || bad "second run rc=$rc, changed=$([ "$before" = "$after" ] && echo no || echo yes)"

echo "== I3: --check reflects reality =="
(cd "$R" && "$INSTALL" --check) >/dev/null 2>&1 && ok "--check passes when installed" || bad "--check failed when installed"
R2=$(fresh_repo i3)
(cd "$R2" && "$INSTALL" --check) >/dev/null 2>&1 && bad "--check passed when NOT installed" || ok "--check fails when not installed"

echo "== I4: --uninstall restores the generated hook byte-for-byte =="
(cd "$R" && "$INSTALL" --uninstall) >/dev/null 2>&1
if cmp -s "$R/.git/hooks/pre-commit" "$FIXTURE"; then ok "restored byte-for-byte"; else bad "restore differs from the fixture"; fi

echo "== I5: MUTATED INPUT - anchor removed, installer must REFUSE and change nothing =="
grep -v -F '# 1. Complexity analysis' "$FIXTURE" >"$T/no_anchor"
R3=$(fresh_repo i5 "$T/no_anchor")
sum_before=$(md5sum <"$R3/.git/hooks/pre-commit")
(cd "$R3" && "$INSTALL") >"$T/i5.log" 2>&1
rc=$?
sum_after=$(md5sum <"$R3/.git/hooks/pre-commit")
[ "$rc" -ne 0 ] && ok "refuses when the anchor is absent (rc=$rc)" || bad "silently 'succeeded' with no anchor"
[ "$sum_before" = "$sum_after" ] && ok "left the hook untouched" || bad "mangled the hook while failing"
grep -q 'expected exactly 1 line matching' "$T/i5.log" && ok "says why" || bad "no reason given"

echo "== I6: MUTATED INPUT - anchor duplicated, installer must REFUSE =="
{ cat "$FIXTURE"; echo '# 1. Complexity analysis (only staged source files, not entire project)'; } >"$T/dup_anchor"
R4=$(fresh_repo i6 "$T/dup_anchor")
(cd "$R4" && "$INSTALL") >"$T/i6.log" 2>&1
rc=$?
[ "$rc" -ne 0 ] && ok "refuses on a duplicated anchor (rc=$rc)" || bad "spliced against an ambiguous anchor"

echo "== I6b: MUTATED INPUT - END anchor duplicated, installer must REFUSE =="
awk '{ print }
     /Complexity check\.\.\. ⏭.*no source files staged/ { print }' "$FIXTURE" >"$T/dup_end"
R4b=$(fresh_repo i6b "$T/dup_end")
(cd "$R4b" && "$INSTALL") >"$T/i6b.log" 2>&1
rc=$?
[ "$rc" -ne 0 ] && ok "refuses on a duplicated END anchor (rc=$rc)" || bad "spliced against an ambiguous END anchor"

echo "== I7: END TO END - a real 'git commit' through the spliced hook =="
R5=$(fresh_repo i7)
nest() {
    cat <<EOF
pub fn $1(a: i32, b: i32, c: i32) -> i32 {
    let mut t = 0;
    for i in 0..a {
        if i > b {
            if i > c {
                if i % 2 == 0 {
                    if i % 3 == 0 { t += 1; } else if i % 5 == 0 { t += 2; } else { t += 3; }
                } else if i % 7 == 0 { t += 4; } else { t += 5; }
            } else if i > 0 { t += 6; } else { t += 7; }
        } else if b > c { t += 8; } else { t += 9; }
    }
    t
}
EOF
}
nest hot >"$R5/src/hot.rs"
git -C "$R5" add -A
git -C "$R5" commit -q --no-verify -m "seed"
(cd "$R5" && "$INSTALL") >/dev/null 2>&1
base_head=$(git -C "$R5" rev-parse HEAD)

# (a) the UNFREEZE case: touch the violating file without worsening it
printf '// probe added during an investigation\n' >>"$R5/src/hot.rs"
git -C "$R5" add -A
(cd "$R5" && git commit -q -m "unrelated edit to a file that already violates") >"$T/i7a.log" 2>&1
rc=$?
if [ "$rc" -eq 0 ] && [ "$(git -C "$R5" rev-parse HEAD)" != "$base_head" ]; then
    ok "commit ACCEPTED: edit to a pre-existing violation (impossible before #2766)"
else
    bad "commit refused (rc=$rc) - the file is still frozen"
    sed 's/^/       | /' "$T/i7a.log"
fi
mid_head=$(git -C "$R5" rev-parse HEAD)

# (b) the RATCHET case: worsen it
{ printf 'pub fn hot(a: i32, b: i32, c: i32) -> i32 {\n    let mut t = 0;\n    for i in 0..a {\n        if a > 0 {\n'
  printf '            if i > b {\n                if i > c {\n                    if i %% 2 == 0 {\n'
  printf '                        if i %% 3 == 0 { t += 1; } else if i %% 5 == 0 { t += 2; } else { t += 3; }\n'
  printf '                    } else if i %% 7 == 0 { t += 4; } else { t += 5; }\n'
  printf '                } else if i > 0 { t += 6; } else { t += 7; }\n'
  printf '            } else if b > c { t += 8; } else { t += 9; }\n        }\n    }\n    t\n}\n'; } >"$R5/src/hot.rs"
git -C "$R5" add -A
(cd "$R5" && git commit -q -m "worsen it") >"$T/i7b.log" 2>&1
rc=$?
if [ "$rc" -ne 0 ] && [ "$(git -C "$R5" rev-parse HEAD)" = "$mid_head" ]; then
    ok "commit REFUSED and HEAD did not move: the ratchet holds"
else
    bad "the ratchet break was committed (rc=$rc)"
    sed 's/^/       | /' "$T/i7b.log"
fi
grep -q 'WORSE' "$T/i7b.log" && ok "the refusal names the worsened function" || bad "refusal gave no reason"

echo "== I8: DRIFT - the LIVE generated hook still matches the installer anchors =="
live="$(cd -- "$(git -C "$ROOT" rev-parse --git-common-dir)" && pwd)/hooks/pre-commit"
if [ ! -f "$live" ]; then
    ok "no live generated hook to check (skipped)"
elif grep -F -q 'BEGIN complexity delta gate (#2766)' "$live"; then
    ok "live hook already carries the delta gate"
elif grep -F -q 'auto-managed by PMAT' "$live"; then
    st=$(grep -c -E '^# 1\. Complexity analysis' "$live")
    sline=$(grep -n -E '^# 1\. Complexity analysis' "$live" | cut -d: -f1 | awk 'NR == 1')
    en=$(awk -v s="${sline:-0}" 'NR > s && /Complexity check\.\.\. ⏭.*no source files staged/ { n++ } END { print n + 0 }' "$live")
    [ "$st" = 1 ] && [ "$en" = 1 ] \
        && ok "live generated hook matches both anchors exactly once" \
        || bad "live generated hook drifted: start=$st end=$en (re-anchor the installer)"
else
    ok "live hook is not pmat-generated (skipped)"
fi

printf '\ninstaller case table: %d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
