#!/usr/bin/env python3
"""tarball_workspace.py DIR: turn DIR/pkgs/<name>-<ver>/ (unpacked .crate files) into one workspace (#4114).

Writes DIR/Cargo.toml with every unpacked crate as a member and a [patch.crates-io] entry per crate
pointing at its unpacked directory. Before a publish the siblings are not on crates.io at the new
version, so without the patch nothing would resolve. With it, every sibling is compiled from its
TARBALL and never from the repository's sources. Prints "<name>\t<version>\t<dir>" per crate.
Exits 2 when DIR/pkgs holds nothing or a manifest cannot be read, because an empty workspace
would build green and prove nothing.
"""
import json
import pathlib
import sys
import tomllib


def package_name(d):
    return tomllib.loads((pathlib.Path(d) / "Cargo.toml").read_text())["package"]["name"]


def main(argv):
    # --name DIR: the [package] name of one unpacked crate (a --crate-file substitution keys on the
    # manifest, never on a split of the directory name: a version may hold '-', e.g. 0.70.0-rc.1)
    # --target-dir: `cargo metadata` JSON on stdin -> its target_directory (the gate's default build
    # target: honours CARGO_TARGET_DIR and .cargo/config.toml, never a guess)
    if len(argv) == 2 and argv[1] == "--target-dir":
        try:
            print(json.load(sys.stdin)["target_directory"])
            return 0
        except (ValueError, KeyError) as e:
            print("tarball_workspace: no target_directory in cargo metadata: %s" % e, file=sys.stderr)
            return 2
    if len(argv) == 3 and argv[1] == "--name":
        try:
            print(package_name(argv[2]))
            return 0
        except (OSError, KeyError, tomllib.TOMLDecodeError) as e:
            print("tarball_workspace: no package name in %s: %s" % (argv[2], e), file=sys.stderr)
            return 2
    if len(argv) != 2:
        print("usage: tarball_workspace.py DIR", file=sys.stderr)
        return 2
    root = pathlib.Path(argv[1])
    pkgs = sorted(p for p in (root / "pkgs").iterdir() if (p / "Cargo.toml").is_file()) if (root / "pkgs").is_dir() else []
    if not pkgs:
        print("tarball_workspace: no unpacked crate under %s/pkgs" % root, file=sys.stderr)
        return 2
    members, patch, rows = [], [], []
    for d in pkgs:
        try:
            pkg = tomllib.loads((d / "Cargo.toml").read_text())["package"]
        except (OSError, KeyError, tomllib.TOMLDecodeError) as e:
            print("tarball_workspace: unreadable manifest %s: %s" % (d / "Cargo.toml", e), file=sys.stderr)
            return 2
        members.append('    "pkgs/%s",' % d.name)
        patch.append('%s = { path = "pkgs/%s" }' % (pkg["name"], d.name))
        rows.append("%s\t%s\t%s" % (pkg["name"], pkg["version"], d))
    (root / "Cargo.toml").write_text(
        "# Generated by scripts/lib/tarball_workspace.py (#4114): the published tarballs, and nothing else.\n"
        "[workspace]\nresolver = \"2\"\nmembers = [\n" + "\n".join(members) + "\n]\n\n"
        "[patch.crates-io]\n" + "\n".join(patch) + "\n")
    print("\n".join(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
