"""Aggregate spike 028: pack outcomes, three-way tails, gate sensitivity, candidate bars -> RESULTS.md + results/summary.json.

    uv run --frozen --project scripts/laya_train python .planning/spikes/028-laya-packability-noise-floor/analyze.py
"""
import json
import re
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "scripts" / "laya_train"))
import metrics  # noqa: E402

HERE = Path(__file__).resolve().parent
R = HERE / "results"
D27 = REPO / ".planning/spikes/027-laya-calibration-slice-and-tcap/data"
LABELS = ["none", "against", "favor"]
RUNS = ["s64-es12-seed17-rep", "s64-r1-seed13", "s16-r1-seed13", "s64-es12-seed23-rep"]


def labels_of(d):
    task = json.loads((d / "task.json").read_text())
    names = list(task["criteria"].keys())
    return np.array([names.index(json.loads(l)["label"]) for l in (d / "eval.jsonl").read_text().splitlines() if l.strip()])


def pack_outcome(run):
    f = R / "pack" / (run + ".log")
    if not f.exists():
        return None
    t = f.read_text()
    line = next((l for l in t.splitlines() if l.startswith(("PACKED", "REFUSED"))), "")
    ex = re.search(r"exit=(\d+) wall_s=(\d+)", t)
    num = lambda k: (re.search(k + r"=([0-9.eE+-]+)", line) or [None, None])[1]  # noqa: E731
    return {"line": line, "exit": int(ex[1]) if ex else None, "wall_s": int(ex[2]) if ex else None,
            "variant": line.split()[1] if line.startswith("REFUSED") else "PACKED",
            "rescore_max_abs": num("rescore_max_abs") or num("max_abs"), "zs_rescore_max_abs": num("zs_rescore_max_abs"),
            "which": num("which") if "which=" in line else None}


def load(name):
    f = R / "triad" / (name + ".json")
    return json.loads(f.read_text()) if f.exists() else None


def gate_view(t, y):
    out = {}
    for k in ("rust", "torch32", "f64"):
        P = np.asarray(t["probs_full"][k], dtype=np.float64)
        P = P / P.sum(1, keepdims=True)
        out[k] = {"ece": float(metrics.ece_top_label(P, y, 15)), "macro_f1": float(metrics.macro_f1(P, y))}
    return out


summary = {"pack": {r: pack_outcome(r) for r in RUNS}, "triad": {}, "bars": {}}
lines = ["# Spike 028 — RESULTS (generated by analyze.py)", ""]
lines += ["## 1. `just laya-pack` on the gate's test eval set (280 rows), aarch64", "",
          "| checkpoint | exit | outcome | rescore_max_abs (ft) | zs_rescore_max_abs | wall s |", "|---|---|---|---|---|---|"]
for r in RUNS:
    p = summary["pack"][r]
    if p:
        lines.append("| %s | %s | `%s` | %s | %s | %s |" % (r, p["exit"], p["line"][:110], p["rescore_max_abs"], p["zs_rescore_max_abs"] or "not reached", p["wall_s"]))
lines.append("")

for set_, dname in (("test", None), ("indist", HERE / "data/indist")):
    names = ["base"] + RUNS
    rows = []
    for r in names:
        t = load("%s-%s" % (set_, r))
        if t is None:
            continue
        summary["triad"]["%s-%s" % (set_, r)] = {k: t[k] for k in t if k not in ("per_row", "probs_full", "logits_full")}
        rows.append((r, t))
    if not rows:
        continue
    title = "gate test eval (280 rows)" if set_ == "test" else "spike-027 in-distribution held-out (459 rows)"
    lines += ["## 2%s. Three-way tails — %s" % ("a" if set_ == "test" else "b", title), "",
              "Probabilities (bar `pack_rescore_probs_abs` 1e-5): max (row) / p99 / median / rows > 1e-5", "",
              "| checkpoint | T | rust − torch32 | rust − f64 | torch32 − f64 | argmax r=t / r=f / t=f | ids equal | torch rerun == stored |",
              "|---|---|---|---|---|---|---|---|"]
    fmt = lambda s: "%.2e (r%d) / %.1e / %.1e / **%d**" % (s["max"], s["row"], s["p99"], s["median"], s["over_bar"])  # noqa: E731
    for r, t in rows:
        a = t["argmax_agree"]
        lines.append("| %s | %.3f | %s | %s | %s | %d / %d / %d | %d/%d | %s |" % (
            r, t["T_applied_rust"], fmt(t["probs"]["rust_vs_torch32"]), fmt(t["probs"]["rust_vs_f64"]),
            fmt(t["probs"]["torch32_vs_f64"]), a["rust_vs_torch32"], a["rust_vs_f64"], a["torch32_vs_f64"],
            t["ids_equal"], t["n"], t.get("torch_rerun_bitwise_equal_stored_rows", "n/a")))
        for alt in t.get("alt_t", []):
            lines.append("| %s **@T=%.2f** (cap-10 probe) | %.3f | %s | %s | %s | | | |" % (
                r, alt["t"], alt["t"], fmt(alt["probs"]["rust_vs_torch32"]), fmt(alt["probs"]["rust_vs_f64"]),
                fmt(alt["probs"]["torch32_vs_f64"])))
    lines += ["", "Logits (bar `logits_abs` 1e-4): max (row) / p99 / median / rows > 1e-4; max |z|", "",
              "| checkpoint | rust − torch32 | rust − f64 | torch32 − f64 | max abs z (f64) |", "|---|---|---|---|---|"]
    for r, t in rows:
        lines.append("| %s | %s | %s | %s | %.1f |" % (r, fmt(t["logits"]["rust_vs_torch32"]), fmt(t["logits"]["rust_vs_f64"]),
                                                     fmt(t["logits"]["torch32_vs_f64"]), t["logit_abs_max"]))
    lines += ["", "Final-norm block (ladder bar `final_norm_abs` 1e-4, max over every token of every row): max / rows > 1e-4 / headroom = 1e-4 ÷ max", "",
              "| checkpoint | rust − torch32 | rust − f64 | torch32 − f64 | max abs final-norm value | f32 ulp at that value |", "|---|---|---|---|---|---|"]
    ff = lambda s: "%.2e / %d / %.2f×" % (s["max"], s["over_bar"], s["headroom"])  # noqa: E731
    for r, t in rows:
        fa = t["final_abs_max"]
        lines.append("| %s | %s | %s | %s | %.1f | %.1e |" % (r, ff(t["final"]["rust_vs_torch32"]), ff(t["final"]["rust_vs_f64"]),
                                                            ff(t["final"]["torch32_vs_f64"]), fa, float(np.spacing(np.float32(fa)))))
    # Gate sensitivity: does the served (Rust) or exact (f64) model read a different gate than the stored torch file?
    y = labels_of(dname if dname else D27 / "s64")   # s16 and s64 eval.jsonl are byte-identical (e3269525…)
    lines += ["", "Gate metrics recomputed from each side's probabilities (ECE top-label, 15 bins; macro-F1). The gate reads torch32.", "",
              "| checkpoint | ECE torch32 | ECE rust | ECE f64 | Δ ECE rust−torch | macro-F1 torch32 / rust / f64 |", "|---|---|---|---|---|---|"]
    for r, t in rows:
        if "probs_full" not in t:
            continue
        g = gate_view(t, y)
        summary["triad"]["%s-%s" % (set_, r)]["gate_view"] = g
        lines.append("| %s | %.5f | %.5f | %.5f | %+.1e | %.4f / %.4f / %.4f |" % (
            r, g["torch32"]["ece"], g["rust"]["ece"], g["f64"]["ece"], g["rust"]["ece"] - g["torch32"]["ece"],
            g["torch32"]["macro_f1"], g["rust"]["macro_f1"], g["f64"]["macro_f1"]))
    # Candidate bars
    lines += ["", "Candidate bars (probabilities). need = max|rust − torch32| (what pack compares); noise = max|torch32 − f64| (torch's own fp32 error); k_needed = need ÷ noise.", "",
              "| checkpoint | need | noise torch | noise rust (rust − f64) | k_needed | 1e-5 margin | 3×noise margin | 4×noise margin | 5e-5 margin | 1e-4 margin |",
              "|---|---|---|---|---|---|---|---|---|---|"]
    for r, t in rows:
        need = t["probs"]["rust_vs_torch32"]["max"]
        noise = t["probs"]["torch32_vs_f64"]["max"]
        rn = t["probs"]["rust_vs_f64"]["max"]
        b = {"need": need, "noise_torch": noise, "noise_rust": rn, "k_needed": need / noise,
             "margin": {"1e-5": 1e-5 / need, "3x": 3 * noise / need, "4x": 4 * noise / need, "5e-5": 5e-5 / need, "1e-4": 1e-4 / need}}
        summary["bars"]["%s-%s" % (set_, r)] = b
        m = b["margin"]
        lines.append("| %s | %.2e | %.2e | %.2e | %.2f | %.2f× | %.2f× | %.2f× | %.2f× | %.2f× |" % (
            r, need, noise, rn, b["k_needed"], m["1e-5"], m["3x"], m["4x"], m["5e-5"], m["1e-4"]))
    lines.append("")

(R / "summary.json").write_text(json.dumps(summary, indent=1) + "\n")
(HERE / "RESULTS.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
