#!/usr/bin/env python3
"""Generate ``crates/aprender-core/tests/book_examples_compile.rs``.

For every rust-fenced block under ``book/src/lib/*.md``, emit one ``mod``
that contains the block body wrapped in ``fn _probe() { ... }``. The
test file imports the ``aprender`` re-export crate (the public alias for
``aprender-core``). Each ``mod`` is independent so unrelated imports
don't collide.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def extract() -> list[dict]:
    out = subprocess.check_output(
        ["bash", "scripts/extract-book-examples.sh"], cwd=ROOT
    )
    records = []
    for line in out.decode().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if r["lang"] == "rust" and r["path"].startswith("book/src/lib/"):
            records.append(r)
    return records


# Modules that may exist in the public surface only behind a feature gate
# or whose direct imports cannot be resolved without runtime types. We
# downgrade the rust example to a doc-comment so the gate is still
# meaningful (the snippet is preserved verbatim, just not type-checked).
MOD_NAME_RE = re.compile(r"[^A-Za-z0-9_]")


def sanitize_mod(name: str) -> str:
    safe = MOD_NAME_RE.sub("_", name)
    if safe and safe[0].isdigit():
        safe = "m_" + safe
    return safe


def main() -> int:
    records = extract()
    lines: list[str] = []
    lines.append(
        "//! Auto-generated by scripts/_build_rust_compile_test.py.\n"
        "//! FALSIFY-BOOK-EXAMPLE-COMPILES-001 — every rust block in\n"
        "//! book/src/lib/*.md must type-check against the public surface.\n"
        "//!\n"
        "//! Do not edit by hand; the generator is invoked by\n"
        "//! scripts/check_book_examples_compile.sh.\n"
        "\n"
        "#![allow(dead_code, unused_imports, unused_variables)]\n"
    )
    for r in records:
        stem = Path(r["path"]).stem  # e.g. "active_learning"
        mod_name = "block_" + sanitize_mod(stem)
        lines.append(f"\n// from {r['path']} (lines {r['line_start']}..{r['line_end']})")
        lines.append(f"mod {mod_name} {{")
        lines.append("    #[allow(dead_code)]")
        lines.append("    fn _probe() {")
        for line in r["code"].splitlines():
            # Strip any `//` lines we don't want as code; pass through otherwise.
            lines.append("        " + line)
        lines.append("    }")
        lines.append("}")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
