#!/usr/bin/env bash
# check_parity_block_refusals.sh — a zero or empty COMPARATOR band must be a
# NAMED refusal, never a Python traceback (#2735, #2887, PMAT-972).
#
# WHY THIS EXISTS
# ---------------
# scripts/lib/parity_block.py builds a parity block from harness reports and
# derives every ratio as `statistics.median(subject) / statistics.median
# (comparator)`. A zero-token SUBJECT band refuses cleanly today: the
# division itself never crashes (0 / positive == 0.0), and the block's own
# self-validation (bench_receipt.validate_parity) rejects it downstream with
# "contains a non-positive rate". A zero-token COMPARATOR band is the
# opposite case -- the division IS the crash, and it happens before
# self-validation ever runs, so a `ZeroDivisionError` traceback reaches the
# caller where a FAIL verdict belongs. An empty (no-runs) comparator band
# raises `statistics.StatisticsError` the same way. This guards both.
#
#   bash scripts/check_parity_block_refusals.sh --selftest   # case table
#
# The fixtures are generated by the self-test itself, under mktemp -d, in the
# HISTORICAL layout scripts/lib/parity_block_selftest.sh builds (sourced from
# this script). Nothing here reads a real harness report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROG=check_parity_block_refusals
export PBS_ROOT="$ROOT"

usage() {
    printf 'usage: %s --selftest\n' "$PROG" >&2
    exit 2
}

if [ "${1:-}" != "--selftest" ]; then
    usage
fi

command -v python3 >/dev/null 2>&1 || { printf '%s: ENV - python3 is missing\n' "$PROG" >&2; exit 2; }

# shellcheck source=scripts/lib/parity_block_selftest.sh
. "$ROOT/scripts/lib/parity_block_selftest.sh" || exit 1

TD=$(mktemp -d "${TMPDIR:-/tmp}/parity-block-selftest.XXXXXX")
safe_rm_scratch() {
    local victim=${1:-} must=${2:-}
    [ -n "$victim" ] || return 0
    [ -n "$must" ]   || return 0
    [ "$victim" != "/" ] || return 0
    case "$victim" in
      *"$must"*) if [ -n "$victim" ] && [ "$victim" != "/" ]; then rm -rf -- "$victim"; fi ;;
      *) return 0 ;;
    esac
}
cleanup() { safe_rm_scratch "$TD" 'parity-block-selftest.'; }
trap cleanup EXIT

n=0; red=0

row() { # row <want-rc> <label> <cmd...>
    local want=$1 label=$2; shift 2; local rc=0
    n=$((n + 1))
    "$@" >"$TD/out.$n" 2>&1 || rc=$?
    if [ "$rc" = "$want" ]; then printf 'ok    row %-2s rc=%s  %s\n' "$n" "$rc" "$label"
    else printf 'FAIL  row %-2s rc=%s (wanted %s)  %s\n' "$n" "$rc" "$want" "$label"; sed 's/^/        /' "$TD/out.$n"; red=1; fi
}

assert_contains() { # assert_contains <row-n> <needle> <label>
    local i=$1 needle=$2 label=$3
    if grep -qF -- "$needle" "$TD/out.$i"; then
        printf 'ok    row %-2s output contains: %s  (%s)\n' "$i" "$needle" "$label"
    else
        printf 'FAIL  row %-2s missing expected text: %s  (%s)\n' "$i" "$needle" "$label"
        sed 's/^/        /' "$TD/out.$i"
        red=1
    fi
}

assert_not_contains() { # assert_not_contains <row-n> <needle> <label>
    local i=$1 needle=$2 label=$3
    if grep -qF -- "$needle" "$TD/out.$i"; then
        printf 'FAIL  row %-2s contains forbidden text: %s  (%s)\n' "$i" "$needle" "$label"
        sed 's/^/        /' "$TD/out.$i"
        red=1
    else
        printf 'ok    row %-2s does not contain: %s  (%s)\n' "$i" "$needle" "$label"
    fi
}

# --- fixtures --------------------------------------------------------------
CONTROL="$TD/control"; ZC="$TD/zero-comparator"; ZS="$TD/zero-subject"; EC="$TD/empty-comparator"
mkdir -p "$CONTROL" "$ZC" "$ZS" "$EC"
pbs_make_fixture "$CONTROL" none       clean
pbs_make_fixture "$ZC"      comparator zero
pbs_make_fixture "$ZS"      subject    zero
pbs_make_fixture "$EC"      comparator empty

# --- rows --------------------------------------------------------------
row 0 "control fixture: both sides positive at every band -> PASS" \
    pbs_run "$CONTROL" "$TD/control.json"

row 1 "zero-COMPARATOR band c=8 -> a NAMED refusal, not a traceback" \
    pbs_run "$ZC" "$TD/zc.json"
assert_contains "$n" "band 8 comparator: non-positive rate is not a measurement" \
    "zero comparator names the band and the side"
assert_not_contains "$n" "Traceback" \
    "zero comparator must never crash"

row 1 "zero-SUBJECT band c=8 -> the EXISTING subject refusal, untouched" \
    pbs_run "$ZS" "$TD/zs.json"
assert_contains "$n" "contains a non-positive rate" \
    "the pre-existing bench_receipt._median_of subject wording still fires"
assert_not_contains "$n" "Traceback" \
    "zero subject never crashed before this fix and must not now"

row 1 "empty-COMPARATOR band c=8 (no runs at all) -> a NAMED refusal, not a traceback" \
    pbs_run "$EC" "$TD/ec.json"
assert_contains "$n" "band 8 comparator: no samples is not a measurement" \
    "an empty comparator band names the band and the side"
assert_not_contains "$n" "Traceback" \
    "an empty comparator band must never crash"

if [ "$red" = 0 ]; then
    printf 'PASS  %s: every fixture (control, zero comparator, zero subject, empty comparator) verdicts as a named result, never a traceback\n' "$PROG"
    exit 0
fi
printf 'FAIL  %s: see rows above\n' "$PROG" >&2
exit 1
