#!/bin/bash
# CI/CD script for Aprender
# Hand-maintained. The header used to say "Generated by bashrs - DO NOT EDIT
# MANUALLY / Source: scripts/ci.rs", but scripts/ci.rs is not in the tree, so
# there is nothing to regenerate from; edits land here (PMAT-742, 2026-09-03).

set -euo pipefail

echo "🚀 Aprender CI/CD Pipeline"
echo "=========================="
echo ""

# Configuration
COVERAGE_THRESHOLD=85

# Step 1: Format check
echo "📝 [1/7] Format check..."
if ! cargo fmt --check; then
    echo "❌ Format check failed"
    exit 1
fi
echo "✅ Format check passed"

# Step 2: Clippy
echo "🔍 [2/7] Clippy analysis..."
if ! cargo clippy --all-targets -- -D warnings; then
    echo "❌ Clippy check failed"
    exit 1
fi
echo "✅ Clippy check passed"

# Step 3: Unit tests
echo "🧪 [3/7] Unit tests..."
if ! cargo test --lib; then
    echo "❌ Unit tests failed"
    exit 1
fi
echo "✅ Unit tests passed"

# Step 4: Property tests
echo "🎲 [4/7] Property tests (256 cases)..."
if ! PROPTEST_CASES=256 cargo test --workspace --test property_tests; then
    echo "❌ Property tests failed"
    exit 1
fi
echo "✅ Property tests passed"

# Step 5: Doc tests
echo "📚 [5/7] Documentation tests..."
if ! cargo test --doc; then
    echo "❌ Doc tests failed"
    exit 1
fi
echo "✅ Doc tests passed"

# Step 6: Coverage (optional, requires cargo-llvm-cov)
echo "📊 [6/7] Coverage analysis..."
if command -v cargo-llvm-cov &> /dev/null; then
    # mold breaks LLVM coverage. This used to `mv ~/.cargo/config.toml` aside for the run,
    # renaming a file every other cargo process on the host reads, and leaving it renamed when
    # the run was killed before the restore. Refuse instead, as the Makefile does (#3839, #4097).
    cargo_cfg="${CARGO_HOME:-"$HOME/.cargo"}/config.toml"
    if [ -f "$cargo_cfg" ] && grep -q mold "$cargo_cfg"; then
        echo "❌ $cargo_cfg enables mold, which breaks LLVM coverage instrumentation."
        echo "   Refusing rather than moving a file every other cargo process on this host reads (#4097)."
        echo "   Run with CARGO_HOME pointing at a copy without mold, or remove mold from that file."
        exit 1
    fi

    cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    COVERAGE=$(cargo llvm-cov report $(python3 scripts/coverage_report_scope.py) --summary-only 2>&1 | grep "TOTAL" | awk '{print $10}' | tr -d '%')

    echo "Coverage: ${COVERAGE}%"
    if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
        echo "⚠️  Coverage ${COVERAGE}% below threshold ${COVERAGE_THRESHOLD}%"
    else
        echo "✅ Coverage check passed"
    fi
else
    echo "⚠️  cargo-llvm-cov not installed, skipping coverage"
fi

# Step 7: TDG Score (optional, requires pmat)
echo "📈 [7/7] TDG Score analysis..."
if command -v pmat &> /dev/null; then
    TDG_OUTPUT=$(pmat tdg 2>&1)
    echo "$TDG_OUTPUT"
    echo "✅ TDG analysis complete"
else
    echo "⚠️  pmat not installed, skipping TDG analysis"
fi

echo ""
echo "🎉 CI/CD Pipeline Complete!"
echo ""

exit 0
