#!/usr/bin/env python3
"""Derive `contracts/apr-verb-classification-v1.yaml` from the CLI command registry (gh#3597).

WHY THIS IS DERIVED AND NOT HAND-LISTED
=======================================
#3597's done_when 1 is "**0** of the 111 registry verbs is unclassified", and done_when 5 is that
the classification is "committed as data the release notes are generated from, not as prose in a PR
body". A hand-maintained table satisfies neither for long: the registry gains a verb, the table does
not, and the count that was true on the day it was written goes on reading true.

So every row here is computed from `contracts/apr-cli-commands-v1.yaml`, which FALSIFY-CLI-001/002
already holds as the SSOT. Re-running this script is how you check the classification is current;
`--check` fails if the committed file is not what the registry produces today.

THE BUCKETS, AND WHAT DECIDES THEM
==================================
`requires_model` in the registry is the discriminator, and it is a structural fact rather than a
judgement:

  V       requires_model: true   — the verb takes the blessed model, so it CAN carry a receipt on
                                   it. A receipt is owed on BOTH CUDA host classes (intel + gx10);
                                   #3597 done_when 2 says partial coverage is a refusal, not a pass.
  V2      requires_model: false  — the verb takes no model at all, so "receipted on Qwen3.5" is not
                                   a statement that can be made about it. Judged on passes-or-
                                   refuses-by-name instead.
  refusal                        — an explicit refusal carrying `removed_by` and an exit code.

**The `*-lint` blanket disposition, PROPOSED rather than assumed** (#3597 done_when 1 asks for a
proposal): all 32 `*-lint` verbs have `requires_model: false` in the registry — not 31, not "mostly"
— so they land in V2 by the same rule every other non-model-bound verb does. That is a blanket
disposition arrived at by a property they all share, not a blanket exemption granted because there
are 32 of them. If any `*-lint` verb ever gains `requires_model: true`, it leaves V2 automatically
and this script will say so.

WHAT THIS FILE DOES NOT CLAIM
=============================
A `V` row with `dogfood: U` is **not** a pass. It records that the verb is model-bound and therefore
owes a receipt, and that the receipt does not exist yet. Turning `U` into a pass requires the
dogfood run on both host classes — it is not something this script can or should infer. Absence of a
receipt is recorded as absence, never as a pass.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REGISTRY = Path("contracts/apr-cli-commands-v1.yaml")
OUT = Path("contracts/apr-verb-classification-v1.yaml")
HEADER = "# GENERATED by scripts/derive_verb_classification.py — do not hand-edit rows.\n"

# Refusals are the ONE hand-maintained input, because "this verb refuses on this architecture" is a
# measured behaviour and nothing in the registry records it. Each needs a reason, a `removed_by` and
# the source that measured it — #3597 done_when 3: a refusal states one line, an exit code and
# `removed_by`, and a refusal naming the wrong defect is a fail-open.
KNOWN_REFUSAL = {
    "bench": {
        "exit_code": 5,
        "line": (
            "error: Validation failed: Failed to create model: Format error: Architecture 'qwen35' "
            "is the Qwen3.5 hybrid (Gated Delta Net, detected tensor 'blk.0.ssm_a'): it runs "
            "through `Qwen35Model` (realizar::gguf::forward_qwen35, CPU #3091) or "
            "`Qwen35CudaModel` (GPU #3090), NOT through the dense QuantizedGGUFTransformer loader, "
            "whose per-layer tensor names this file does not carry. Load it with `apr run` / "
            "`apr chat`, which dispatch this architecture to the hybrid forward."
        ),
        "stream": "stderr",
        "reason": (
            "refuses qwen35 outright — the benchmark subcommand cannot measure the flagship "
            "architecture. The refusal is HONEST today and stays a refusal."
        ),
        "removed_by": "v0.70",
        "measured_on": "apr 0.68.2 (e6f77c98c), Qwen3.5-0.8B-Q4_K_M.gguf, 2026-09-21",
        "source": "gh#3597",
    },
}

# done_when 3, enforced rather than cited. An earlier revision of this file quoted the clause in a
# comment and then shipped a refusal carrying only `removed_by` — all three quorum lanes found it,
# unanimously. A requirement stated in prose beside data that violates it is worth less than no
# statement at all, because it reads as coverage.
REFUSAL_REQUIRED = ("exit_code", "line", "removed_by", "reason", "stream", "measured_on")


def _check_refusals() -> None:
    """Refuse to emit at all if a refusal row is missing what done_when 3 requires."""
    for verb, row in KNOWN_REFUSAL.items():
        missing = [k for k in REFUSAL_REQUIRED if not row.get(k)]
        if missing:
            raise SystemExit(
                f"derive_verb_classification: refusal row '{verb}' is missing {missing}.\n"
                "  gh#3597 done_when 3: \"Every refusal states one line, an exit code, and "
                "removed_by.\"\n"
                "  A refusal row without its exit code is not a classification, it is a note."
            )
        if not isinstance(row["exit_code"], int):
            raise SystemExit(
                f"derive_verb_classification: refusal row '{verb}' has a non-integer exit_code "
                f"{row['exit_code']!r} — it must be the code the binary actually returned."
            )


def derive(registry: dict) -> dict:
    _check_refusals()
    cmds = registry["commands"]
    rows = []
    for c in sorted(cmds, key=lambda x: x["name"]):
        name = c["name"]
        requires_model = bool(c.get("requires_model"))
        common = {
            "verb": name,
            "requires_model": requires_model,
            "category": c.get("category"),
        }
        if name in KNOWN_REFUSAL:
            r = KNOWN_REFUSAL[name]
            rows.append({**common, "bucket": "refusal", "basis": "measured", **r})
        elif requires_model:
            rows.append(
                {
                    **common,
                    "bucket": "V",
                    "basis": "registry",
                    "dogfood": "U",
                    "reason": (
                        "model-bound: takes the blessed model, so it CAN carry a receipt on it. "
                        "Receipt owed on intel AND gx10 before this row is a pass."
                    ),
                }
            )
        else:
            rows.append(
                {
                    **common,
                    "bucket": "V2",
                    "basis": "registry",
                    "reason": (
                        'not model-bound: takes no model, so "receipted on Qwen3.5" is not a '
                        "statement that can be made about it. Judged on passes-or-refuses-by-name."
                    ),
                }
            )

    counts = {
        "total": len(rows),
        "V": sum(1 for r in rows if r["bucket"] == "V"),
        "V2": sum(1 for r in rows if r["bucket"] == "V2"),
        "refusal": sum(1 for r in rows if r["bucket"] == "refusal"),
        "unclassified": 0,
        "dogfood_denominator": sum(1 for r in rows if r.get("dogfood") == "U"),
    }
    # The partition must be exact: every verb in exactly one bucket, no verb in none.
    assert counts["V"] + counts["V2"] + counts["refusal"] == counts["total"], counts
    assert counts["total"] == len(cmds), (counts["total"], len(cmds))

    return {
        "schema": "apr/verb-classification/v1",
        "issue": 3597,
        "derived_from": str(REGISTRY),
        "registry_commands": len(cmds),
        "note": (
            "DERIVED, not hand-listed. Every field but `dogfood` and the refusal rows comes from "
            "the registry, so this file cannot drift from the SSOT without --check failing."
        ),
        "counts": counts,
        "verbs": rows,
    }


def render(doc: dict) -> str:
    return HEADER + yaml.safe_dump(doc, sort_keys=False, width=100, allow_unicode=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed file is not what the registry produces today",
    )
    args = ap.parse_args()

    if not REGISTRY.exists():
        print(f"derive_verb_classification: {REGISTRY} not found — run from the repo root", file=sys.stderr)
        return 2

    text = render(derive(yaml.safe_load(REGISTRY.read_text())))

    if args.check:
        if not OUT.exists():
            print(f"REJECT: {OUT} does not exist; run without --check to create it", file=sys.stderr)
            return 1
        if OUT.read_text() != text:
            print(
                f"REJECT: {OUT} is not what {REGISTRY} produces today.\n"
                "        The registry gained or changed a verb and the classification did not "
                "follow.\n"
                f"        Fix: python3 {Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        doc = yaml.safe_load(text)
        print(
            "ok  {total} verbs classified, 0 unclassified "
            "(V={V} V2={V2} refusal={refusal}); dogfood denominator {dogfood_denominator}".format(
                **doc["counts"]
            )
        )
        return 0

    OUT.write_text(text)
    doc = yaml.safe_load(text)
    print("wrote {} — {}".format(OUT, doc["counts"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
