import csv
rows = list(csv.DictReader(open("docs/audits/surface_audit.csv", newline='', encoding='utf-8')))
sel = [r for r in rows
       if int(r["quality_1_10"]) <= 4
       and (r["in_dogfood_skill"] or "").strip().lower() != "yes"]
sel.sort(key=lambda r: (int(r["quality_1_10"]), r["feature"]))

out = []
out.append("# THE 44 — features carrying a live ledger defect with NO gate.")
out.append("#")
out.append("# Generated by scripts/dogfood_the44.py from docs/audits/surface_audit.csv")
out.append("# at cbb1ccd78 on 2026-08-22. All 44 are in `apr`.")
out.append("#")
out.append("# Each entry needs EITHER an open issue OR an explicit written waiver")
out.append("# before the next release. `issue:` and `waiver:` both null is the")
out.append("# unresolved state and is what F-DOGCOV-009 fails on.")
out.append("#")
out.append("# A waiver is a SENTENCE, not a checkbox: say why shipping this ungated")
out.append("# is acceptable for this release. \"low priority\" is not a waiver.")
out.append("")
out.append("metadata:")
out.append("  generated_at: '2026-08-22'")
out.append("  generated_commit: cbb1ccd78")
out.append("  source: docs/audits/surface_audit.csv")
out.append(f"  count: {len(sel)}")
out.append("  regenerate: python3 scripts/dogfood_the44.py")
out.append("")
out.append("features:")
for r in sel:
    out.append(f"- feature: {r['feature']!r}")
    out.append(f"  quality: {r['quality_1_10']}")
    out.append(f"  hardware: {r['verified_hardware']}")
    out.append(f"  confidence: {r['confidence']}")
    out.append(f"  evidence: {r['evidence_path']!r}")
    out.append("  issue: null")
    out.append("  waiver: null")
open("docs/audits/dogfood-the-44.yaml", "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"wrote {len(sel)} entries")
