# extract_ggml_traits.awk — classify every ggml tensor-type id and emit the fixture.
#
# Called by scripts/extract_ggml_traits.sh. This half does the two jobs the shell
# should not do inline: it classifies each id live/Removed from `enum ggml_type`
# BY WHETHER ITS LINE IS COMMENTED (never by the comment's wording —
# `// GGML_TYPE_Q4_0_4_8 = 32,` says nothing), and it refuses to emit unless that
# classification agrees with the compiled table.
#
# WHY awk AND NOT python3. This was python3, and `workspace-test-shard (3/3)`
# failed with `python3: command not found` — the containerized job has no python.
# The self-test that proves this classifier can fail has to run WHERE CI RUNS, so
# the classifier may not depend on an interpreter that is absent there. awk is in
# the container, and in every base image this fleet uses. Measured, not assumed:
# the previous version of this file was python and its self-test was green on the
# dev box and exit 127 in CI.
#
# Inputs (as -v):  pin, resolved, probe (TSV path), header (ggml.h path)
# Output: the fixture JSON on stdout.
# Exit:   0 ok · 2 malformed input · 7 the header and the compiled table disagree.

function fail(msg) { print "extract: " msg > "/dev/stderr"; problems = problems + 1 }

BEGIN {
    if (pin == "" || resolved == "" || probe == "" || header == "") {
        print "extract: pin, resolved, probe and header are all required" > "/dev/stderr"
        exit 2
    }

    # ---- the header: id -> name, and whether its line is COMMENTED -------
    inside = 0; header_count = -1; n_header = 0
    while ((getline line < header) > 0) {
        if (!inside) { if (line ~ /^[ \t]*enum ggml_type[ \t]*\{/) inside = 1; continue }
        if (line ~ /^[ \t]*\};/) break
        # A row is: optional `//`, then GGML_TYPE_<NAME> = <id>,
        if (line !~ /^[ \t]*(\/\/[ \t]*)?GGML_TYPE_[A-Z0-9_]+[ \t]*=[ \t]*[0-9]+[ \t]*,/) continue
        commented = (line ~ /^[ \t]*\/\//) ? 1 : 0
        name = line; sub(/^[ \t]*(\/\/[ \t]*)?GGML_TYPE_/, "", name); sub(/[ \t]*=.*$/, "", name)
        id = line; sub(/^[^=]*=[ \t]*/, "", id); sub(/[^0-9].*$/, "", id)
        if (name == "COUNT") { header_count = id + 0; continue }
        hname[id + 0] = name
        hlive[id + 0] = (commented ? 0 : 1)
        n_header = n_header + 1
    }
    close(header)
    if (header_count < 0) { print "extract: no GGML_TYPE_COUNT in enum ggml_type" > "/dev/stderr"; exit 2 }

    # ---- the compiled table, as the probe printed it ---------------------
    if ((getline first < probe) <= 0) { print "extract: probe produced nothing" > "/dev/stderr"; exit 2 }
    probe_count = first + 0
    n_probe = 0
    while ((getline line < probe) > 0) {
        n = split(line, f, "\t")
        if (n < 5) continue
        id = f[1] + 0
        pname[id] = f[2]; pblck[id] = f[3] + 0; psize[id] = f[4] + 0; pquant[id] = (f[5] + 0 == 1)
        seen[id] = 1
        n_probe = n_probe + 1
    }
    close(probe)

    # ---- the cross-check that can FAIL -----------------------------------
    problems = 0
    if (header_count != probe_count)
        fail("GGML_TYPE_COUNT: header " header_count " vs compiled " probe_count)
    if (n_probe != probe_count)
        fail("probe emitted " n_probe " rows for COUNT " probe_count)
    for (i = 0; i < probe_count; i++) {
        if (!(i in hname)) { fail("id " i " is in the compiled table but not in the header enum"); continue }
        if (!(i in seen)) { fail("id " i " (" hname[i] ") is in the header but not in the compiled table"); continue }
        compiled_live = (pblck[i] > 0) ? 1 : 0
        if (hlive[i] != compiled_live)
            fail("id " i " (" hname[i] "): header says " (hlive[i] ? "live" : "Removed") \
                 ", compiled table says " (compiled_live ? "live" : "Removed") \
                 " (blck_size=" pblck[i] ", type_name=\"" pname[i] "\")")
        if (hlive[i] && psize[i] <= 0)
            fail("id " i " (" hname[i] ") is live but type_size is " psize[i])
    }
    if (problems > 0) {
        print "extract: the header and the compiled table disagree (" problems " problem(s))" > "/dev/stderr"
        exit 7
    }

    # ---- emit ------------------------------------------------------------
    live = 0
    for (i = 0; i < probe_count; i++) if (hlive[i]) live = live + 1

    print "{"
    print "  \"_comment\": \"GENERATED by scripts/extract_ggml_traits.sh from upstream ggml at the pinned comparator commit. Do not hand-edit: regenerate. trueno_quant asserts that pin_build_commit below still equals scripts/llama_pin.toml build_commit.\","
    print "  \"source\": \"llama.cpp ggml/include/ggml.h + libggml-base type_traits\","
    print "  \"pin_build_commit\": \"" pin "\","
    print "  \"resolved_sha\": \"" resolved "\","
    print "  \"ggml_type_count\": " probe_count ","
    print "  \"live_count\": " live ","
    print "  \"removed_count\": " (probe_count - live) ","
    print "  \"types\": ["
    for (i = 0; i < probe_count; i++) {
        print "    {"
        print "      \"id\": " i ","
        print "      \"enum_name\": \"" hname[i] "\","
        print "      \"ggml_name\": \"" json_escape(pname[i]) "\","
        print "      \"status\": \"" (hlive[i] ? "live" : "removed") "\","
        print "      \"blck_size\": " pblck[i] ","
        print "      \"type_size\": " psize[i] ","
        print "      \"is_quantized\": " (pquant[i] ? "true" : "false")
        print "    }" (i == probe_count - 1 ? "" : ",")
    }
    print "  ]"
    print "}"
    exit 0
}

# ggml's removed rows carry a type_name with commas and spaces but no quotes or
# backslashes; escape anyway rather than rely on that staying true upstream.
function json_escape(s,   out) {
    out = s
    gsub(/\\/, "\\\\", out)
    gsub(/"/, "\\\"", out)
    return out
}
