#!/usr/bin/env python3
"""Emit the ggml tensor-type fixture from a compiled probe + the upstream header.

Called by scripts/extract_ggml_traits.sh, which owns pin resolution and the
probe build. This half does two jobs the shell should not: it classifies each
id live/Removed from `enum ggml_type` BY WHETHER ITS LINE IS COMMENTED (never
by the comment's wording -- `// GGML_TYPE_Q4_0_4_8 = 32,` says nothing), and it
refuses to emit unless that classification agrees with the compiled table.

Exit 0 on success, 7 on any disagreement, 2 on a malformed input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys

ROW = re.compile(r"^\s*(//\s*)?GGML_TYPE_([A-Z0-9_]+)\s*=\s*(\d+)\s*,")


def parse_header(path: str) -> tuple[dict[int, tuple[str, bool]], int]:
    """Return {id: (NAME, live)} and GGML_TYPE_COUNT from `enum ggml_type`."""
    rows: dict[int, tuple[str, bool]] = {}
    count = None
    inside = False
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if not inside:
                if re.match(r"^\s*enum ggml_type\s*\{", line):
                    inside = True
                continue
            if re.match(r"^\s*\};", line):
                break
            match = ROW.match(line)
            if not match:
                continue
            commented, name, id_text = match.groups()
            ident = int(id_text)
            if name == "COUNT":
                count = ident
                continue
            rows[ident] = (name, commented is None)
    if count is None:
        print("extract: no GGML_TYPE_COUNT in enum ggml_type", file=sys.stderr)
        sys.exit(2)
    return rows, count


def parse_probe(path: str) -> tuple[list[dict[str, object]], int]:
    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    if not lines:
        print("extract: probe produced nothing", file=sys.stderr)
        sys.exit(2)
    count = int(lines[0])
    types: list[dict[str, object]] = []
    for line in lines[1:]:
        ident, name, blck, size, quant = line.split("\t")
        types.append(
            {
                "id": int(ident),
                "ggml_name": name,
                "blck_size": int(blck),
                "type_size": int(size),
                "is_quantized": quant == "1",
            }
        )
    return types, count


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--probe", required=True)
    ap.add_argument("--header", required=True)
    ap.add_argument("--pin", required=True)
    ap.add_argument("--resolved", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    header, header_count = parse_header(args.header)
    probe, probe_count = parse_probe(args.probe)
    problems: list[str] = []

    if header_count != probe_count:
        problems.append(f"GGML_TYPE_COUNT: header {header_count} vs compiled {probe_count}")
    if len(probe) != probe_count:
        problems.append(f"probe emitted {len(probe)} rows for COUNT {probe_count}")
    missing = sorted(set(range(probe_count)) - set(header))
    if missing:
        problems.append(f"ids in the compiled table but not in the header enum: {missing}")

    out_types = []
    for row in probe:
        ident = int(row["id"])
        name, live = header.get(ident, ("", False))
        # THE CROSS-CHECK. A row the header comments out must be dead in the
        # compiled table too (ggml gives it blck_size 0 and a DEPRECATED /
        # "... REMOVED ..." type_name), and a live row must have a real block.
        compiled_live = int(row["blck_size"]) > 0
        if live != compiled_live:
            problems.append(
                f"id {ident} ({name}): header says {'live' if live else 'Removed'}, "
                f"compiled table says {'live' if compiled_live else 'Removed'} "
                f"(blck_size={row['blck_size']}, type_name={row['ggml_name']!r})"
            )
        if live and int(row["type_size"]) <= 0:
            problems.append(f"id {ident} ({name}) is live but type_size is {row['type_size']}")
        out_types.append(
            {
                "id": ident,
                "enum_name": name,
                "ggml_name": row["ggml_name"],
                "status": "live" if live else "removed",
                "blck_size": int(row["blck_size"]),
                "type_size": int(row["type_size"]),
                "is_quantized": bool(row["is_quantized"]),
            }
        )

    if problems:
        print("extract: the header and the compiled table disagree:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 7

    live = [t for t in out_types if t["status"] == "live"]
    fixture = {
        "_comment": (
            "GENERATED by scripts/extract_ggml_traits.sh from upstream ggml at the pinned "
            "comparator commit. Do not hand-edit: regenerate. trueno_quant asserts that "
            "pin_build_commit below still equals scripts/llama_pin.toml build_commit."
        ),
        "source": "llama.cpp ggml/include/ggml.h + libggml-base type_traits",
        "pin_build_commit": args.pin,
        "resolved_sha": args.resolved,
        "ggml_type_count": probe_count,
        "live_count": len(live),
        "removed_count": len(out_types) - len(live),
        "types": out_types,
    }
    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump(fixture, handle, indent=2, sort_keys=False)
        handle.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
