#!/usr/bin/env bash
# scripts/install_complexity_delta_gate.sh — splice the DELTA gate (#2766) into
# the pmat-generated pre-commit hook.
#
# The live hook is NOT tracked by git.  The chain in this repo is:
#
#   core.hooksPath = .git/hooks-apr
#     .git/hooks-apr/pre-commit   (apr-agent worktree guard)
#       -> exec $(git rev-parse --git-common-dir)/hooks/pre-commit
#            (generated by `pmat hooks install`, marked DO NOT EDIT)
#
# and it is that generated file which holds the absolute-threshold scan of
# staged FILES.  `pmat hooks install` regenerates it, so this installer is
# idempotent and re-runnable: run it again after any `make hooks-install`.
#
# It refuses to do nothing quietly.  If the anchors it splices between are not
# found, it exits 1 with the reason rather than leaving an unpatched hook behind
# a success message.
#
# Usage:
#   scripts/install_complexity_delta_gate.sh          # install / re-install
#   scripts/install_complexity_delta_gate.sh --check  # verify only, no writes
#   scripts/install_complexity_delta_gate.sh --uninstall

set -euo pipefail

MARKER='BEGIN complexity delta gate (#2766)'
START_RE='^# 1\. Complexity analysis'
END_MARK_RE='Complexity check\.\.\. ⏭.*no source files staged'

mode=${1:---install}

repo_root=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "ERROR: not inside a git worktree" >&2
    exit 1
}
common_dir=$(cd -- "$(git rev-parse --git-common-dir)" && pwd)
HOOK="$common_dir/hooks/pre-commit"
BACKUP="$HOOK.pmat-original"

if [ ! -f "$HOOK" ]; then
    echo "ERROR: no pre-commit hook at $HOOK" >&2
    echo "       run 'pmat hooks install' (or 'make hooks-install') first." >&2
    exit 1
fi

installed() { grep -F -q "$MARKER" "$HOOK"; }

case "$mode" in
--check)
    if installed; then
        echo "complexity delta gate: INSTALLED in $HOOK"
        exit 0
    fi
    echo "complexity delta gate: NOT INSTALLED in $HOOK" >&2
    echo "       run scripts/install_complexity_delta_gate.sh" >&2
    exit 1
    ;;
--uninstall)
    if [ -f "$BACKUP" ]; then
        cp -- "$BACKUP" "$HOOK.new"
        chmod +x "$HOOK.new"
        mv -f -- "$HOOK.new" "$HOOK"
        echo "restored the pmat-generated hook from $BACKUP"
        exit 0
    fi
    echo "ERROR: no backup at $BACKUP; re-run 'pmat hooks install --force'" >&2
    exit 1
    ;;
--install) ;;
*)
    echo "usage: $0 [--install|--check|--uninstall]" >&2
    exit 2
    ;;
esac

if installed; then
    echo "complexity delta gate: already installed in $HOOK (no change)"
    exit 0
fi

start=$(grep -n -E "$START_RE" "$HOOK" | cut -d: -f1) || start=""
n_start=$(printf '%s\n' "$start" | grep -c . || true)
if [ "$n_start" -ne 1 ]; then
    echo "ERROR: expected exactly 1 line matching /$START_RE/ in $HOOK, found $n_start." >&2
    echo "       The generated hook changed shape; re-anchor this installer instead of" >&2
    echo "       shipping a patch that silently does nothing." >&2
    exit 1
fi

mark=$(awk -v s="$start" -v re="$END_MARK_RE" 'NR > s && $0 ~ re { print NR }' "$HOOK")
n_mark=$(printf '%s\n' "$mark" | grep -c . || true)
if [ "$n_mark" -ne 1 ]; then
    echo "ERROR: expected exactly 1 line after $start matching /$END_MARK_RE/, found $n_mark." >&2
    exit 1
fi

end=$(awk -v m="$mark" 'NR > m && $0 == "fi" { print NR; exit }' "$HOOK")
if [ -z "$end" ]; then
    echo "ERROR: no closing 'fi' after line $mark in $HOOK" >&2
    exit 1
fi

tmp="$HOOK.new.$$"
{
    awk -v e="$((start - 1))" 'NR <= e' "$HOOK"
    cat <<'BLOCK'
# --- BEGIN complexity delta gate (#2766) ---
# The generated scan above measured whole STAGED FILES against an absolute
# threshold, so any file holding a pre-existing violation could not be edited at
# all. It is replaced by a DELTA gate: a violation that is new or worsened still
# refuses the commit; one you merely inherit does not.
_APR_DELTA_GATE="$(git rev-parse --show-toplevel)/scripts/complexity_delta_gate.sh"
if [ -x "$_APR_DELTA_GATE" ]; then
    "$_APR_DELTA_GATE" || exit 1
else
    echo "  Complexity delta check... MISSING $_APR_DELTA_GATE" >&2
    exit 1
fi
# --- END complexity delta gate (#2766) ---
BLOCK
    awk -v s="$((end + 1))" 'NR >= s' "$HOOK"
} >"$tmp"

# Verify before installing: a patch that leaves the old scan in place, or that
# does not parse, must never reach .git/hooks/.
fatal() {
    echo "ERROR: $1" >&2
    rm -f -- "$tmp"
    exit 1
}
grep -F -q "$MARKER" "$tmp" || fatal "spliced hook is missing the delta-gate marker"
if grep -q -F 'pmat analyze complexity --file' "$tmp"; then
    fatal "spliced hook still contains the absolute per-file scan"
fi
bash -n "$tmp" || fatal "spliced hook does not parse"

[ -f "$BACKUP" ] || cp -- "$HOOK" "$BACKUP"
chmod +x "$tmp"
mv -f -- "$tmp" "$HOOK"

echo "complexity delta gate: installed into $HOOK"
echo "  original saved at $BACKUP"
echo "  re-run this after any 'pmat hooks install' / 'make hooks-install'"
