// CONTRACT: gated-delta-net-v1.yaml
// HASH: sha256:c5d6e7f890123456
// Originally generated by: pv probar --binding
//
// BODIES ARE HAND-WRITTEN (PMAT-3321). `pv probar` emits empty `#[ignore]`d
// stubs; every body below is maintained by hand against the kernels the
// contract itself names under `simd_dispatch` and `depends_on`. Regenerating
// this file with `pv probar --binding` DISCARDS them — `make contract-regen`
// writes a `.rs.new` for review, review it, do not overwrite this file.
//
// The stubs carried the reason "Gated Delta Net not implemented". That was
// stale: the recurrence has shipped as
// `provable_contracts::kernels::gated_delta_net::gdn_recurrence_{scalar,avx2}`,
// the causal conv1d as `provable_contracts::kernels::conv1d::conv1d_scalar`,
// the decay's sigmoid as
// `provable_contracts::kernels::silu_standalone::sigmoid_scalar`, and the L2
// normalisation as `aprender::autograd::l2_normalize_rows`.

use aprender::autograd::{l2_normalize_rows, Tensor};
use proptest::prelude::*;
use provable_contracts::kernels::conv1d::conv1d_scalar;
use provable_contracts::kernels::gated_delta_net::gdn_recurrence_scalar;
use provable_contracts::kernels::silu_standalone::sigmoid_scalar;

/// Recover the recurrence's internal state matrix `S_t` for every timestep.
///
/// The kernel keeps `S` private, but it is fully observable through the read
/// `o_t = q_tᵀ S_t`: driving the query with the basis vector `e_i` at every
/// timestep makes `o_t` equal to row `i` of `S_t`, exactly (the other terms
/// enter the accumulator as `0.0 * s`, and `0.0 + y == y` in IEEE-754 for
/// finite `y`). `k`, `v`, `alpha`, `beta` do not depend on `q`, so the `k_dim`
/// probe runs all see the same state trajectory.
///
/// Returns `seq_len` matrices, each flattened `k_dim x v_dim` row-major.
fn recover_states(
    k: &[f32],
    v: &[f32],
    alpha: &[f32],
    beta: &[f32],
    seq_len: usize,
    k_dim: usize,
    v_dim: usize,
) -> Vec<Vec<f32>> {
    let mut states = vec![vec![0.0_f32; k_dim * v_dim]; seq_len];
    for i in 0..k_dim {
        let mut q = vec![0.0_f32; seq_len * k_dim];
        for t in 0..seq_len {
            q[t * k_dim + i] = 1.0;
        }
        let mut out = vec![0.0_f32; seq_len * v_dim];
        gdn_recurrence_scalar(&q, k, v, alpha, beta, seq_len, k_dim, v_dim, &mut out);
        for (t, state) in states.iter_mut().enumerate() {
            for j in 0..v_dim {
                state[i * v_dim + j] = out[t * v_dim + j];
            }
        }
    }
    states
}

/// L2 norm of a row, accumulated in f64 so the check is tighter than the
/// value it is checking.
fn row_norm(row: &[f32]) -> f64 {
    row.iter()
        .map(|&x| f64::from(x) * f64::from(x))
        .sum::<f64>()
        .sqrt()
}

proptest! {
    /// Obligation: Decay in unit interval (bound) — GDN-BND-001
    /// Formal: α_t = sigmoid(...) ∈ (0, 1) since sigmoid maps ℝ → (0, 1)
    /// Falsification: FALSIFY-GDN-001 (proptest with extreme values)
    #[test]
    fn prop_decay_in_unit_interval(
        a_log in -4.0f32..2.0,
        dt in -3.0f32..3.0,
        dt_bias in -3.0f32..3.0,
    ) {
        // The contract's `decay` equation, verbatim: α = σ(exp(A_log)·dt + dt_bias).
        let z = a_log.exp() * dt + dt_bias;
        // Contract precondition: the pre-activation is finite.
        prop_assume!(z.is_finite());

        let mut decay = [0.0_f32; 1];
        sigmoid_scalar(&[z], &mut decay);
        let alpha = decay[0];

        // The bound itself, over the whole finite domain: never NaN, never
        // outside the closed unit interval.
        prop_assert!(alpha.is_finite(), "alpha not finite for z={}: {}", z, alpha);
        prop_assert!(
            (0.0..=1.0).contains(&alpha),
            "alpha outside [0,1] for z={}: {}", z, alpha
        );

        // Strictness. Over ℝ the obligation is the OPEN interval, and that is
        // what the Lean proof establishes. In f32 the reference kernel
        // saturates: 1/(1+exp(-z)) rounds to exactly 1.0 once exp(-z) drops
        // below half an ulp of 1 (z ≳ 16.7), and to exactly 0.0 once exp(-z)
        // overflows (z ≲ -88). The open bound is therefore asserted on the
        // sub-domain where f32 can still represent it; the saturating tails are
        // pinned to the closed interval by the extreme-value table below rather
        // than hidden.
        if z.abs() <= 15.0 {
            prop_assert!(alpha > 0.0, "alpha not > 0 for z={}: {}", z, alpha);
            prop_assert!(alpha < 1.0, "alpha not < 1 for z={}: {}", z, alpha);
        }

        // FALSIFY-GDN-001, "extreme values": saturation must stay inside the
        // closed interval and must never manufacture a NaN.
        let extremes = [f32::MIN, -1.0e30, -100.0, 0.0, 100.0, 1.0e30, f32::MAX];
        let mut sat = [0.0_f32; 7];
        sigmoid_scalar(&extremes, &mut sat);
        for (&x, &y) in extremes.iter().zip(sat.iter()) {
            prop_assert!(
                y.is_finite() && (0.0..=1.0).contains(&y),
                "sigmoid({}) = {} escaped [0,1]", x, y
            );
        }
        // …and the interior of the domain is genuinely interior, so the table
        // above cannot pass by collapsing everything onto the endpoints.
        prop_assert!(
            sat[3] > 0.0 && sat[3] < 1.0,
            "sigmoid(0) = {} not interior", sat[3]
        );
    }

    /// Obligation: State shape preserved (invariant) — GDN-INV-002
    /// Formal: shape(state_{t+1}) == shape(state_t) == [k_dim, v_dim]
    /// Falsification: FALSIFY-GDN-002 (recurrence over random timesteps)
    #[test]
    fn prop_state_shape_preserved(
        seq_len in 1usize..8,
        k_dim in 1usize..5,
        v_dim in 1usize..5,
        pool in proptest::collection::vec(-2.0f32..2.0, 128),
        alpha_pool in proptest::collection::vec(0.0f32..1.0, 8),
        beta_pool in proptest::collection::vec(-1.0f32..1.0, 8),
    ) {
        let k = &pool[0..seq_len * k_dim];
        let v = &pool[64..64 + seq_len * v_dim];
        let alpha = &alpha_pool[..seq_len];
        let beta = &beta_pool[..seq_len];

        let states = recover_states(k, v, alpha, beta, seq_len, k_dim, v_dim);

        // The observable state is [k_dim, v_dim] at EVERY timestep, and each of
        // its k_dim*v_dim entries obeys the contract's `write` equation
        // S_{t+1} = α_t·S_t + k_t ⊗ δ_t (δ_t = v_t in this kernel) with S_0 = 0.
        // A state that changed shape — a rank-collapsed outer product, a
        // mis-strided row, a state that grew with t — cannot satisfy this for
        // every (i, j), which is what makes the shape claim falsifiable through
        // an API that never hands the state out.
        prop_assert_eq!(states.len(), seq_len);
        let mut expected = vec![0.0_f32; k_dim * v_dim];
        for t in 0..seq_len {
            prop_assert_eq!(
                states[t].len(),
                k_dim * v_dim,
                "state at t={} is not [k_dim={}, v_dim={}]",
                t, k_dim, v_dim
            );
            for i in 0..k_dim {
                for j in 0..v_dim {
                    // Same association order as the kernel, so this is exact.
                    expected[i * v_dim + j] = alpha[t] * expected[i * v_dim + j]
                        + beta[t] * k[t * k_dim + i] * v[t * v_dim + j];
                    let got = states[t][i * v_dim + j];
                    let want = expected[i * v_dim + j];
                    prop_assert!(
                        (got - want).abs() <= 1e-6 * want.abs().max(1.0),
                        "state[t={}][{},{}] = {}, write equation says {}",
                        t, i, j, got, want
                    );
                }
            }
        }
    }

    /// Obligation: Causal conv1d (invariant) — GDN-INV-003
    /// Formal: conv1d output at t depends only on t..t-k+1
    /// Falsification: FALSIFY-GDN-003 (modifying future input must not move the
    /// current output)
    #[test]
    fn prop_causal_conv1d(
        length in 4usize..16,
        kernel_size in 1usize..5,
        cut in 0usize..14,
        weight_pool in proptest::collection::vec(-1.5f32..1.5, 4),
        input_pool in proptest::collection::vec(-2.0f32..2.0, 16),
        bump in 0.5f32..3.0,
    ) {
        prop_assume!(cut + 1 < length);
        let weight = &weight_pool[..kernel_size];
        // The tap that reads position `ol` itself; anti-vacuity below needs it.
        prop_assume!(weight[kernel_size - 1].abs() > 1e-3);

        // Causal configuration: left padding of k-1 with stride 1, which is how
        // a GDN/Mamba short conv is wired. in_pos = ol + kk - (k-1) ≤ ol, so
        // output ol reads only ol-(k-1)..=ol.
        let padding = kernel_size - 1;
        let out_length = length + 2 * padding - kernel_size + 1;
        let input = &input_pool[..length];

        let mut base = vec![0.0_f32; out_length];
        conv1d_scalar(input, weight, None, 1, 1, length, kernel_size, 1, padding, &mut base);

        // Perturb every input strictly after `cut`.
        let mut future = input.to_vec();
        for x in future.iter_mut().skip(cut + 1) {
            *x += bump;
        }
        let mut perturbed = vec![0.0_f32; out_length];
        conv1d_scalar(&future, weight, None, 1, 1, length, kernel_size, 1, padding, &mut perturbed);

        // Bit-exact: a causal window does not merely round to the same value,
        // it never adds the future term to the accumulator at all.
        for ol in 0..=cut {
            prop_assert_eq!(
                base[ol].to_bits(),
                perturbed[ol].to_bits(),
                "conv1d output at t={} moved ({} -> {}) when only inputs > {} changed",
                ol, base[ol], perturbed[ol], cut
            );
        }
        // Anti-vacuity: the perturbation must actually be visible SOMEWHERE, or
        // the loop above would pass for a kernel that ignores its input.
        prop_assert!(
            base[cut + 1] != perturbed[cut + 1],
            "future perturbation never reached the output at t={}: {} == {}",
            cut + 1, base[cut + 1], perturbed[cut + 1]
        );

        // The same causality for the recurrence the conv1d feeds: o_t = q_tᵀ S_t
        // and S_t is accumulated from timesteps 0..=t only. q and k are drawn
        // positive so q_{t+1}·k_{t+1} > 0 and the anti-vacuity check below is
        // deterministic rather than a coin flip on a near-orthogonal pair.
        let seq_len = length.min(6);
        prop_assume!(cut + 1 < seq_len);
        let (k_dim, v_dim) = (3_usize, 2_usize);
        let q: Vec<f32> = (0..seq_len * k_dim).map(|i| 0.5 + (i % 3) as f32 * 0.25).collect();
        let kk: Vec<f32> = (0..seq_len * k_dim).map(|i| 0.5 + (i % 4) as f32 * 0.25).collect();
        let vv: Vec<f32> = (0..seq_len * v_dim).map(|i| (i as f32) * 0.3 - 0.5).collect();
        let alpha = vec![0.7_f32; seq_len];
        let beta = vec![0.4_f32; seq_len];

        let mut rec_base = vec![0.0_f32; seq_len * v_dim];
        gdn_recurrence_scalar(&q, &kk, &vv, &alpha, &beta, seq_len, k_dim, v_dim, &mut rec_base);

        let mut vv_future = vv.clone();
        for x in vv_future.iter_mut().skip((cut + 1) * v_dim) {
            *x += bump;
        }
        let mut rec_perturbed = vec![0.0_f32; seq_len * v_dim];
        gdn_recurrence_scalar(
            &q, &kk, &vv_future, &alpha, &beta, seq_len, k_dim, v_dim, &mut rec_perturbed,
        );

        for idx in 0..(cut + 1) * v_dim {
            prop_assert_eq!(
                rec_base[idx].to_bits(),
                rec_perturbed[idx].to_bits(),
                "recurrence output {} moved when only v at timesteps > {} changed",
                idx, cut
            );
        }
        prop_assert!(
            rec_base[(cut + 1) * v_dim] != rec_perturbed[(cut + 1) * v_dim],
            "future perturbation never reached the recurrence output at t={}",
            cut + 1
        );
    }

    /// Obligation: L2 norm preserves direction (invariant) — GDN-INV-004
    /// Formal: L2(q) / ||L2(q)|| ≈ q / ||q||
    /// Falsification: FALSIFY-GDN-004 (cosine similarity ≈ 1)
    #[test]
    fn prop_l2_norm_preserves_direction(
        batch in 1usize..4,
        hidden in 2usize..8,
        pool in proptest::collection::vec(-10.0f32..10.0, 32),
        scale in 0.5f32..4.0,
    ) {
        let data: Vec<f32> = pool[..batch * hidden].iter().map(|x| x * scale).collect();
        let x = Tensor::new(&data, &[batch, hidden]);
        let y = l2_normalize_rows(&x, 1e-12)
            .expect("l2_normalize_rows rejected a finite, non-degenerate input");
        prop_assert_eq!(y.shape(), &[batch, hidden]);

        for b in 0..batch {
            let xs = &data[b * hidden..(b + 1) * hidden];
            let ys = &y.data()[b * hidden..(b + 1) * hidden];
            let nx = row_norm(xs);
            // The zero vector has no direction to preserve, and below the eps
            // clamp the op is a different function (x/eps); stay off both.
            prop_assume!(nx > 1e-3);
            let ny = row_norm(ys);

            // Anti-vacuity: the identity map preserves direction trivially, so
            // first prove something was actually normalised.
            prop_assert!(
                (ny - 1.0).abs() < 1e-5,
                "row {} was not normalised: ||y|| = {}", b, ny
            );

            // Direction: cosine similarity is 1 — parallel AND same sense.
            let dot: f64 = xs
                .iter()
                .zip(ys.iter())
                .map(|(&a, &c)| f64::from(a) * f64::from(c))
                .sum();
            let cos = dot / (nx * ny);
            prop_assert!(
                (cos - 1.0).abs() < 1e-6,
                "row {} changed direction: cos = {}", b, cos
            );

            // Cosine is second-order blind to a small rotation (1 - cos ≈ θ²/2),
            // so pin the angle linearly too: every 2-D minor of [x; y] vanishes
            // iff y is a scalar multiple of x.
            for j in 1..hidden {
                let cross = f64::from(xs[0]) * f64::from(ys[j])
                    - f64::from(xs[j]) * f64::from(ys[0]);
                let tol = 1e-5 * nx + 1e-9;
                prop_assert!(
                    cross.abs() <= tol,
                    "row {} not parallel to input: minor(0,{}) = {} > {}",
                    b, j, cross, tol
                );
            }
        }
    }

    /// Obligation: SIMD matches scalar within ULP (equivalence) — GDN-EQ-005
    /// Tolerance: 8 ULP (gated-delta-net-v1.yaml, GDN-EQ-005)
    /// Falsification: FALSIFY-GDN-005 (SIMD reduction order differs)
    ///
    /// Gated on runtime AVX2 detection. Where AVX2 is absent this obligation is
    /// reported N/A on stdout — it is NOT silently skipped, and it is NOT
    /// claimed as a pass for a backend that never ran.
    #[test]
    fn prop_simd_equivalence(
        seq_len in 1usize..8,
        k_dim in 1usize..5,
        v_dim in 1usize..5,
        pool in proptest::collection::vec(-2.0f32..2.0, 192),
        alpha_pool in proptest::collection::vec(0.0f32..1.0, 8),
        beta_pool in proptest::collection::vec(-1.0f32..1.0, 8),
    ) {
        #[cfg(target_arch = "x86_64")]
        {
            if is_x86_feature_detected!("avx2") {
                use provable_contracts::kernels::gated_delta_net::gdn_recurrence_avx2;
                use provable_contracts::kernels::ulp::ulp_distance;

                let q = &pool[0..seq_len * k_dim];
                let k = &pool[64..64 + seq_len * k_dim];
                let v = &pool[128..128 + seq_len * v_dim];
                let alpha = &alpha_pool[..seq_len];
                let beta = &beta_pool[..seq_len];

                let mut scalar_out = vec![0.0_f32; seq_len * v_dim];
                let mut avx2_out = vec![0.0_f32; seq_len * v_dim];
                gdn_recurrence_scalar(
                    q, k, v, alpha, beta, seq_len, k_dim, v_dim, &mut scalar_out,
                );
                // SAFETY: guarded by the `is_x86_feature_detected!("avx2")`
                // above, which is the entire safety obligation of a
                // `#[target_feature(enable = "avx2")]` fn.
                //
                // `unsafe_code` is DENY (not forbid) workspace-wide, and this is
                // the narrowest possible opt-out: one block, in a test, whose
                // only purpose is to call the SIMD entry point the contract
                // names in `simd_dispatch`. There is no safe wrapper — checking
                // GDN-EQ-005 without calling `gdn_recurrence_avx2` would mean
                // comparing the scalar kernel to itself. The `unsafe_code` gate
                // that this crate ships (`f_dod_unsafe_code_is_deny_by_default`)
                // scans `crates/aprender-core/src`, not `tests/`, so this does
                // not widen the audited unsafe surface of the library.
                #[allow(unsafe_code)]
                unsafe {
                    gdn_recurrence_avx2(
                        q, k, v, alpha, beta, seq_len, k_dim, v_dim, &mut avx2_out,
                    );
                }

                prop_assert_eq!(scalar_out.len(), avx2_out.len());
                for (i, (&s, &a)) in scalar_out.iter().zip(avx2_out.iter()).enumerate() {
                    let dist = ulp_distance(s, a);
                    prop_assert!(
                        dist <= 8,
                        "GDN-EQ-005: avx2 vs scalar at {}: {} vs {} ({} ULP > 8)",
                        i, s, a, dist
                    );
                }
            } else {
                println!(
                    "GDN-EQ-005: N/A — avx2 not detected on this host; \
                     SIMD/scalar equivalence is UNVERIFIED here, not passing."
                );
            }
        }
        #[cfg(not(target_arch = "x86_64"))]
        {
            let _ = (seq_len, k_dim, v_dim, pool, alpha_pool, beta_pool);
            println!(
                "GDN-EQ-005: N/A — no AVX2 backend on this target_arch; \
                 SIMD/scalar equivalence is UNVERIFIED here, not passing."
            );
        }
    }
}
