#!/usr/bin/env bash
# Regenerate src/unicode_tables.rs from the Unicode Character Database (UCD).
#
# Usage: gen_unicode_tables.sh <UCD dir> > src/unicode_tables.rs   (needs GNU awk: strtonum, asort)
#
# The judge this crate ports ran on CPython 3.13, whose `unicodedata` is Unicode 15.1.0. The UCD that
# ships with Ubuntu is 14.0.0, so two 15.0 digit runs are added by hand below (15.1 added no digits).
# The other 15.0/15.1 additions are NOT here: they count as unassigned, so `repr` escapes them where
# CPython would print them. src/pyval.rs says so where it uses the table.
set -euo pipefail

ucd="${1:?usage: gen_unicode_tables.sh <UCD dir>}"
data="${ucd}/UnicodeData.txt"
fold="${ucd}/CaseFolding.txt"
for f in "${data}" "${fold}"; do
  if [ ! -r "${f}" ]; then
    printf 'unreadable: %s\n' "${f}" >&2
    exit 1
  fi
done
version="$(sed -n 's/^# CaseFolding-\([0-9.]*\)\.txt$/\1/p' "${fold}")"
if [ -z "${version}" ]; then
  printf 'no version line in %s\n' "${fold}" >&2
  exit 1
fi

printf '// GENERATED by gen_unicode_tables.sh from UCD %s. Do not edit by hand.\n\n' "${version}"

gawk -F';' '
function flush() { if (lo >= 0) { printf "    (0x%04X, 0x%04X),\n", lo, hi; lo = -1 } }
function mark(cp, ok) {
  if (ok && lo >= 0 && cp == hi + 1) { hi = cp; return }
  if (ok) { flush(); lo = cp; hi = cp; return }
  flush()
}
BEGIN {
  lo = -1
  print "/// Code points that CPython str.isprintable() accepts: assigned, not in Cc Cf Cs Co Zl Zp Zs, plus U+0020."
  print "#[rustfmt::skip]"
  print "pub const PRINTABLE: &[(u32, u32)] = &["
}
{
  cp = strtonum("0x" $1); cat = $3
  ok = (cat !~ /^(Cc|Cf|Cs|Co|Zl|Zp|Zs)$/) || cp == 32
  if ($2 ~ /, First>$/) { first = cp; next }
  if ($2 ~ /, Last>$/) { for (c = first; c <= cp; c++) mark(c, ok); next }
  if (cp != hi + 1) flush()
  mark(cp, ok)
}
END { flush(); print "];" }
' "${data}"

printf '\n'

gawk -F';' '
BEGIN {
  print "/// The first code point of every Nd run (decimal value 0); a run is ten digits, 0 to 9."
  print "#[rustfmt::skip]"
  print "pub const DIGIT_ZEROS: &[u32] = &["
}
$3 == "Nd" && $7 == "0" { z[n++] = strtonum("0x" $1) }
END {
  # Unicode 15.0: KAWI DIGIT ZERO and NAG MUNDARI DIGIT ZERO.
  z[n++] = strtonum("0x11F50"); z[n++] = strtonum("0x1E4F0")
  asort(z)
  for (i = 1; i <= n; i++) printf "    0x%04X,\n", z[i]
  print "];"
}
' "${data}"

printf '\n'

gawk -F'; ' '
BEGIN {
  print "/// str.casefold(): CaseFolding.txt statuses C and F, sorted by code point."
  print "#[rustfmt::skip]"
  print "pub const CASEFOLD: &[(u32, &str)] = &["
}
/^[0-9A-F]/ && ($2 == "C" || $2 == "F") {
  split($3, t, " "); s = ""
  for (i = 1; i in t; i++) s = s "\\u{" t[i] "}"
  printf "    (0x%s, \"%s\"),\n", $1, s
}
END { print "];" }
' "${fold}"
