//! Port of `scripts/lib/tarball_workspace.py` (#4114): turn `DIR/pkgs/<name>-<ver>/`
//! (unpacked `.crate` files) into one workspace.
//!
//! [`write_workspace`] writes `DIR/Cargo.toml` with every unpacked crate as a member and a
//! `[patch.crates-io]` entry per crate pointing at its unpacked directory. Before a publish
//! the siblings are not on crates.io at the new version, so without the patch nothing would
//! resolve; with it, every sibling compiles from its TARBALL, never from the repository's
//! sources. It prints `<name>\t<version>\t<dir>` per crate, and refuses when `DIR/pkgs`
//! holds nothing or a manifest cannot be read, because an empty workspace would build green
//! and prove nothing.
//!
//! [`package_name`] is `--name DIR`: the `[package]` name of one unpacked crate (a
//! `--crate-file` substitution keys on the manifest, never on a split of the directory
//! name: a version may hold `-`, e.g. `0.70.0-rc.1`). [`target_dir`] is `--target-dir`:
//! `cargo metadata` JSON on stdin to its `target_directory`.

use serde_json::Value;
use std::path::Path;

/// First line of the generated `Cargo.toml`. The original named itself here; the port names
/// the subcommand that now writes the file.
pub const HEADER: &str = "# Generated by aprender-ci-tools tarball-workspace (#4114): the published tarballs, and nothing else.";

/// `--target-dir`: the `target_directory` line (with its `\n`), or the refusal message.
///
/// # Errors
/// Metadata that is not JSON, or has no string `target_directory`.
pub fn target_dir(metadata: &[u8]) -> Result<String, String> {
    let meta: Value = serde_json::from_slice(metadata)
        .map_err(|e| format!("tarball_workspace: no target_directory in cargo metadata: {e}"))?;
    meta.get("target_directory")
        .and_then(Value::as_str)
        .map(|t| format!("{t}\n"))
        .ok_or_else(|| {
            "tarball_workspace: no target_directory in cargo metadata: 'target_directory'"
                .to_owned()
        })
}

/// The `[package]` table's `name` and `version` of `dir/Cargo.toml`.
fn manifest(dir: &Path) -> Result<(String, String), String> {
    let path = dir.join("Cargo.toml");
    let text = std::fs::read_to_string(&path).map_err(|e| format!("{e}"))?;
    let table: toml::Table = text.parse().map_err(|e| format!("{e}"))?;
    let pkg = table.get("package").ok_or("'package'")?;
    let field = |key: &str| {
        pkg.get(key)
            .and_then(toml::Value::as_str)
            .map(str::to_owned)
            .ok_or_else(|| format!("'{key}'"))
    };
    Ok((field("name")?, field("version")?))
}

/// `--name DIR`: the crate's `[package]` name (with its `\n`), or the refusal message.
///
/// # Errors
/// No readable `DIR/Cargo.toml`, or no string `[package]` name in it.
pub fn package_name(dir: &str) -> Result<String, String> {
    let path = Path::new(dir).join("Cargo.toml");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| format!("tarball_workspace: no package name in {dir}: {e}"))?;
    let table: toml::Table = text
        .parse()
        .map_err(|e| format!("tarball_workspace: no package name in {dir}: {e}"))?;
    table
        .get("package")
        .and_then(|p| p.get("name"))
        .and_then(toml::Value::as_str)
        .map(|n| format!("{n}\n"))
        .ok_or_else(|| format!("tarball_workspace: no package name in {dir}: 'name'"))
}

/// `str(pathlib.PurePosixPath(p))`: repeated and trailing slashes and `.` parts are dropped;
/// exactly two leading slashes are kept (POSIX leaves `//` implementation-defined); an empty
/// path is `.`.
fn py_pure_path(p: &str) -> String {
    let root = if p.starts_with("//") && !p.starts_with("///") {
        "//"
    } else if p.starts_with('/') {
        "/"
    } else {
        ""
    };
    let parts: Vec<&str> = p
        .split('/')
        .filter(|s| !s.is_empty() && *s != ".")
        .collect();
    match (root, parts.is_empty()) {
        ("", true) => ".".to_owned(),
        (r, _) => format!("{r}{}", parts.join("/")),
    }
}

/// `str(Path(base) / name)`: a `.` base contributes nothing.
fn py_join(base: &str, name: &str) -> String {
    match base {
        "." => name.to_owned(),
        b if b.ends_with('/') => format!("{b}{name}"),
        b => format!("{b}/{name}"),
    }
}

/// `DIR`: write `DIR/Cargo.toml` and return the `<name>\t<version>\t<dir>` rows (with a
/// final `\n`), or the refusal message. Nothing is written on a refusal.
///
/// # Errors
/// No crate under `DIR/pkgs`, an unreadable manifest, a non-UTF-8 directory name, or a
/// failed write.
pub fn write_workspace(dir: &str) -> Result<String, String> {
    let root = py_pure_path(dir);
    let pkgs_dir = py_join(&root, "pkgs");
    let mut pkgs: Vec<String> = Vec::new();
    if Path::new(&pkgs_dir).is_dir() {
        let entries = std::fs::read_dir(&pkgs_dir).map_err(|e| format!("{pkgs_dir}: {e}"))?;
        for entry in entries {
            let entry = entry.map_err(|e| format!("{pkgs_dir}: {e}"))?;
            let name = entry
                .file_name()
                .into_string()
                .map_err(|n| format!("tarball_workspace: a directory name is not UTF-8: {n:?}"))?;
            if Path::new(&py_join(&pkgs_dir, &name))
                .join("Cargo.toml")
                .is_file()
            {
                pkgs.push(name);
            }
        }
    }
    // pathlib orders siblings by their name string: code-point order, which is the byte
    // order of UTF-8.
    pkgs.sort_unstable();
    if pkgs.is_empty() {
        return Err(format!(
            "tarball_workspace: no unpacked crate under {root}/pkgs"
        ));
    }
    let (mut members, mut patch, mut rows) = (Vec::new(), Vec::new(), Vec::new());
    for name in &pkgs {
        let d = py_join(&pkgs_dir, name);
        let (pname, version) = manifest(Path::new(&d))
            .map_err(|e| format!("tarball_workspace: unreadable manifest {d}/Cargo.toml: {e}"))?;
        members.push(format!("    \"pkgs/{name}\","));
        patch.push(format!("{pname} = {{ path = \"pkgs/{name}\" }}"));
        rows.push(format!("{pname}\t{version}\t{d}"));
    }
    let toml = format!(
        "{HEADER}\n[workspace]\nresolver = \"2\"\nmembers = [\n{}\n]\n\n[patch.crates-io]\n{}\n",
        members.join("\n"),
        patch.join("\n")
    );
    let out = py_join(&root, "Cargo.toml");
    std::fs::write(&out, toml).map_err(|e| format!("{out}: {e}"))?;
    Ok(format!("{}\n", rows.join("\n")))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pure_path_matches_pathlib() {
        for (p, want) in [
            ("", "."),
            (".", "."),
            ("./", "."),
            ("./a/", "a"),
            ("a//b/./c/", "a/b/c"),
            ("/", "/"),
            ("//", "//"),
            ("///", "/"),
            ("//a", "//a"),
            ("///a//", "/a"),
            ("a/../b", "a/../b"),
        ] {
            assert_eq!(py_pure_path(p), want, "PurePosixPath({p:?})");
        }
        assert_eq!(py_join(".", "pkgs"), "pkgs");
        assert_eq!(py_join("/", "pkgs"), "/pkgs");
        assert_eq!(py_join("//", "pkgs"), "//pkgs");
        assert_eq!(py_join("a", "pkgs"), "a/pkgs");
    }

    #[test]
    fn target_dir_reads_the_metadata_field() {
        assert_eq!(
            target_dir(br#"{"target_directory":"/t"}"#).as_deref(),
            Ok("/t\n")
        );
        assert!(target_dir(b"{").is_err());
        assert!(target_dir(br#"{"packages":[]}"#).is_err());
        assert!(target_dir(br#"{"target_directory":5}"#).is_err());
    }

    fn crate_dir(root: &Path, dir: &str, manifest: &str) {
        let d = root.join("pkgs").join(dir);
        std::fs::create_dir_all(&d).expect("mkdir");
        std::fs::write(d.join("Cargo.toml"), manifest).expect("write manifest");
    }

    fn scratch(tag: &str) -> std::path::PathBuf {
        let d =
            std::env::temp_dir().join(format!("ci-tools-tarball-ws-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).expect("mkdir scratch");
        d
    }

    #[test]
    fn writes_members_patch_and_rows_in_name_order() {
        let root = scratch("ok");
        crate_dir(
            &root,
            "b-0.70.0-rc.1",
            "[package]\nname = \"b\"\nversion = \"0.70.0-rc.1\"\n",
        );
        crate_dir(
            &root,
            "a-1.0.0",
            "[package]\nname = 'a'\nversion = \"1.0.0\"\n",
        );
        std::fs::create_dir_all(root.join("pkgs/no-manifest")).expect("mkdir");
        std::fs::write(root.join("pkgs/stray.txt"), "x").expect("write");
        let r = root.to_str().expect("utf-8 scratch");
        assert_eq!(
            write_workspace(&format!("{r}/")).as_deref(),
            Ok(
                format!("a\t1.0.0\t{r}/pkgs/a-1.0.0\nb\t0.70.0-rc.1\t{r}/pkgs/b-0.70.0-rc.1\n")
                    .as_str()
            )
        );
        assert_eq!(
            std::fs::read_to_string(root.join("Cargo.toml")).expect("read"),
            format!(
                "{HEADER}\n{}",
                "[workspace]\nresolver = \"2\"\nmembers = [\n    \"pkgs/a-1.0.0\",\n    \"pkgs/b-0.70.0-rc.1\",\n]\n\n\
                 [patch.crates-io]\na = { path = \"pkgs/a-1.0.0\" }\nb = { path = \"pkgs/b-0.70.0-rc.1\" }\n"
            )
        );
        assert_eq!(
            package_name(&format!("{r}/pkgs/b-0.70.0-rc.1")).as_deref(),
            Ok("b\n")
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn refuses_an_empty_workspace_and_a_bad_manifest_without_writing() {
        let root = scratch("bad");
        let r = root.to_str().expect("utf-8 scratch").to_owned();
        assert!(write_workspace(&r).is_err(), "no pkgs dir");
        std::fs::create_dir_all(root.join("pkgs/empty")).expect("mkdir");
        assert!(write_workspace(&r).is_err(), "no crate in pkgs");
        crate_dir(&root, "a-1", "[package]\nname = \"a\"\nversion = \"1\"\n");
        crate_dir(&root, "z-1", "[package]\nname = \"z\"\n");
        assert_eq!(
            write_workspace(&r),
            Err(format!(
                "tarball_workspace: unreadable manifest {r}/pkgs/z-1/Cargo.toml: 'version'"
            ))
        );
        assert!(
            !root.join("Cargo.toml").exists(),
            "a refusal writes nothing"
        );
        assert!(package_name(&format!("{r}/pkgs/empty")).is_err());
        let _ = std::fs::remove_dir_all(&root);
    }
}
